### ISSUE TITLE
Release not-shaded artifacts

### ISSUE THREAD

**Issue by hekonsek** [spotify/docker-client#100]
Hi,

First of all - I love your library :) . Really good job!

I'm concerned about one thing. Having JAX-RS API shaded into docker-client is usually fine, but in some cases may be problematic and leads to `java.lang.LinkageError`. The usual solution for such `java.lang.LinkageError` is to exclude JAX-RS jar from the project and leave only code shaded within the docker-client jar. But if docker-client is an Maven-optional library in your project, while some other dependency providing JAX-RS is required, then excluding JAX-RS is not really an option.

Since jars shipping shaded dependencies can be tricky (especially when shaded code perform `instanceof` checks, like `javax.ws.rs.client.ClientBuilder#newBuilder()` does), it is a good practice to release two versions of the artifacts - shaded and not-shaded. Can you guys consider releasing both shaded and not-shaded version of the library?

Cheers.

**Comment by matthewwerny** [comment]
I have added pull request https://github.com/spotify/docker-client/pull/123 to allow for the change.  I would love to see this get accepted, as I have a major project that I think will benefit the community greatly that is blocked by the need for an unshaded version of this library.  Thanks!

**Comment by rohansingh** [comment]
Fixed by #123.
