### ISSUE TITLE
Connecting with a remote cloud

### ISSUE THREAD

**Issue by ViniciusDeAndrade** [spotify/docker-client#1002]
Hello everybody.
I have a particular cloud  running a docker app, and I can connect with it using ssh and the Docker CLI.
Basically I set on CLI a ssh command, my userId and a password to connect.

How can I do that with a method using this client?
Thanks

**Comment by davidxia** [comment]
Feel free to create another issue if you're having problems. If you figure out the remote docker API endpoints your docker CLi command is making, you can use the [docs](https://github.com/spotify/docker-client/blob/master/docs/user_manual.md) to figure out the DockerClient methods to use. The client methods map one-to-one with the remote docker API endpoints.

**Comment by ViniciusDeAndrade** [comment]
This old one was already solve.
Thanks

`public static DockerClient conn() {
		DockerClient docker = null;		
		docker = DefaultDockerClient.builder().uri(URI.create("http:IP")).build();
		return docker;
		
	}`
