### ISSUE TITLE
copyToContainer - Cannot resolve method?

### ISSUE THREAD

**Issue by rwmajor2** [spotify/docker-client#1004]
I am trying to do something real simple like:
```java
   try {
      docker.copyToContainer(pathNotebook, contid, "/home/jovyan");
    }
    catch (DockerException ex) {
      throw new RuntimeException(ex.getMessage() + " Unable to copy file.");
    }
```

However, it keeps telling me that `Cannot resolve method copyToContainer(java.lang.String, java.lang.String, java.lang.String)`.

Any thoughts on what's going on?  My docker object is good, as I am using it for other operations prior to this.

**Comment by mattnworb** [comment]
These are the two method signatures for the copyToContainer methods as of the latest version of this library: https://github.com/spotify/docker-client/blob/643d3aba5027781d26236791ba10ea3e115f5548/src/main/java/com/spotify/docker/client/DockerClient.java#L1356-L1360

There is no `(String, String, String)` overload.
