### ISSUE TITLE
Question:  Best way to see if can connect to Docker client?

### ISSUE THREAD

**Issue by rwmajor2** [spotify/docker-client#1009]
What's the best way to determine if the Docker environment can be connected to from this Java SDK.

For example, the following will succeed if Docker is not running:
```java
   DockerClient docker;
    try {
      docker = DefaultDockerClient.fromEnv().build();
    }
    catch (DockerCertificateException e) {
      throw new AdminException(AdminLogCode.FAILED_TO_ESTABLISH_DOCKER_ENVIRONMENT.message(), e);
    }
```

It's not until I actually try to use the docker object that it generates an error.  Is there an easy way to "test the connection" without handling an error?

**Comment by mattnworb** [comment]
The DockerClient interface has a `ping()` method that will try to communicate with the daemon's API and will fail if the daemon is not reachable.

**Comment by rwmajor2** [comment]
Thanks @mattnworb.  That will work.
