### ISSUE TITLE
Maven is not getting all classes

### ISSUE THREAD

**Issue by ViniciusDeAndrade** [spotify/docker-client#1011]
Hello.

I am not getting all classes and methods inside some another ones that I am.
For example: I cannot import the Spread and Preferences classes.
here is my pom dependency.

`
<dependencies>

		<dependency>
			<groupId>com.spotify</groupId>

			<artifactId>docker-client</artifactId>

			<version>LATEST</version>

		</dependency>

	</dependencies>`

thanks

**Comment by davidxia** [comment]
Could you provide more information and maybe a way to reproduce?

**Comment by ViniciusDeAndrade** [comment]
I have forced the maven to solve this.
