### ISSUE TITLE
Please merge PR #887

### ISSUE THREAD

**Issue by chrsoo** [spotify/docker-client#1014]
Hi, 

In the Response Times section of the [contributing guidelines](https://github.com/spotify/docker-client/blob/master/CONTRIBUTING.md#response-times) I read 

> Please poke us if you feel you're being neglected, and we'll do our best to get back to you.

Comments on the PR does not seem to help, could you please approve #887?

**Comment by davidxia** [comment]
@chrsoo Sorry for the delay. I just reviewed https://github.com/spotify/docker-client/pull/1007.
