### ISSUE TITLE
Copying File to Container via Stream without an actual file?

### ISSUE THREAD

**Issue by rwmajor2** [spotify/docker-client#1015]
I know there is the method copyToContainer() which gets a file into a container and works well.  I also know that it can take an InputStream.

My question is does anyone know how I can copy a "file" to the container without having an actual file on disk?  I can write text into a Stream to be used as the InputStream, but it seems like Docker really wants this to be an actual file.

Thoughts?  Appreciate any input.

**Comment by mattnworb** [comment]
Like you alluded to, if I had the data I wanted to appear in the file inside the container available as a `byte[]` or something else in memory of my program, I would just pass that in to `copyToContainer()` as a `ByteArrayInputStream` or some other applicable subclass of `InputStream`.

**Comment by rwmajor2** [comment]
Thanks Matt.  I found a work-around for now to do execCreate and just "echo" my file to the container, since it is just a simple text file.
