### ISSUE TITLE
How to handle the "shaded" classifier for a dependency that depends on spotify docker-client?

### ISSUE THREAD

**Issue by pswenson** [spotify/docker-client#1017]
## Description

I am using this project https://github.com/geowarin/docker-junit-rule which depends on the spotify docker client.  I am using a dropwizard project which is having jersey collisions as documented here: https://github.com/spotify/docker-client#a-note-on-shading.  The document suggests to use ` <classifier>shaded</classifier>`

However since I'm getting the docker client as a transitive dependency I don't know how to pass this on from my pom.xml.

Any suggestion on how to modify this dependency to pass on the `shaded`?

``` 
<dependency>
      <groupId>com.github.geowarin</groupId>
      <artifactId>docker-junit-rule</artifactId>
      <version>1.1.0</version>
</dependency>
```

Or do I need to build the docker-junit-rule to somehow pass in the shaded classifier?

thanks!

**Comment by davidxia** [comment]
Hm, I'm not entirely sure. Does [anything here help](https://maven.apache.org/plugins/maven-shade-plugin/examples/class-relocation.html) or would you need docker-junit-rule to provide a shaded version of itself?
