### ISSUE TITLE
Question:  How to make execCreate() wait for command to finish

### ISSUE THREAD

**Issue by rwmajor2** [spotify/docker-client#1018]
I have the following snippet:
```
ExecCreation execId = docker.execCreate(id,
                new String[]{"bash", "-c", "python .get_item_from_portal.py " + itemId},
                DockerClient.ExecCreateParam.attachStdout(),
                DockerClient.ExecCreateParam.attachStderr());
        stream = docker.execStart(execId.id(), DockerClient.ExecStartParameter.TTY);
```
that runs a Python script.  However, I want this code to wait for the Python code to finish running.  Currently, it is not.  Is there a way to make this happen?

**Comment by johnflavin** [comment]
This is off the top of my head; I don't remember exactly. But I think if you read from the stream with `readFully()` the thread will block until the stream is closed by docker.

**Comment by rwmajor2** [comment]
Thanks @johnflavin.  I think that definitely helps.
