### ISSUE TITLE
Add support for AWS ECR variant of `RegistryAuthSupplier`

### ISSUE THREAD

**Issue by 56quarters** [spotify/docker-client#1019]
Much like there is a `RegistryAuthSupplier` for authenticating with Google's container repository, there could be an implementation that works with AWS ECR repositories. This implementation could make use of the [AWS Java SDK](http://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22com.amazonaws%22%20AND%20a%3A%22aws-java-sdk-ecr%22) to generate ECR credentials on the fly. 

A rough sketch of the API would be...

```java
public class AwsEcrRegistryAuthSupplier implements RegistryAuthSupplier {

    private final AmazonECR client;

    public AwsEcrRegistryAuthSupplier(AmazonECR client) {
        this.client = client;
    }

    @Override
    public RegistryAuth authFor(String imageName) throws DockerException {
        client.getAuthorizationToken(/* ... */)
        return null;
    }
    
    // ... other methods
}
```

Would you accept a pull request that added support for this using the existing `ContainerRegistryAuthSupplier` Google implementation as a model?

If this functionality was accepted, a follow up issue + PR would probably add use of it to the [spotify/dockerfile-maven](https://github.com/spotify/dockerfile-maven) plugin.

Thanks!

**Comment by davidxia** [comment]
See https://github.com/spotify/docker-client/pull/1013 and https://github.com/spotify/docker-client/pull/876.

**Comment by 56quarters** [comment]
Whoops, missed those PRs
