### ISSUE TITLE
LogStream.readFully() returns an empty String

### ISSUE THREAD

**Issue by daniloradenovic** [spotify/docker-client#1025]
## Description
LogStream.readFully() sometimes returns an empty String, even though the output is not empty.

## How to reproduce
Create and start container with
`docker run busybox echo "Hello World"`
and then try to read logs multiple times.

Here's a [test case](https://github.com/daniloradenovic/docker-client/commit/585a5097e06ac07dadcbbbf33d0aacf3bc461224).

## What do you expect

If the container produced some output on stdout, it should always be returned.

## What happened instead

Sometimes an empty String is returned.

## Software:

- `docker version`: 

Client:
 Version:      18.03.1-ce
 API version:  1.37
 Go version:   go1.9.5
 Git commit:   9ee9f40
 Built:        Thu Apr 26 07:13:02 2018
 OS/Arch:      darwin/amd64
 Experimental: false
 Orchestrator: swarm

Server:
 Engine:
  Version:      18.03.1-ce
  API version:  1.37 (minimum version 1.12)
  Go version:   go1.9.5
  Git commit:   9ee9f40
  Built:        Thu Apr 26 07:22:38 2018
  OS/Arch:      linux/amd64
  Experimental: true
- Spotify's docker-client version: 8.11.4-SNAPSHOT (5b1dc681e7c68b3a941af65dca288c3985c0f9f0)

**Comment by johnflavin** [comment]
This is interesting

**Comment by daniloradenovic** [comment]
You're right, this is actually a docker problem. Sorry for the early judgment. 

I've ran 1000 containers in a bash script and the logs were missing a few times. Here's the script if anyone is interested.

```bash
#!/usr/bin/env bash

container_name="helloworldcontainer"

docker rm $container_name || echo "Container $container_name does not exist"
docker run --name $container_name busybox "echo" "Hello World"
wait

for i in `seq 0 1000`; do

    echo "Check #$i";
    output=$(docker logs "helloworldcontainer");
    if [ "$output" != "Hello World" ]; then
        echo "Container $i did not return the expected output. It returned $output instead"
    fi

done
```
I'll open an issue in docker project. Closing this one.
