### ISSUE TITLE
Container name does not match the one provided in createContainer

### ISSUE THREAD

**Issue by imavroukakis** [spotify/docker-client#1027]
BUG REPORT

## Description

When retrieving named containers via `.listContainers(ListContainersParam.allContainers())`, container names contain a `/` in front of them, e.g.

![image](https://user-images.githubusercontent.com/1764981/40491102-19f3ec2a-5f65-11e8-9b6f-2352af92dc84.png)

## How to reproduce

Create a container with a given name e.g.
`final ContainerCreation creation = dockerClient.createContainer(containerConfig, "mssql-base");`

invoke `.listContainers(ListContainersParam.allContainers())` and inspect the container name

## What do you expect

I expect the name to match the one provided in `createContainer`

## Software:
- `docker version`
```
Client:
 Version:      18.05.0-ce
 API version:  1.37
 Go version:   go1.9.5
 Git commit:   f150324
 Built:        Wed May  9 22:12:05 2018
 OS/Arch:      darwin/amd64
 Experimental: false
 Orchestrator: swarm

Server:
 Engine:
  Version:      18.05.0-ce
  API version:  1.37 (minimum version 1.12)
  Go version:   go1.10.1
  Git commit:   f150324
  Built:        Wed May  9 22:20:16 2018
  OS/Arch:      linux/amd64
  Experimental: true
```
- Spotify's docker-client version: 8.11.4

**Comment by johnflavin** [comment]
This is not a bug in docker-client. This is just what docker does. I can reproduce this behavior with the docker CLI.
```bash
[~]$ containerId=$(docker create --name foo busybox:latest) && docker inspect -f '{{ .Name }}' ${containerId}
/foo
```

The real lie is in `docker ps`, which strips off the `/` from all the names.

```
[~]$ docker ps -a | grep foo
614b8ccaf28b        busybox:latest       "sh"                     About a minute ago   Created                                       foo
```

**Comment by imavroukakis** [comment]
Hi @johnflavin thanks for the feedback. Following the principle of least surprise, I believe that it should be stripped out, what do you think? I would suspect there are other docker-isms that are being better taken care of in the client.

**Comment by johnflavin** [comment]
I totally understand that perspective. Especially in this case where the expected result is so intuitive—I just gave it a name, so I think I should get that name—yet different from the actual result. 

But at the same time, I think that kind of change, even though small, is outside the project's scope: to be a java client for docker's REST API. We try to hew as closely as possible to docker's API in everything. Names of the classes and methods, properties, structure of objects, etc. I can't think of any place where we inspect a value that gets returned from docker and change it before giving it back to you. (Not that I can guarantee it does not happen anywhere, but it isn't the norm.)

We bind the JSON we get back from docker into java objects and hand them over to you, and that's it. That way you can do whatever you need to with them. The downside is that you kinda have to be familiar with docker's API, including its little quirks like this container naming thing.

**Comment by imavroukakis** [comment]
If your aim is to mirror in code what Docker provides from its ReST API, then, reluctantly, I'd have to concur. It would certainly explain oddness like `String` used in ports. Personally, I think that certain things, like the aforementioned naming, and using String in port numbers is weirdness that could have been smoothed over by an API such as this 😄

**Comment by davidxia** [comment]
@imavroukakis Nonetheless, thanks for reporting.
