### ISSUE TITLE
attach of LogStream hangs even though Container has finished

### ISSUE THREAD

**Issue by jjohnstn** [spotify/docker-client#1035]
**Is this a BUG REPORT or FEATURE REQUEST?**:
BUG REPORT

## Description

We have code that attempts to output the result of a Container that runs a C compilation into the Eclipse console.  We use the following:

LogStream stream = ((DockerClient) token).logs(id,
					LogsParam.follow(), LogsParam.stdout(), LogsParam.stderr());
stream.attach(out, err);

where the out and err are PipedOutputStream instances that we hook up to PipedInputStreams for the callers to read and output to the Eclipse console.

We make the call for this in a separate thread.  In another thread, we have code that is doing a
waitContainer(id);

The waitContainer call uses a DockerClient copy that is separate from the one used to start the Container and create the LogStream

What is happening is that the thread that sees the waitContainer() complete successfully is waiting to see that the thread that attached the LogStream completes within 5 seconds later (to process all output).   I even tried 10 seconds and that didn't help.  It is stalling as the stream.attach() call does not return and we sit there and wait and wait.

What I ended having to do was to forcibly close the client copy I used to create the LogStream (token) and that stops it.  The issue is that I would expect the log stream to stop automatically when the container it is following has finished and this sometimes is the case.

[Add feature/bug description here]

## How to reproduce

Create 2 threads.  One that starts a Container that runs a gcc -v command and then attaches a LogStream with the parameters specified above.  The out and err streams can be any OutputStream.

In the other thread, wait for the Container to finish and then query whether the line after the LogStream attach comes back.

## What do you expect

I expect that shortly after the Container has completed and all output has been processed, the attach of the LogStream should finish (even by Exception).

## What happened instead

The attach hangs and the only way to get it stop is to close the DockerClient that was used to create the LogStream.  I had tried closing the out and err streams but that does not work.

## Software:

- `docker version`: 

Client:
 Version:         1.13.1
 API version:     1.26
 Package version: docker-1.13.1-54.git6c336e4.fc27.x86_64
 Go version:      go1.9.5
 Git commit:      19d432b-unsupported
 Built:           Mon May 21 10:58:04 2018
 OS/Arch:         linux/amd64

Server:
 Version:         1.13.1
 API version:     1.26 (minimum version 1.12)
 Package version: docker-1.13.1-54.git6c336e4.fc27.x86_64
 Go version:      go1.9.5
 Git commit:      19d432b-unsupported
 Built:           Mon May 21 10:58:04 2018
 OS/Arch:         linux/amd64
 Experimental:    false

- Spotify's docker-client version:  

com.spotify.docker.client_8.9.2.v20180207-1730.jar (from Orbit)

## Full backtrace

Thread [Thread-20] (Suspended)	
	owns: Object  (id=196)	
	owns: ChannelInputStream  (id=197)	
	owns: BufferedInputStream  (id=198)	
	Foreign.invokeN3O1(long, long, long, long, long, Object, int, int, int) line: not available [native method]	
	Invoker$LP64(Invoker).invokeN3(CallContext, long, long, long, long, int, Object, ObjectParameterStrategy, ObjectParameterInfo) line: 1061	
	Native$LibC$jnr$ffi$1.read(int, ByteBuffer, long) line: not available	
	Native.read(int, ByteBuffer) line: 101	
	Common.read(ByteBuffer) line: 49	
	UnixSocketChannel(AbstractNativeSocketChannel).read(ByteBuffer) line: 62	
	UnixSocketChannel.read(ByteBuffer) line: 250	
	ChannelInputStream.read(ReadableByteChannel, ByteBuffer, boolean) line: 59	
	ChannelInputStream.read(ByteBuffer) line: 109	
	ChannelInputStream.read(byte[], int, int) line: 103	
	SessionInputBufferImpl.streamRead(byte[], int, int) line: 137	
	SessionInputBufferImpl.fillBuffer() line: 153	
	SessionInputBufferImpl.readLine(CharArrayBuffer) line: 282	
	ChunkedInputStream.getChunkSize() line: 264	
	ChunkedInputStream.nextChunk() line: 225	
	ChunkedInputStream.read(byte[], int, int) line: 184	
	EofSensorInputStream.read(byte[], int, int) line: 137	
	BufferedInputStream.fill() line: 246	
	BufferedInputStream.read1(byte[], int, int) line: 286	
	BufferedInputStream.read(byte[], int, int) line: 345	
	ApacheConnector$HttpClientResponseInputStream(FilterInputStream).read(byte[], int, int) line: 133	
	EntityInputStream.read(byte[], int, int) line: 102	
	ReaderInterceptorExecutor$UnCloseableInputStream.read(byte[], int, int) line: 296	
	ByteStreams.read(InputStream, byte[], int, int) line: 859	
	LogReader.nextMessage() line: 49	
	DefaultLogStream.computeNext() line: 56	
	DefaultLogStream.computeNext() line: 35	
	DefaultLogStream(AbstractIterator<T>).tryToComputeNext() line: 145	
	DefaultLogStream(AbstractIterator<T>).hasNext() line: 140	
	DefaultLogStream.attach(OutputStream, OutputStream, boolean) line: 96	
	DefaultLogStream.attach(OutputStream, OutputStream) line: 84	
	DockerConnection.attachLog(Closeable, String, OutputStream, OutputStream) line: 2120	
	ContainerCommandProcess.lambda$0(IDockerConnection, String, OutputStream, IDockerContainerInfo) line: 133	
	1712157917.run() line: not available	
	Thread.run() line: 748

**Comment by davidxia** [comment]
@jjohnstn thanks for reporting. Do you have a working example of code that can reproduce?

**Comment by jjohnstn** [comment]
I'd have to work to put something simple together because all of the code is in Eclipse Linux Tools and CDT.  If you want to duplicate it in Eclipse, first download the Eclipse Photon RC3 CPP EPP:  

http://www.eclipse.org/downloads/packages/eclipse-ide-cc-developers/photonrc3

Set up an Image with make, gcc installed.  Start up docker daemon and then start up the CPP EPP.  If you go to Docker Tooling Perspective in Eclipse, you can verify that Docker Tooling has found your daemon, otherwise, add a connection to it.

From C/C++ Perspective, go to New->C/C++ Project->Makefile project and choose a name.

Once the project is created,  go to the Project Explorer View and select project.  On launch bar above, pull down the target box which will say "Local" and choose the image you created above.  Hit the Hammer icon which will build the project in a Container.

If you debug on your side, you should see a Container wait complete but the attachLog doesn't return.  The Eclipse code will end up closing the client used to do the attachLog after 5 seconds elapses in sleeps.
