### ISSUE TITLE
Add support for `credHelpers ` in new docker versions

### ISSUE THREAD

**Issue by yuelipku** [spotify/docker-client#1037]
Hi, I am using the `dockerfile-maven` together with `amazon-ecr-credential-helper`
[https://github.com/awslabs/amazon-ecr-credential-helper](url)
`amazon-ecr-credential-helper` support `credHelpers`. 
`With Docker 1.13.0 or greater, you can configure Docker to use different credential helpers for different registries.`

I am wondering whether docker-client could support `credHelpers`?

**Comment by yuelipku** [comment]
Hi, I tried. It does not have support on this..

**Comment by johnflavin** [comment]
From docker's [docker login](https://docs.docker.com/engine/reference/commandline/login/#credential-helper-protocol) docs:
> Credential helpers are specified in a similar way to credsStore, but allow for multiple helpers to be configured at a time. Keys specify the registry domain, and values specify the suffix of the program to use (i.e. everything after docker-credential-). For example:
> ```
> {
>  "credHelpers": {
>    "registry.example.com": "registryhelper",
>    "awesomereg.example.org": "hip-star",
>    "unicorn.example.io": "vcbait"
>  }
>}
>```

I don't think we do support `credHelpers` right now. At least, I can't find any part of the `docker-client` code that reads `credHelpers` from the `config.json`.

**Comment by yuelipku** [comment]
Yes, it will help a lot if you could consider support `creHelper`, in some situations, we have registries from different service providers.
