### ISSUE TITLE
The Volume.status has an incorrect generic type

### ISSUE THREAD

**Issue by man4j** [spotify/docker-client#1039]
```
@AutoValue
@JsonAutoDetect(fieldVisibility = ANY, getterVisibility = NONE, setterVisibility = NONE)
public abstract class Volume {
...
  @Nullable
  @JsonProperty("Status")
  public abstract ImmutableMap<String, String> status();
...
}
```
But some volume drivers returns status as complex structure not as simple String (f.e. vsphere volume driver).

Please change map from ImmutableMap<String, **String**> to ImmutableMap<String, **Object**>

Also:

```
  public abstract ImmutableMap<String, String> driverOpts();
  public abstract ImmutableMap<String, String> options();
```

I think that driverOpts and options have the same problem.

Thanks!

**Comment by johnflavin** [comment]
Can you give an example of the kind of status that gets returned that isn't just a String? Or a link to the docker API docs, if there are examples there.
