### ISSUE TITLE
DOCKER_HOST not work?

### ISSUE THREAD

**Issue by pickmonster** [spotify/docker-client#1049]
`o.a.http.impl.execchain.RetryExec - I/O exception (java.io.IOException) caught when processing request to {}->unix://localhost:80: No such file or directory`
`o.a.http.impl.execchain.RetryExec - Retrying request to {}->unix://localhost:80`
`com.spotify.docker.client.DockerException: java.util.concurrent.ExecutionException: javax.ws.rs.ProcessingException: java.io.IOException: No such file or directory`

I had set DOCKER_HOST ,but it not work. And i had try "docker ps". Command also work.

My project running in Rancher. So I tried to set environment variables in Rancher. Also give me same error. There is some config I set wrong?

Code:
`final DockerClient docker = DefaultDockerClient.fromEnv().build();`
`final DockerClient docker = new DefaultDockerClient("unix:///var/run/docker.sock");`
Neither way can work.

**Comment by geraldglennon** [comment]
@pickmonster I have the same problem. For one you need to set the environment variable. I'm doing this inside a docker container and the application is not picking this up. So im currenlty looking into what I'm doing wrong.

But what I also found today is a bug in the latest version that if the DOCKER_HOST is not found then it tries to find this from the os name. but the AND statement is wrong and it will always default to unix://localhost:80 and not unix:///var/run/docker.soc. 

in DockerHost class -> defaultDockerEndpoint()

the return line is wrong !os.equalsIgnoreCase("linux") && !os.contains("mac") ? "localhost:" + defaultPort() : "unix:///var/run/docker.sock";. It will never find the correct host

**Comment by geraldglennon** [comment]
Actually I take that back i was using 8.12.0 but its fixed in 8.13.0

**Comment by geraldglennon** [comment]
I managed to get this working. There is an issue with systemDelegate that it cannot find any environment variables inside docker container. (Redhat Atomic). I've create my own docker client and removed systemDelegate. I suggest this be investigated as a bug.
