### ISSUE TITLE
i cant write to stdin in docker php api

### ISSUE THREAD

**Issue by mohammadreza-soft74** [spotify/docker-client#1067]
hi .
i cant write to stdin when i run my php app with execstart  which need input .

my docker client and docker Engine version : 
Client:
 Version:           18.06.0-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        0ffa825
 Built:             Wed Jul 18 19:09:54 2018
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.0-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       0ffa825
  Built:            Wed Jul 18 19:07:56 2018
  OS/Arch:          linux/amd64
  Experimental:     false

Thanks in advance.

**Comment by mattnworb** [comment]
Are you sure this is the right repo to report your issue? This library is for use in Java code (or on the JVM, more specifically) to communicate with the docker daemon. Are you somehow using it from PHP code?
