### ISSUE TITLE
support nvidia runtime

### ISSUE THREAD

**Issue by kyr7** [spotify/docker-client#1095]
## Support nvidia runtime

Hi. I want to be able to use nvidia runtime like this:
'docker run --runtime=nvidia nvidia/cuda nvidia-smi'

Would you like to add this feature valuable for machine learning? Or maybe would you hint how I could add it to make a pull request?

**Comment by mattnworb** [comment]
this should already be possible, check out #1060

**Comment by kyr7** [comment]
Thank you for pointing this.
