### ISSUE TITLE
Proxy parameter forwarding for build containers

### ISSUE THREAD

**Issue by KineticCookie** [spotify/docker-client#1105]
**Is this a BUG REPORT or FEATURE REQUEST?**: Feature request

## Description

Pass proxy parameters from `~/.docker/config.json` to build containers as buildargs.

## How to reproduce

Execute `DefaultDockerClient.build` method having proxy setup in `~/.docker/config.json`.
All requests from within build container are made directly, avoiding proxy.

## What do you expect

I think it's a standard behavior to add corresponding `buildargs` from values in `~/.docker/config.json`.
Docker CLI has this behavior by default: https://docs.docker.com/network/proxy/#configure-the-docker-client . Despite this, `docker-client`, parses config file only to get auth parameters.
I suggest to expose the new version of `DockerClient.build` method, which will fully embrace the docker config and properly set parameters.

## What happened instead

Proxy setup from `~/.docker/config.json` is not parsed, and ignored during image build.

## Software:

- `docker version`: Docker version 18.06.1-ce, build e68fc7a
- Spotify's docker-client version: 8.12.0

## Full backtrace

N/A

**Comment by KineticCookie** [comment]
So, if it's ok for you guys, I could make a PR with the implementation.

**Comment by mattnworb** [comment]
@KineticCookie all PRs are welcome!

**Comment by cwienands1** [comment]
We need exactly this feature, setting the proxy configuration via config.json. @KineticCookie, did you ever make any progress in that direction?

Reason why config.json: docker-client is used by the Maven plugin dockerfile-maven. The only way right now (that I know of) to inject proxy settings into containers during a Maven build step is via the plugin/configuration/buildArgs collection in the pom.xml. Yes, these values can be overridden when running Maven from the command line but I argue that proxy settings have no business in the pom to begin with. Proxy settings are user- and environment-specific, and it doesn't make sense that I should have to add these values to all my projects (or to a parent pom for that matter). 

As a concrete example: We have a large codebase of around 100 Spring Boot services. In our existing (individual) dev env and CI/CD env, no proxy settings are necessary. The network environment will change and proxy settings will be necessary. Again, I should not have to modify my code base only to configure an environmental aspect.

**Comment by rmueller83** [comment]
We also need this. It seems like @KineticCookie started something on a branch: https://github.com/KineticCookie/docker-client/commits/proxy-build-params

**Comment by rmueller83** [comment]
For reference, here is an implementation for a different Maven plugin which reads the Proxy settings from the Docker configuration file: https://github.com/fabric8io/docker-maven-plugin/pull/1187/files

**Comment by KineticCookie** [comment]
Hi!
I noticed that the maintainers mentioned that they won't accept new features in README.MD

>At this point, we're not developing or accepting new features or even fixing non-critical bugs. Feel free to fork this repo though.

So I decided to implement build proxies in my client code (by passing build-args) rather than fixing it in the library itself.
