### ISSUE TITLE
event support

### ISSUE THREAD

**Issue by mainiak** [spotify/docker-client#114]
Hi.

I have question regarding support for events inside docker host.

Is there or will be any support for docker events?
https://docs.docker.com/reference/api/docker_remote_api_v1.16/#monitor-dockers-events

I was looking into DockerClient API but I didn't seen any.

Thank you in advance for your answer.

**Comment by mainiak** [comment]
@tedyoung - could you, please, paste here link to your implementation, so I can look into it?

**Comment by tedyoung** [comment]
Oops, just realized that I totally dropped the ball on this. I'll sanitize my code and link to it, and then see what a PR might look like.

**Comment by mattnworb** [comment]
done in #358
