### ISSUE TITLE
Add HostConfig.Init support when creating a container

### ISSUE THREAD

**Issue by arminbalalaie** [spotify/docker-client#1159]
Based on the docker API changelog, from version 1.25, Docker added ``HostConfig.Init`` field to ``POST /containers/create`` to run an init inside the container that forwards signals and reaps processes. Right now, it is not possible to configure this field through the HostConfig.Builder class. It'd be great to add support for this.

**Comment by arminbalalaie** [comment]
Poke

**Comment by arminbalalaie** [comment]
Poke

**Comment by dmandalidis** [comment]
Hi @arminbalalaie ,

Since this project went on mature status, please re-open this issue (if it still stands) to https://github.com/dmandalidis/docker-client. Thanks
