### ISSUE TITLE
Most popular and well-supported fork?

### ISSUE THREAD

**Issue by tony--** [spotify/docker-client#1166]
The README has been updated with the following statement:
> Spotify no longer uses recent versions of this project internally. The version of docker-client we're using is whatever helios has in its pom.xml. At this point, we're not developing or accepting new features or even fixing non-critical bugs. Feel free to fork this repo though.

I'm wondering how others in the user community are adjusting to this?  Is there an actively maintained fork that others are moving to?

**Comment by dmandalidis** [comment]
hi @tony-- 

I 'm forking this and planning to redistribute it, I believe I will be ready within a month

**Comment by dmandalidis** [comment]
hi again @tony-- 

Everything is set at https://github.com/dmandalidis/docker-client; simply changing the group id and the version will do the trick

**Comment by tony--** [comment]
Thanks for the update @dmandalidis, will check it out!

**Comment by ieggel** [comment]
@dmandalidis 

Great news. Thanks. I will have a look at your project!

**Comment by tony--** [comment]
I have switched to https://github.com/dmandalidis/docker-client.  Thanks for the effort @dmandalidis!
