### ISSUE TITLE
Docker client fails to fetch image load balanced docker host

### ISSUE THREAD

**Issue by mohapsub** [spotify/docker-client#1173]
Hi There!! I am using sportify docker client 8.16.0.
I have four remote docker hosts(4 pods in k8s Deployment) and there is load balancer service(k8s Service) configured on those four pods. When I connect to remote docker using the service from my java client app using sportify docker-client I face issues.
Image creation is fine but while pushing to registry its not able to find image. Same code works fine with single pod. 
I suspect image is getting created in one pod but while pushing image its trying to find that using other pod and fails to find image. This is just a guess. Please help.

**Is this a BUG REPORT or FEATURE REQUEST?**:

## Description

[Add feature/bug description here]

## How to reproduce

[Add steps on how to reproduce this issue]

## What do you expect

[Describe what do you expect to happen]

## What happened instead

[Describe the actual results]

## Software:

- `docker version`: [Add the output of `docker version` here, both client and server] 18 ce +
- Spotify's docker-client version: [Add docker-client version here] 8.16.0

## Full backtrace

```text
[Paste full backtrace here]
```

**Comment by mattnworb** [comment]
I'm not sure I understand. The docker daemon is running as multiple pods in a Kubernetes cluster - but where is it that you are trying to push the image to? You push an image to a registry, not typically to a docker daemon. 

If you are running a registry in a Kubernetes cluster, how to set that up would be beyond the scope of this library (and I don't think we can help you out).

**Comment by mohapsub** [comment]
I am running a dind(docker in docker) image in k8s. Four pods of dind in a k8s Deployment and I have a Service configured for this deployment. I am trying to access remote docker using this service endpoint by sportify client

**Comment by mohapsub** [comment]
I use one pod for my Deployment then it works fine. If I use four pods, then image is getting created in one of the pod but while pushing image to registry/ or image inspect it fails. Cant find image .

**Comment by mattnworb** [comment]
You probably want to have some way to share the state/storage between those pods. I'd suggest taking a look at other tools that allow you to do Docker builds in k8s to see how they deploy things:

- https://github.com/GoogleContainerTools/kaniko
- https://github.com/uber/makisu

**Comment by mohapsub** [comment]
is there a method available that can create and push image as one unit of task?
Now its working as two remote calls, build and push.

**Comment by mohapsub** [comment]
there should be method 'buildAndpush' or so that should create image and push to registry with one call to remote docker. This should work for me. Single docker instance cant handle the load so multiple pod or docker instances served by a load balancer is a very common solution. This is very basic need and will be very helpful.

**Comment by mattnworb** [comment]
There is not a single method for `buildAndPush` in this client because there is not a single method in the Docker Remote API for building and pushing in a single operation: https://docs.docker.com/engine/api/v1.40/#operation/ImageBuild
