### ISSUE TITLE
Unable to see the output of a container that is running a docker image

### ISSUE THREAD

**Issue by hasans3** [spotify/docker-client#1174]
## Description

I am able to run the spotify/docker-java api and run containers with the image that I want to run, however, I cannot see the output of that container inside my Eclipse environment. How do I do that? 

Also, I can only pull images from docker hub. However, I cannot pull/run images that are on my local machine. How do I run the local images.

**Comment by harrismirza** [comment]
I am having the same issue in Intellij, it seems to work with the same image for commands with a short output, but when the output is longer, it shows nothing.

Strangely, if I restart the created container using the docker cmd the output is shown.
