### ISSUE TITLE
very very slow with remote docker

### ISSUE THREAD

**Issue by mohapsub** [spotify/docker-client#1175]
I use sportify 8.16.0 java docker client to build and push docker image using a remote docker instance. Sometimes for the same build it runs quick(in a min) but most of times it takes hours to build same image from same code base. Its very inconsistent in terms of speed.

**Is this a BUG REPORT or FEATURE REQUEST?**:

## Description

[Add feature/bug description here]

## How to reproduce

[Add steps on how to reproduce this issue]

## What do you expect
Faster docker build
[Describe what do you expect to happen]

## What happened instead
Sometimes it run for hours for docker build
[Describe the actual results]

## Software:

- `docker version`: [Add the output of `docker version` here, both client and server]
- Spotify's docker-client version: [Add docker-client version here]
8.16.0
## Full backtrace

```text
[Paste full backtrace here]
```

**Comment by mattnworb** [comment]
Have you tried passing [a `ProgressHandler` to the build method](https://github.com/spotify/docker-client/blob/14c955c0524233639fe76a35edda3d620037a525/src/main/java/com/spotify/docker/client/DockerClient.java#L558) so you can see progress messages, to know which part is "slow"?

**Comment by mohapsub** [comment]
its not very consistent, sometimes it works fine. most of the times each of line execution of docker file is very slow. Even a simple copy a file(less than 1 kb) takes more than 5 mins. I am not very familiar with progress handler. Will this help in improving perf?
