### ISSUE TITLE
Can't get current logs from running container and return immediately

### ISSUE THREAD

**Issue by Diors-Po** [spotify/docker-client#1197]
**Is this a BUG REPORT or FEATURE REQUEST?**:
BUG REPORT

## Description

I want to get logs from running containers, so call "attachContainer()" to get a LogStream,  and use it to return a log-String. 
However,  LogStream.readFully() will hang until the container stop.
## How to reproduce

```java
       dockerClient.startContainer(container.id());
        final String logs;
        try (LogStream stream = dockerClient.attachContainer(container.id(),
                DockerClient.AttachParameter.LOGS, DockerClient.AttachParameter.STDOUT,
                DockerClient.AttachParameter.STDERR, DockerClient.AttachParameter.STREAM)) {

                System.out.println("ready to get logs......");
                logs = stream.readFully();
                System.out.println("over...");
                System.out.println(logs);
        }
```

## What do you expect

I want to get the current logs from running container.

## What happened instead

The logs will return only when container stopped.

## Software:

- `docker version`: 
Version:           19.03.2
 API version:       1.40
 Go version:        go1.12.8
 Git commit:        6a30dfc
 Built:             Thu Aug 29 05:26:49 2019
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.2
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.8
  Git commit:       6a30dfc
  Built:            Thu Aug 29 05:32:21 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.6
  GitCommit:        894b81a4b802e4eb2a91d1ce216b8817763c29fb
 runc:
  Version:          1.0.0-rc8
  GitCommit:        425e105d5a03fabd737a126ad93d62a9eeede87f
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

- Spotify's docker-client version: 
8.16.0

## Full backtrace

```text
```

**Comment by mattnworb** [comment]
I think you should only pass `DockerClient.AttachParameter.STREAM` if you intend to stream logs from the container until it exits:

> `stream`: Stream attached streams from the time the request was made onwards.

https://docs.docker.com/engine/api/v1.40/#operation/ContainerAttach
