### ISSUE TITLE
Disable log printing

### ISSUE THREAD

**Issue by yanivoren** [spotify/docker-client#121]
When executing build from command line log messages of ProgressMessage display, how can I eliminate them?

```
...
ProgressMessage{id=null, status=null, stream=ALTER TABLE
, error=null, progress=null, progressDetail=null}
ProgressMessage{id=null, status=null, stream= ---> a1f12f7a0cbb
, error=null, progress=null, progressDetail=null}
ProgressMessage{id=null, status=null, stream=Removing intermediate container 44d3a69dc637
, error=null, progress=null, progressDetail=null}
...
```

notes:
Run gradle task from command line which executes the build.
Using custom progresshandler which doesn't log or print to console.
Log is not displayed when running from eclipse.
TIA

**Comment by davidxia** [comment]
@yanivoren I haven't used this with gradle. Can you supply the gradle file and build commands so I can try to reproduce?

**Comment by yanivoren** [comment]
build.gradle:

`apply plugin: 'java'`
`apply plugin: 'eclipse'`

`sourceCompatibility = 1.5`
`version = '1.0'`
`jar {`
    `manifest {`
        `attributes 'Implementation-Title': 'Gradle Quickstart', 'Implementation-Version': version`
    `}`
`}`

`repositories {`
    `mavenCentral()`
`}`

`dependencies {`
    `compile group: 'commons-collections', name: 'commons-collections', version: '3.2'`
    `compile "com.spotify:docker-client:2.7.5"`
    
    `testCompile group: 'junit', name: 'junit', version: '4.+'`
`}`

`task runMyTask(dependsOn: 'classes',type:JavaExec) {`
    `main = "org.gradle.MainRunner"`
    `classpath = sourceSets.test.runtimeClasspath`
    `description = 'Resetting the dockers data volume container for testing'`
 `}`

`test {`
    `systemProperties 'property': 'value'`
`}`

`uploadArchives {`
    `repositories {`
       `flatDir {`
           `dirs 'repos'`
       `}`
    `}`
`}`


To execute this :

1. create class MainRunner in package org.gradle which contains main, the main will use docker to build some image.
2. run gradle runMyTask from command line.

notes:
Using eclipse -> create gradle project (gradle ide plugin) can speed the reproduce process.

**Comment by yanivoren** [comment]
@davidxia were you able to reproduce?

**Comment by davidxia** [comment]
@yanivoren I spent a bit of time on this a while ago but couldn't. I guess I'm not familiar enough with gradle. I'm also using IntelliJ. I probably don't have time to follow up on this for now :(

**Comment by yanivoren** [comment]
OK

**Comment by davidxia** [comment]
Is this still an issue or can I close it?

**Comment by tdomzal** [comment]
Message is logged here:
https://github.com/spotify/docker-client/blob/master/src/main/java/com/spotify/docker/client/LoggingPullHandler.java#L48

So setting log level to WARN on category 

`com.spotify.docker.client.LoggingPullHandler`

should suppress progress message.
How to do this depends of logging framework you are using.
