### ISSUE TITLE
Using Netty instead of Jersey Client

### ISSUE THREAD

**Issue by diptanu** [spotify/docker-client#122]
Are you guys considering using Netty instead of Jersey Client? We have a docker client built on top of RxNetty [1], but I am looking to use a client which has more community behind it to keep up with every new docker api changes etc :) So I am considering to use this client. We use docker client from a Mesos executor which needs to be very light weight and not consume a lot of memory or spawn a lot of threads etc. 

[1] https://github.com/ReactiveX/RxNetty

**Comment by davidxia** [comment]
@diptanu Hm, I don't think there are any plans on using Netty right now. I wasn't part of the discussion to use Jersey over Netty so maybe @rohansingh can shed light on that. But I do know we support unix sockets.

Have you tried using our docker-client and found it doesn't work?

**Comment by diptanu** [comment]
@davidxia Thanks, I have just started your docker-client, haven't deployed it in any environment yet. I will let you guys know how things go. One question, are you guys using this client for production workload at Spotify?

**Comment by davidxia** [comment]
@diptanu yes we are using docker-client as a dependency of github.com/spotify/helios as of early July 2014 with a money-generating service. So we have a lot of confidence in it.

**Comment by diptanu** [comment]
@davidxia That's great! We are building something similar, targeted for public clouds and managing clusters in multiple geographies.

**Comment by davidxia** [comment]
@diptanu Yea feel free to ask us any questions. Can i close this issue for now?

**Comment by rohansingh** [comment]
You might also be interested in #107.

**Comment by diptanu** [comment]
@davidxia Yes, please close the issue.
