### ISSUE TITLE
Can't find a way to retrieve Docker Host from DockerClient

### ISSUE THREAD

**Issue by mbaechler** [spotify/docker-client#138]
When using DefaultDockerClient.fromEnv (which is a great feature), I can't find any way to retrieve the computed Host IP from DockerClient object.
It's unfortunate because it's computed in fromEnv method.
Is there something i'm missing ?
If not, would you accept a PR for this ?

**Comment by davidxia** [comment]
Merged in https://github.com/spotify/docker-client/pull/139
