### ISSUE TITLE
Unpack Docker Image Enhancement

### ISSUE THREAD

**Issue by cholcombe973** [spotify/docker-client#145]
I wrote some code to take a docker saved tar file and unpack it into the docker directories.  This allows an saved image to be unpacked without a running docker daemon.  If interested I'll submit a pull request.  Otherwise I might just throw it up on my github for whomever that is interested.

**Comment by rohansingh** [comment]
@cholcombe973 That sounds pretty cool but I don't think it fits within the goals of this project since it isn't really a "docker-client" thing. I'd love to see it as a separate project though.

**Comment by cholcombe973** [comment]
Sounds good.  Thought I'd ask before going to the trouble of trying to integrate the code :)
