### ISSUE TITLE
Mounted volumes

### ISSUE THREAD

**Issue by vanmellebenjamin** [spotify/docker-client#147]
Good evening, 

I use the client to start docker containers on my local machine.
All is fine excepted the volume mount.

I tried since this morning to get the same result as docker cmd: -v $HOME/.roq:/lib/RoQ/roq-config
but I didn't found the good way to do it.

Can you introduce me to the way to mount volume with the client ?

Thank you,
Benjamin

**Comment by davidxia** [comment]
Hi @vanmellebenjamin 

The way I see it being used in github.com/spotify/helios is 

    final ImmutableList.Builder<String> binds = ImmutableList.builder();
    binds.add("/path/to/source/in/host:/path/to/target/in/container");

    final HostConfig.Builder builder = HostConfig.builder()
        .binds(binds)
        .portBindings(portBindings())
        .dns(dns);

    final HostConfig hostConfig = config.hostConfig();
    docker.startContainer(container.id(), hostConfig);

But I also see `testVolumesFrom()` [here](https://github.com/spotify/docker-client/blob/fc7c1ceba153d8355940a43fe46aa1533472f180/src/test/java/com/spotify/docker/client/DefaultDockerClientTest.java#L1066).

@rohansingh I've successfully mounted volumes the first way. This second way as shown in the test calls the [create container docker daemon endpoint](https://docs.docker.com/v1.3/reference/api/docker_remote_api_v1.3/#create-a-container) with a "volumes" parameter. How's that different than the first way above which calls the [start container endpoint](https://docs.docker.com/v1.3/reference/api/docker_remote_api_v1.3/#start-a-container) with "binds"?

**Comment by rohansingh** [comment]
Using `volumes()` when creating a container creates a volume in the container, which is not bound to anything. Specifying `binds()` in the `HostConfig` actually binds a directory from the host.

**Comment by vanmellebenjamin** [comment]
Thank you very much !
That was helpful.
