### ISSUE TITLE
Question on keeping a docker up and running

### ISSUE THREAD

**Issue by cholcombe973** [spotify/docker-client#148]
I think I'm missing something here.  
        final HostConfig hostConfig = HostConfig.builder()
                .networkMode("host")
                .binds("/etc:/etc")
                .privileged(Boolean.TRUE)
                .build();

   final ContainerConfig config = ContainerConfig.builder()
                    .image("ubuntu:latest")
                    .cmd("/bin/bash")
                    .hostname("mon-1")
                    .build();
            final ContainerCreation creation = dockerClient.createContainer(config);
            final String id = creation.id();
            dockerClient.startContainer(id, hostConfig);
When I run a container with this code it seems to start up and then exit immediately.  Do you know how to set interactive mode or detach?

**Comment by cholcombe973** [comment]
I'm basically trying to recreate this cmd line:
docker run -d=true -i --privileged=true --net=host -v /etc:/etc -t ubuntu:latest /bin/bash

With that command I can kick it off and the container will keep running in the background.

**Comment by cholcombe973** [comment]
I added 
                    .attachStderr(Boolean.TRUE)
                    .attachStdin(Boolean.TRUE)
                    .attachStderr(Boolean.TRUE)
                    .tty(Boolean.TRUE)
to my container config. Checking if that fixes it.

**Comment by cholcombe973** [comment]
That worked!

**Comment by rohansingh** [comment]
@cholcombe973 Sorry for the delayed response. But yup, that's basically what the `--interactive` in `docker run` does. If there's no `stdin` attached, bash will just exit.

**Comment by crummy** [comment]
FYI to others, it seems that only `.tty(Boolean.TRUE)` is necessary to keep the container running.
