### ISSUE TITLE
Ports details as in Docker ps

### ISSUE THREAD

**Issue by ipedrazas** [spotify/docker-client#150]
I'm writing an Eclipse plugin for Docker using this library but I had to modify slightly the Container class to provide the port info the way the `docker ps` does:

`6379/tcp` or `1337/tcp, 7474/tcp` or  `0.0.0.0:5432->5432/tcp`

Do you think you would be interested on merging the change? is a public method `Container.portsAsString()` that returns a String with the ports info.

I haven't found the way of pulling all the ports data out of your Container class, hence this change :smile: 

![5cbd1afe557f593710139975ca3b7280](https://cloud.githubusercontent.com/assets/32796/6855325/0a505588-d3ef-11e4-9fd4-d3c7a2a68476.png)

**Comment by rohansingh** [comment]
Are you sure that this isn't what you are looking for:
https://github.com/spotify/docker-client/pull/41#issuecomment-58225659

**Comment by ipedrazas** [comment]
correct me if I'm wrong but when you fetch all the running containers `listContainers()` you call the API once and get all the data (port info included). But with the method you suggest, you will make an API call for each running container you have.

I agree that `client.inspectContainer(containerId).networkSettings().ports();` provides the port info, but `Container` has that infor as well, I don't see what's the problem on exposing the port info from `Container`.

It's clear that people does not understand that you cannot access the data even it's there.

**Comment by rohansingh** [comment]
Ah, I see what you mean. Great point. I'm open to a PR on this.

**Comment by ipedrazas** [comment]
\o/

**Comment by xcoulon** [comment]
@ipedrazas since docker-client version 2.7.16, the Container class has an inner class named PortMapping that provides you with the public IP, public port, private IP and type (see https://github.com/spotify/docker-client/pull/133). 
Then, in your Eclipse table view, you just need to concatenate these attributes using a custom ColumnLabelProvider.
HTH.

**Comment by davidxia** [comment]
@ipedrazas https://github.com/spotify/docker-client/pull/133 has been merged. Does that work for you? if so can we close this issue?
