### ISSUE TITLE
Support loading image tarball

### ISSUE THREAD

**Issue by stephan-huttenhuis** [spotify/docker-client#154]
Hi guys,

It would be great if it were possible to load an image tarball through the DockerClient.

https://docs.docker.com/reference/api/docker_remote_api_v1.17/#load-a-tarball-with-a-set-of-images-and-tags-into-docker

Thanks

**Comment by davidxia** [comment]
Finally closed by https://github.com/spotify/docker-client/pull/301

**Comment by stephan-huttenhuis** [comment]
The implemented solution does not work for me because an images/create is done instead of an image/load. The image ends up with only a single layer.

**Comment by johnflavin** [comment]
+1 to reopen. #301 implemented `/images/create`, not `/images/load`.

**Comment by davidxia** [comment]
Fixed by #494
