### ISSUE TITLE
X-Registry-Auth deprecated

### ISSUE THREAD

**Issue by kevtaylor** [spotify/docker-client#157]
As far as I can make out, the api version being called from the spotify client is V1.12

1).
In the docker server.go software the X-Registry-Auth appears to only be used prior to V1.9
as: 

// This block can be removed when API versions prior to 1.9 are deprecated.
// Both headers will be parsed and sent along to the daemon, but if a non-empty
// ConfigFile is present, any value provided as an AuthConfig directly will
// be overridden. See BuildFile::CmdFrom for details.
if version.LessThan("1.9") && authEncoded != "" {

it has been superseded by X-Registry-Config

2).
Also, the structure of X-Registry-Auth appears to be this:

Username      string `json:"username,omitempty"`
Password      string `json:"password,omitempty"`
Auth          string `json:"auth"`
Email         string `json:"email"`
ServerAddress string `json:"serveraddress,omitempty"`

There doesn't appear to be a way of adding the "auth" element to the spotify client

3).
The /build element of the rest api requires authentication on a private repo 
I tried adding the header .header("X-Registry-Auth", authHeader(authConfig)) to the build method
but I cannot get this build to work without falling over with a 403 error - the credentials don't seem to be passed correctly

Can anyone shed any light on these?

**Comment by davidxia** [comment]
@kevtaylor 

1. The version in the URL this docker-client makes requests to is "v1.12" but the docker daemon just ignores this. We've been testing and building docker-client against docker 1.3 with api version 1.15 for several months now. Soon we'll make it explicit in the docs and code what version we've been testing on.

2. I think the value of X-Registry-Auth should be 

```
{"Username": "foo", "Password": "pass", "Email": "foo@bar.com"[, "ServerAddress": "example.com"]}
```

3 Where are you trying to add `.header("X-Registry-Auth", authHeader(authConfig))`? Isn't this already in  `DefaultDockerClient.push()` and `pull()`?

**Comment by kevtaylor** [comment]
The problem we are facing is actually build Docker images through the API (indirectly through the maven plugin). So build() is the method being called here. This explicitly requires X-Registry-Config in versions after 1.8 (I have actually added X-Registry-Auth) to this method and changed the API version to 1.8 which then made the code work. 
When the build api is called it will attempt to get https://registry/v1/someapp/images and over SSL this requires authentication which is missing from the spotify docker client code

**Comment by kevtaylor** [comment]
@rohansingh Thanks for merging. This issue is resolved by the PR
