### ISSUE TITLE
Specify restart policy when starting container

### ISSUE THREAD

**Issue by paulrutter** [spotify/docker-client#168]
I cannot find the possibility to specify a restart policy (https://docs.docker.com/reference/commandline/cli/#restart) when starting a container.

Is this missing or am I looking in the wrong place?
If it's missing, can it be added to "HostConfig" -> "restartPolicy"?

It's a config setting in the REST API, https://docs.docker.com/reference/api/docker_remote_api_v1.18/, see "Create a container".

Thanks in advance.

**Comment by davidxia** [comment]
@paulrutter [Here's the docs on `docker run --restart`][1]. Here at Spotify we use [helios][2] to handle container restarts so we didn't add this to docker-client. We're open to PRs though :). Let me know if you need help getting started.

  [1]: https://docs.docker.com/reference/commandline/cli/#restart-policies
  [2]: https://github.com/spotify/helios

**Comment by davidxia** [comment]
@paulrutter Do you still have this issue or can I close this?

**Comment by paulrutter** [comment]
@davidxia Although the issue is still valid in my opinion, i've worked around this issue by letting my app stack restart the container when needed.

**Comment by davidxia** [comment]
Ah OK. I'll leave this issue open in case anyone feels like contributing
this.

On Monday, August 3, 2015, paulrutter <notifications@github.com> wrote:

> @davidxia <https://github.com/davidxia> Although the issue is still valid
> in my opinion, i've worked around this issue by letting my app stack
> restart the container when needed.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/spotify/docker-client/issues/168#issuecomment-127146971>
> .
>


-- 
David Xia
Software Engineer
dxia@spotify.com

**Comment by sayarg** [comment]
hey folks, we have a use case for the restart policy and happy to look into it. as a first step i need to be able to build and test the project on windows. i've opened this issue for this here: https://github.com/spotify/docker-client/issues/327

if there are no objections, i'll proceed with making a proposal.

**Comment by paulrutter** [comment]
Sounds good :)

**Comment by sayarg** [comment]
here's my change to make it build and test for me on windows:

https://github.com/spotify/docker-client/pull/331

**Comment by davidxia** [comment]
Just merged https://github.com/spotify/docker-client/pull/332
