### ISSUE TITLE
how to get the exited containers for java

### ISSUE THREAD

**Issue by qq1514730142** [spotify/docker-client#177]
like this ?    docker.listContainers(ListContainersParam.create("filters", "status[exited]"));
but is error,waiting for help,thinks

**Comment by zanella** [comment]
for (Container c : docker.listContainers( DockerClient.ListContainersParam.create("all", "1") )) {
    System.out.println("(DBG) container: " + c.status());
}

**Comment by zanella** [comment]
docker.listContainers(
                    DockerClient.ListContainersParam.allContainers(),
                    DockerClient.ListContainersParam.create("filters", URLEncoder.encode("{\"status\":[\"exited\"]}", "UTF-8"))
            ).stream()
                .forEach(c -> System.out.println("(DBG) status: " + c.status()));

**Comment by qq1514730142** [comment]
Think you very much!
