### ISSUE TITLE
Do the docker-client suport Paging query?

### ISSUE THREAD

**Issue by qq1514730142** [spotify/docker-client#182]
Do the docker-client suport Paging query? how to do that? wating for help? 
How to use "public List listImages(ListImagesParam... params) " to do Paging query? Thanks in advance!

**Comment by rohansingh** [comment]
Nope, this isn't currently supported.

**Comment by rohansingh** [comment]
As far as I can tell, the Docker API doesn't support this either, so it's not possible to implement. Closing for now.
