### ISSUE TITLE
Support for Docker Remote API v1.18

### ISSUE THREAD

**Issue by diptanu** [spotify/docker-client#189]
Hi,

With Docker 1.6.2 the JSON payload for creating container has changed substantially. I found that the cpu.shares aren't being set propetly anymore while using the latest release of this library with Docker 1.6. Because now the cpu.shares has to be set while creating the container under the HostConfig property in the json payload.

Are you guys planning to support the new API?

**Comment by diptanu** [comment]
@rohansingh @davidxia We are using this at Netflix, and we would have to use the current version and keep up with docker releases since we are going to be using the remote driver functionality so that we can make custom network drivers etc. Do you guys intend to keep up with the future Docker releases or do you need to be on some particular version of Docker for your needs at Spotify??

I have forked the client and developing support for Labels, Mac Address, and the newer API for creating containers. Would you be open to accepting PRs to make the client compatible with v1.18?

**Comment by davidxia** [comment]
@diptanu Great to hear you're using it at Netflix. We're definitely open to PRs. Sorry we haven't been more actively working on this recently. Other stuff came up on our roadmap.

**Comment by diptanu** [comment]
@davidxia Please see my fork, already implemented support for Labels and Mac Addresses. Just testing the cpushares, memory, cpuset related changes now. Please expect a PR soon!

**Comment by diptanu** [comment]
@davidxia https://github.com/spotify/docker-client/pull/190

**Comment by diptanu** [comment]
Can you guys take a look please?

**Comment by davidxia** [comment]
@diptanu Thanks for this. So sorry about the delay. I'm reviewing now.

**Comment by davidxia** [comment]
closing as https://github.com/spotify/docker-client/pull/190 has been merged.
