### ISSUE TITLE
Passing credentials to "push"

### ISSUE THREAD

**Issue by lcoote** [spotify/docker-client#19]
I am playing with the spotify docker-client (via the maven plugin). I would like to be able to specify credentials when I "push". I would be quite happy to add this myself. Is there a preferred impl path. The simplest choices I see:
1. add top level configuration properties user id/password to the docker client
2. add user id/password as parameters to the existing (but optional) parameters to existing "push" overloads
3. add new "push" overloads that accept user id/password as parameters

I am guessing (3) is preferable but would like confirmation that this is acceptable before spending the time.

**Comment by stozk** [comment]
Hi, 

I can't get the authentication to work for pushing and pulling.
I'm using nginx as a proxy to secure the repository.
I've also tried "docker-java", which worked with my credentials.
I also tried the code posted in here by harmanpa above, but all I get is this in the docker log.

DEBU[0996] http://127.0.0.1:5000/v1/repositories/user/helloworld/ -- HEADERS: map[User-Agent:[docker/1.4.1 go/go1.3.3 git-commit/5bc2ff8 kernel/3.13.0-44-generic os/linux arch/amd64]] 
Error: Status 401 trying to push repository ipadas/helloworld: <html>
<head><title>401 Authorization Required</title></head>
<body bgcolor="white">
<center><h1>401 Authorization Required</h1></center>
<hr><center>nginx/1.4.6 (Ubuntu)</center>
</body>
</html>

I'm not sure what I'm doing wrong... any ideas?

BR
Daniel

**Comment by gbougeard** [comment]
I have the same issue and I am wondering if it's linked to using a docker registry v1 ?
