### ISSUE TITLE
Inspect Container - MacAddress

### ISSUE THREAD

**Issue by BCotrim** [spotify/docker-client#198]
The method Inspect Container doesn't have an entry for the MacAddress.
The request response:
...
"NetworkSettings": {
        "Bridge": "",
        "Gateway": "",
        "IPAddress": "",
        "IPPrefixLen": 0,
        "MacAddress": "",
        "PortMapping": null,
        "Ports": null
    },
...

https://docs.docker.com/reference/api/docker_remote_api_v1.18/#inspect-a-container

**Comment by rohansingh** [comment]
Fixed by #199.
