### ISSUE TITLE
StartContainer with HostConfig needs documentation

### ISSUE THREAD

**Issue by cleuton** [spotify/docker-client#200]
Hi, 

The "startContainer" method does not receive "hostConfig" parameter anymore, and it is not documented. 

The correct way is do it like this: 

```
		final HostConfig hostConfig = HostConfig.builder()
				.portBindings(portBindings).build();

		final ContainerConfig configCt = ContainerConfig.builder()
			    .image(dockerImageName).exposedPorts(exposedPort)
			    .hostConfig(hostConfig)
			    .build();

```

**Comment by codeslingerMalthius** [comment]
and then what does one do with the configCt object? startContainer still only takes the containerId String.

**Comment by timoreimann** [comment]
I don't see how the issue is resolved: `createContainer` takes a `ContainerConfig`, while `startContainer` used to accept a `HostConfig`.

**Comment by timoreimann** [comment]
Alright, so the `ContainerConfig` now wraps the  `HostConfig`. I'll add a PR to update the README.
