### ISSUE TITLE
Issue in compile and run test cases

### ISSUE THREAD

**Issue by Shaileshk-egnaroinc** [spotify/docker-client#210]
I had run test cases of spotify/docker-client by using "mvn test" command on one command line prompt , and for connecting docker-java client to Docker server,I had use the following command on another command line prompt which is given below-
1. sudo killall docker
2. sudo rm -r /var/run/docker.pid
3. sudo docker -H tcp://127.0.0.1:49155 -H unix:///var/run/docker.sock -d &

But it shows error where I run "mvn test" command which is given below- 

Running com.spotify.docker.client.DefaultDockerClientTest
- testCommitContainer
- testExecInspect
- testConnectTimeout
- testVolumesFrom
- testUnpauseBadContainer
- testSsl
- testTag
- testFailedBuildDoesNotLeakConn
- testDockerDateFormat
- testPullWithTag
- testSearchImage
- testStats
- testAuth
- testExec
- testInfo
- testPullBadImage
- testFailedPushDoesNotLeakConn
- testRemoveImage
- testCustomProgressMessageHandler
- testStartBadContainer
- testBadAuth
- testBuildName
- testBuildNoRm
- testRemoveBadImage
- testListImages
- testStopContainer
- testCreateContainerWithBadImage
- testPullPrivateRepoWithBadAuth
- testGetImageIdFromBuild
- testTagForce
- testVersion
- testCopyContainer
- testKillBadContainer
- testTagBadImage
- testAttachLog
- testPauseContainer
- testPauseBadContainer
- testRestartBadContainer
- testFailedPullDoesNotLeakConn
- testExitedListContainersParam
- testInspectImage
- interruptTest
- testInspectContainerWithSecurityOpts
- testInspectContainerWithExposedPorts
- testContainerWithHostConfig
- testStopBadContainer
- testMacAddress
- testConnectionRequestTimeout
  Jul 14, 2015 5:17:46 PM org.apache.http.impl.execchain.RetryExec execute
  INFO: I/O exception (org.apache.http.NoHttpResponseException) caught when processing request to {}->unix://localhost:80: The target server failed to respond
  Jul 14, 2015 5:17:46 PM org.apache.http.impl.execchain.RetryExec execute
  INFO: Retrying request to {}->unix://localhost:80
- testExportContainer
- testPullPrivateRepoWithoutAuth
- testLabels
- testWaitContainer
- testReadTimeout
- testRemoveBadContainer
- testBuildImageId
- testBadDockerCertificates
- integrationTest
- testAnsiProgressHandler
- testBuildNoCache
- testBuildImageIdWithAuth
- testPingReturnsOk
- testRestartContainer
- testMissingAuthParam
- testPullPrivateRepoWithAuth
  Tests run: 64, Failures: 0, Errors: 1, Skipped: 4, Time elapsed: 621.383 sec <<< FAILURE!
  Running com.spotify.docker.client.messages.ContainerTest
  Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.002 sec
  Running com.spotify.docker.client.messages.ContainerStateTest
  Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.004 sec
  Running com.spotify.docker.client.DefaultDockerClientUnitTest
  Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.025 sec
  Running com.spotify.docker.client.CompressedDirectoryTest
  Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.009 sec

Results :

Tests in error:
 testSsl(com.spotify.docker.client.DefaultDockerClientTest): java.util.concurrent.ExecutionException: javax.ws.rs.ProcessingException: org.apache.http.conn.HttpHostConnectException: Connect to localhost:49153 [localhost/127.0.0.1] failed: Connection refused

Tests run: 122, Failures: 0, Errors: 1, Skipped: 4

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 10:27.422s
[INFO] Finished at: Tue Jul 14 17:19:40 IST 2015
[INFO] Final Memory: 21M/300M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.10:test (default-test) on project docker-client: There are test failures.
[ERROR]
[ERROR] Please refer to /home/shailesh/Downloads/docker-client-master/target/surefire-reports for the individual test results.
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

Thanks

**Comment by davidxia** [comment]
Is this still an issue for you?

**Comment by johnflavin** [comment]
I also routinely get failures on `testSsl`. I haven't taken the time to figure out why. Partially because I suspect it is a problem with the configuration of the docker daemon on my vm, not with your code, but also because I haven't touched anything that test covers so I wouldn't expect any regressions there.

Still, maybe I should try to figure out what is happening.

**Comment by davidxia** [comment]
@Shaileshk-egnaroinc I just ran `mvn test` on the [latest master commit](f672da40b999b42c02d4568df2beae97c08589a8) and all the tests passed for me. Is this still an issue for you?

## Software:

- docker version: 

Client:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        Thu Jul 28 23:54:00 2016
 OS/Arch:      darwin/amd64

Server:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 17:52:38 2016
 OS/Arch:      linux/amd64
