### ISSUE TITLE
Client termination problem

### ISSUE THREAD

**Issue by helander** [spotify/docker-client#22]
I am calling the DefaultDockerClient from within a class that is run via the java goal of the exec-maven-plugin. All of the operations I do works fine but the procedure does not terminate. It seems as if the DefaultDockerClient creates some resource (e.g. thread) that do not allow my procedure to terminate. After 15 seconds of activity the exec plugin forcefully terminates. Any idea what this is and what could be done?

**Comment by davidxia** [comment]
@helander is this still an issue? If not I can close this.

**Comment by helander** [comment]
Please go ahead and close it.

Skickat från min iPhone
