### ISSUE TITLE
Syntax for portSpecs

### ISSUE THREAD

**Issue by helander** [spotify/docker-client#23]
Can someone provide an example of how to build a ContainerConfig that contains port bindings, e.g.
container port 8080 bound to host port 80 ?

**Comment by jdeppe-pivotal** [comment]
It's 2 years later and I'm not sure if the API has since changed, but I believe this is correct:
```
portBindings.put("8080/tcp", Lists.newArrayList(PortBinding.of("HostPort", "80")));
```
