### ISSUE TITLE
Push images to private registry

### ISSUE THREAD

**Issue by gbougeard** [spotify/docker-client#232]
Hi,

I'm trying to push images to my private registry and I do not find out to do it.
I guessed I had to configure my private registry only in the `authConfig` passed to the `DefaultDockerClient.Builder` but it looks like it tries to push on the default registry : 

```
 val authConfig:AuthConfig = AuthConfig.builder().email("jenkins@mycompany").username("jenkins").password("pwd").serverAddress("https://my-docker-registry.net").build()
    val docker : DockerClient = DefaultDockerClient.fromEnv()
      .authConfig(authConfig)
      .build()
docker.push(tag)
```
=>
```
com.spotify.docker.client.ImagePushFailedException: Image push failed: codebase-center:default: ProgressMessage{id=null, status=null, stream=null, error=Post https://registry-1.docker.io/v2/library/codebase-center/blobs/uploads/: token auth attempt for registry: https://auth.docker.io/token?account=jenkins&scope=repository%3Alibrary%2Fcodebase-center%3Apush%2Cpull&service=registry.docker.io request failed with status: 401 Unauthorized, progress=null, progressDetail=null}
```

Do I miss something or do something wrong?

Thanks for your help

**Comment by vberruchon** [comment]
Hi, I'm also searching how to push to a private registry with the docker-client.
Did you find something about how to configure the registry you want to use?

**Comment by gbougeard** [comment]
Finally I did not go further :/

**Comment by mattnworb** [comment]
Have you tagged the image you are attempting to push to a private repository with the URL of that repository? i.e. `docker push repository.company.com/foo/bar`

http://stackoverflow.com/a/28349540/4249

**Comment by vberruchon** [comment]
Finally it was OK for me using an "AuthConfig" to configure the registry for the DockerClient :
<code>AuthConfig authConfig = AuthConfig.builder().email(dockerUserEmail)
					.username(dockerUsername).password(dockerPassword)
					.serverAddress(registryURL).build();
</code>

But I didn't find much documentation about that - is there a documentation outside from GitHub that I missed ?
And effectively one have to remember to tag the image correctly before pushing (without upper class character in the tag, ever had the problem using version from another system in the tag).
