### ISSUE TITLE
How do I copy some files from host to container?

### ISSUE THREAD

**Issue by rgarbin** [spotify/docker-client#233]
docker cp Improved in release 1.8, now we can send files from host to container.

https://github.com/docker/docker/wiki/Engine-1.8.0
https://docs.docker.com/reference/api/docker_remote_api_v1.20/

This is a nice feature to docker-client  improvement too?

**Comment by tiagodeoliveira** [comment]
+1

**Comment by mauricioklein** [comment]
+1

**Comment by arturschuch** [comment]
+1

**Comment by rgarbin** [comment]
This issue can be closed, right @mattnworb ?
