### ISSUE TITLE
Ports Mapping

### ISSUE THREAD

**Issue by damianopezzotti** [spotify/docker-client#239]
Hi,
I'm trying to create a container exposing a port on the host machine.
Following my code snippet:

```
        final String[] ports = { "8080" };
        final Map<String, List<PortBinding>> portBindings = new HashMap<String, List<PortBinding>>();
        for ( String port : ports ) {
            List<PortBinding> hostPorts = new ArrayList<PortBinding>();
            hostPorts.add( PortBinding.of( "0.0.0.0", null ) );
            portBindings.put( port + "/tcp", hostPorts );
        }
        final HostConfig hostConfig = HostConfig.builder().portBindings( portBindings ).build();

        final ContainerConfig containerConfig = ContainerConfig.builder()
                .hostConfig( hostConfig )
                .image( "sample" )
                .build();
```

When container is created on Docker, port isn't published on the host container
```
docker ps
CONTAINER ID        IMAGE               COMMAND                CREATED             STATUS              PORTS               NAMES
d35dee09c2a0        sample              "/jboss-as-7.1.1.Fin   14 hours ago        Up 3 seconds                            sample
```

If I create the container using docker or docker-compose, everything works fine.
If my image publish a port (using EXPOSE directive in Dockerfile) port is correctly published on the host.

Where is the problem?

Thanks

**Comment by stozk** [comment]
I also can't figure out how to do the port binding...
 The container which gets created by the client just lists this for the ports: 8080/tcp 

While the container I created manually has the port binding set properly: 0.0.0.0:8383->8080/tcp   

(using this command: sudo docker run -p 8383:8080 -d imagename) 

I also used the same code as you respectively the code from the readme...

**Comment by stozk** [comment]
Ok I fixed it for me at least... I'Ve been using client version 3.0.1-snapshot, upgraded to the latest one (3.1.2), now it works.

**Comment by damianopezzotti** [comment]
I tried to upgrade client from 3.1.4 to 3.1.5-SNAPSHOT but nothing changes...
No ports are exposed on host machine

**Comment by subshell** [comment]
Do you have the latest version of Docker installed (currently 1.8.3)? We've had the same problem with docker 1.0.1, which came with Ubuntu Trusty.

**Comment by damianopezzotti** [comment]
Hi,
The following code works for me (exposes container port 8080 on host port 9999)

```
final ContainerConfig containerConfig = ContainerConfig.builder()
    .hostConfig( HostConfig.builder()
        .portBindings( ImmutableMap.of( "8080/tcp", Arrays.asList( PortBinding.of( "", "9999" ) ) ) ).build() )
    .image( imageName )
    .exposedPorts( "8080/tcp" )
    .build();
```

**Comment by mattnworb** [comment]
Hey @damianopezzotti, sorry for the delayed response, but as you've found the key is to include the port in the `.exposedPorts()` map on the ContainerConfig.
