### ISSUE TITLE
Fetching images does not authenticate

### ISSUE THREAD

**Issue by hotstepper13** [spotify/docker-client#242]
Hey guys,

we have setup artifactory as private registry and are able to push images to the registry by using the spotify maven plugin. Yesterday we discovered that if I clean the local cache our builds are no longer succeeding. After doing some research it looks like that the client isnt authenticating while fetching images from the remote registry.

In our logs I saw 3 requests to /v2/ which are answered with http status 401
After that I saw another 2 requests which seems to guess the artifact location.

While pushing I see one request to /v2/ and the 401 response. After that the client will authenticate and everything works well.

If I use plain docker everything is working as exspected.

We set up authentication by having a server with ID "artifactory" in our settings.xml and reference this by having the corrosponding entry.

```
        <plugin>
            <groupId>com.spotify</groupId>
            <artifactId>docker-maven-plugin</artifactId>
            <version>0.3.3</version>
            <configuration>
                <serverId>artifactory</serverId>
                <registryUrl>https://xxxxxxxxxxxxxxxxxxxxxxxx/v2/</registryUrl>
                <imageName>${docker.image.prefix}/${project.artifactId}</imageName>
                <dockerDirectory>src/main/docker</dockerDirectory>
                <resources>
                    <resource>
                        <targetPath>/</targetPath>
                        <directory>${project.build.directory}</directory>
                        <include>${project.build.finalName}.jar</include>
                    </resource>
                </resources>
            </configuration>
        </plugin>
```

I tried the latest tagged version of the spotify-docker-plugin which uses the latest tagged version of the docker-client.

Can someone verify if this is a bug in the library or a misuse? (In case of misuse any hint what we are doing wrong would be appreciatiated).

Thanks in advance and best regards

Frank

**Comment by walbus** [comment]
I had the same problem while using the Spotify-docker-client or the spotify-docker-maven-plugin, and docker api version 1.19 or 1.20.

Docker has changed the format of the JSON X-Registry-Config in version 1.19 and again in version 1.20.
In 1.18 they use
{"configs":{"myrepository":{
    "username":"myusername",
    "password":"mypassword",
    "auth":"",
    "email":"myemail",
    "serveraddress":"myserverAddress"}}}
In 1.20 it is 
{"myrepository":{
    "username":"myusername",
    "password":"mypassword",
    "auth":"",
    "email":"myemail",
    "serveraddress":"myserverAddress"}}
Where "configs" is removed.

This can be fixed with a change to AuthRegistryConfig.java.

This might be your problem.

**Comment by davidxia** [comment]
@hotstepper13 Is this still an issue or can I close?

**Comment by karlney** [comment]
We have the same issue with v 3.5.9 and docker 1.9.1 and the bintray repository.

The ./docker/config.json looks like this:
{
	"auths": {
		
		"meltwater-docker-registry.bintray.io": {
			"auth": "<HASH>",
			"email": "karl.neyvaldt@meltwater.com"
		}
	}

I get this error:

22:18:50.789 [main] INFO  c.s.d.client.DefaultDockerClient - Starting container with Id: 6bc3803a3cb6fc763bf2d93ac0fcd0538379306e7e63345e35dc1a3e908cdd26
22:18:51.043 [main] INFO  c.s.d.client.DefaultDockerClient - Creating container with ContainerConfig: ContainerConfig{hostname=null, domainname=null, username=null, attachStdin=null, attachStdout=null, attachStderr=null, portSpecs=null, exposedPorts=[9300, 9200], tty=null, openStdin=null, stdinOnce=null, env=null, cmd=null, image=meltwater-docker-registry.bintray.io/elasticsearch-meltwater:latest, volumes=null, workingDir=null, entrypoint=null, networkDisabled=null, onBuild=null, labels=null, macAddress=null, hostConfig=HostConfig{binds=null, containerIDFile=null, lxcConf=null, privileged=null, portBindings={9300=[PortBinding{hostIp=0.0.0.0, hostPort=48179}], 9200=[PortBinding{hostIp=0.0.0.0, hostPort=47509}]}, links=null, publishAllPorts=null, dns=null, dnsSearch=null, extraHosts=null, volumesFrom=null, networkMode=null, securityOpt=null, memory=null, memorySwap=null, cpuShares=null, cpusetCpus=null, cpuQuota=null, cgroupParent=null}}
22:18:52.925 [main] INFO  c.s.docker.client.LoggingPullHandler - pull meltwater-docker-registry.bintray.io/elasticsearch-meltwater:latest: ProgressMessage{id=null, status=Pulling repository meltwater-docker-registry.bintray.io/elasticsearch-meltwater, stream=null, error=null, progress=null, progressDetail=null}
22:18:53.368 [main] DEBUG c.s.d.client.messages.AuthConfig - Using configfile: /home/kneyvaldt/.docker/config.json
22:18:55.181 [main] INFO  c.s.docker.client.LoggingPullHandler - pull meltwater-docker-registry.bintray.io/elasticsearch-meltwater:latest: ProgressMessage{id=null, status=Pulling repository meltwater-docker-registry.bintray.io/elasticsearch-meltwater, stream=null, error=null, progress=null, progressDetail=null}
com.spotify.docker.client.ImagePullFailedException: Image pull failed: meltwater-docker-registry.bintray.io/elasticsearch-meltwater:latest: ProgressMessage{id=null, status=null, stream=null, error=Authentication is required., progress=null, progressDetail=null}

	at com.spotify.docker.client.LoggingPullHandler.progress(LoggingPullHandler.java:41)
	at com.spotify.docker.client.ProgressStream.tail(ProgressStream.java:74)
	at com.spotify.docker.client.DefaultDockerClient.pull(DefaultDockerClient.java:793)
	at com.spotify.docker.client.DefaultDockerClient.pull(DefaultDockerClient.java:773)

**Comment by Falkurk** [comment]
Same problem for me. Is there any temporary solution ?

**Comment by davidxia** [comment]
Sorry for not replying quickly. Is this still an issue with the latest client or can I close?

**Comment by Falkurk** [comment]
Hi, I didn't try with the latest client. I found a workaround since my last post.

Sincerely

**Comment by mattnworb** [comment]
We have revamped authentication support in 8.6.0 and 8.7.0 and I believe this should no longer be an issue. Please create a new issue if still having problems.
