### ISSUE TITLE
How can I write some text to running container STDIN?

### ISSUE THREAD

**Issue by mfilippov** [spotify/docker-client#243]
How can I write some text to running container STDIN?

**Comment by rgrunber** [comment]
I think this is the same as Issue #156 . It's not really supported, but it is possible to do with some extra work. One basically needs to retrieve the stream before it's cast as just an input stream by the apache httpclient library and get a reference to the output stream. More information on how one could do this is found there.

**Comment by davidxia** [comment]
closing this duplicate issue
