### ISSUE TITLE
Support labels on container

### ISSUE THREAD

**Issue by kmbulebu** [spotify/docker-client#253]
Docker create a container API provides facilities for assigning metadata via labels to containers. Enhancement would add some matching support in docker-client:

1) Enhance DockerClient.createContainer and ContainerConfig to support adding labels.
2) Enhance DockerClient.inspectContainer and ContainerInfo to include labels.
3) Enhancer DockerClient.listContainers and ListContainersParam to support querying by label.
4) Enhance Container returned by DockerClient.listContainers to include labels.

**Comment by davidxia** [comment]
@kmbulebu sounds like something that'd be good to have. We're open to PRs :)

**Comment by kmbulebu** [comment]
I'm open to submitting. It's in my backlog :)

**Comment by kmbulebu** [comment]
Step 1, creating a container with labels was addressed with commit 6109390.

**Comment by kmbulebu** [comment]
PR #285 addresses Steps 3 and 4. That should close it out.
