### ISSUE TITLE
Documentation (README.md) is outdated

### ISSUE THREAD

**Issue by Khazrak** [spotify/docker-client#259]
// Start container
<code>
docker.startContainer(id, hostConfig);"
</code>

Isn't up to date. hostConfig is not an argument to startContainer anymore

**Comment by timoreimann** [comment]
I fixed this already back in July along PR #200. However, it seems to have been reverted by @nurkiewicz as part of commit 87fc813476dad47c21281bf60b653804ad433ab0 in August. At that time, the old API wasn't in master anymore to my understanding.

**Comment by davidxia** [comment]
@Khazrak @timoreimann Thanks for noticing this. I've reverted https://github.com/spotify/docker-client/commit/87fc813476dad47c21281bf60b653804ad433ab0
