### ISSUE TITLE
Transient failures from pushing images in DefaultDockerClientTest

### ISSUE THREAD

**Issue by mattnworb** [spotify/docker-client#270]
These two tests in DefaultDockerClientTest often fail transiently when run in CircleCI

> testPushPrivateImageWithAuth - in com.spotify.docker.client.DefaultDockerClientTest
> testPushPublicImageWithAuth - in com.spotify.docker.client.DefaultDockerClientTest

error is `429 Too Many Requests` from the registry

> com.spotify.docker.client.ImagePushFailedException: Image push failed: dxia4/docker-client-test-push-private-image-with-auth: ProgressMessage{id=null, status=null, stream=null, error=Post https://registry-1.docker.io/v2/dxia4/docker-client-test-push-private-image-with-auth/blobs/uploads/: token auth attempt for registry: https://auth.docker.io/token?account=dxia4&scope=repository%3Adxia4%2Fdocker-client-test-push-private-image-with-auth%3Apush%2Cpull&service=registry.docker.io request failed with status: 429 Too Many Requests, progress=null, progressDetail=null}

It doesn't help that we run each test twice, in parallel, with DOCKER_HOST set to `tcp://...` and `unix://..`, and the issue is compounded if there happen to be more than branch being tested at the same time.

It would be nice to fix these issues to avoid transient errors on pull requests from contributors. A few ideas:

- do we really need to run the same tests with both `DOCKER_HOST=tcp://...` and `DOCKER_HOST=unix://..` still?
- do we even need to be pushing to the docker.io registry to hit whatever logic the test is trying to test?
- if answer to both above is yes, perhaps we could add some logic to the test to cycle through a handful of repository-name / authentication credentials (not sure which of these being used too concurrently is causing the 429) so that two runs of the test at roughly the same time don't use the same pair.

**Comment by davidxia** [comment]
Good points.

* It's nice to test both tcp and unix as that ensures users can use it for both.
* When I wrote the two tests, I didn't know we'd get rate limited. It was both less work and more end-to-end to hit docker hub.
* I can't find any docs on what the rate limit is for hub. Cycling through more credentials seems like a poor solution though.

Not actually pushing to docker hub seems the best. Perhaps we can just skip those two tests if it's not a release build?

**Comment by davidxia** [comment]
fixed by https://github.com/spotify/docker-client/pull/280
