### ISSUE TITLE
DefaultDockerClientTest testAttachContainer hangs forever with Docker API version 1.21

### ISSUE THREAD

**Issue by mattnworb** [spotify/docker-client#273]
Just leaving this here for future reference, but this test seems to block forever when running against Docker API version 1.21 (Docker 1.9.0).

I took a look in the debugger and it seems like the blocking occurs after the actual logs from the (no longer running) container are read and returned. The log output from the container's command of `ls -la` is consumed and returned from LogReader, but then [the next call to](https://github.com/spotify/docker-client/blob/49130141d4070013881f16a46c1baf9de473bb47/src/main/java/com/spotify/docker/client/LogReader.java#L51)

```
final int n = ByteStreams.read(stream, headerBytes, 0, HEADER_SIZE);
```

blocks forever. Seems like the daemon is holding the connection open but not returning any more bytes.

Haven't had a chance yet to test this on other versions.

**Comment by rgrunber** [comment]
I don't think this is related to the version of Docker as I've reproduced even against 1.20 (Docker 1.8.0). The error is definitely happening due to commit b76fc63 but not consistently. In some cases, the read call returns 0, and in others it hangs.

**Comment by rgrunber** [comment]
So, after yet another round of testing out assumptions, I don't think commit b76fc63 is responsible. I've reproduced the issue on v3.1.9, v3.1.1, and v2.7.18, so I think this has been around for a while.

If anyone is interested in reproducing more consistently in tests : rgrunber/docker-client@e8658d5
Just run : `mvn clean test -Dtest=DefaultDockerClientTest#testAttachLog` (reproducible on both unix/tcp sockets so specify DOCKER_HOST as needed)

**Comment by mattnworb** [comment]
Thanks @rgrunber for the research and info, I happened to independently find the same workaround before looking at your notes :smile: 

On one hand the test should be smarter about not attaching to a probably-stopped container, on the other hand it seems like DockerClient should be smart about somehow notifying the caller that the container will never have more output (although I am not sure if this is possible through the Remote API).
