### ISSUE TITLE
invoking execCreate always results in javax.ws.rs.ProcessingException: Unable to invoke request

### ISSUE THREAD

**Issue by grexe** [spotify/docker-client#283]
Using the spotify docker Java api 3.2.1 against Docker daemon version 1.8.1, build d12ea79, calling 

    execCreate(<id of a running container, checked with docker ps>, new String[]{"bash", "-c", "ls"}, DockerClient.ExecParameter.STDOUT, DockerClient.ExecParameter.STDERR)}}

no matter what I do (also tried the example), in my environment (actually a docker compose group running on Linux (4.1.4-1-CHAKRA #1 SMP PREEMPT Sun Aug 9 19:59:32 UCT 2015 x86_64 GNU/Linux), I always get a 

    java.util.concurrent.ExecutionException: javax.ws.rs.ProcessingException: Unable to invoke request

instead of an execId...
Running on wildfly 9.0.2 (from inside an EAR).

**Comment by mattnworb** [comment]
@grexe is there more to the exception and stacktrace that you can share? 

If it is a 500 Internal Server Error, can you share the relevant output from docker daemon's log?

**Comment by grexe** [comment]
oh sorry, now I see - the container seems to be not running at that time, race condition...

    Nov 13 22:12:40 grexps docker[489]: time="2015-11-13T22:12:40.748707905+01:00" level=error msg="Error setting up exec command in container d2a187c7-f228-440c-91f7-449a84ccad0f: Container d2a187c7-f228-440c-91f7-449a84ccad0f is not running"
    Nov 13 22:12:40 grexps docker[489]: time="2015-11-13T22:12:40.748725021+01:00" level=error msg="Handler for POST /containers/{name:.*}/exec returned error: Container d2a187c7-f228-440c-91f7-449a84ccad0f is not running"
    Nov 13 22:12:40 grexps docker[489]: time="2015-11-13T22:12:40.748743166+01:00" level=error msg="HTTP Error" err="Container d2a187c7-f228-440c-91f7-449a84ccad0f is not running" statusCode=500

Would be nice if the API returned the real error, though...,-)

**Comment by grexe** [comment]
ok in the meantime I have reworked the code and I am now confident (checked the ContainerConfig) that I get the correct container and it is *running*, the call works in e.g. Postman at the same time (returning 201), but throws an Exception in the spotify API...
The docker daemon log now does not report any error as far as I could see.

**Comment by grexe** [comment]
could it be that the API does not correctly handle the result "201 Created" that's returned by a successful ExecCreate call (see Docker docs)?
Because ignoring the Exception seems to work, and I see the result of the ExecCmd in my container!

**Comment by mattnworb** [comment]
@grexe you can invoke `mvn` with the `-e` switch to have it output a full stacktrace of any exceptions thrown by the plugin, having this would be useful to help troubleshoot.

**Comment by grexe** [comment]
Problem is not during build, and I see the full stack trace (given below), but the problem is that in 4/5 cases the Exec call does not work, but in the end the effect *can* be seen in the container, but only in my local environment, not on the test server... it's a real heisenbug...

    com.spotify.docker.client.DockerException: java.util.concurrent.ExecutionException: javax.ws.rs.ProcessingException: Unable to invoke request                                                                           

2015-11-16 15:56:46,963 DEBG 'wildfly' stdout output:                                                                                                                                                                                                                                                                                                      

Sadly I cannot see anything useful in the docker log now.

**Comment by grexe** [comment]
I had to resort to using SSH and execute the command over that for my purpsoses, sadly, but at least it works now.
