### ISSUE TITLE
docker-client should be smarter about attaching to a stopped container

### ISSUE THREAD

**Issue by davidxia** [spotify/docker-client#288]
Ever since we use a no timeout client for attaching to a container (see https://github.com/spotify/docker-client/commit/b76fc6387289b1d310a22501e033c07c5895b7ad), if you attach to a stopped container, the docker-client just hangs forever. How can we be smart about this?

**Comment by rgrunber** [comment]
While I can't exactly rule out b76fc63 from possibly making the issue more visible, I determined in [Issue #273](https://github.com/spotify/docker-client/issues/273#issuecomment-156519331) that the problem existed as early as v2.7.18, which would rule out that commit (introduced in v3.1.10).
