### ISSUE TITLE
docker logs throws IOException/ although container is running

### ISSUE THREAD

**Issue by grexe** [spotify/docker-client#289]
I read similar issues and tried the tests, but in my case, when trying to get the logs of a _running_ container and even halting in a debug breakpoint (so I definitely know the container is there and has status running, checked the ContainerInfo), I always get a

```
java.io.IOException: Attempted read on closed stream.
```

Here's my code:

```
 LogStream stream = client.logs(containerId, stdout(), stderr());
                logs = stream.readFully();
```

But taking the request out of the fresh docker daemon log and pasting it into Postman works just fine:

```
GET /containers/76e1cb34fbc9/logs?stdout=true
```

Response: HTTP 200, log output

Using Docker API 3.2.1 on Linux x64 4.1.4-1 and Docker version 1.8.1, build d12ea79

**Comment by mattnworb** [comment]
A bit random but are you sure that the code in the debugger and the browser are talking to the same `DOCKER_HOST`?

**Comment by grexe** [comment]
yes it's the same host, all running locally on my laptop, and there's only one docker daemon running...
This is really a downer since I have several "worker" containers running that are reused and restarted on-the-fly, so it's hard to track down the logs in time without introducing a shared log folder or rewriting the container management code...

**Comment by davidxia** [comment]
@grexe Is this still an issue? Do you have steps to repro?
