### ISSUE TITLE
Docker Api 1.21 Support

### ISSUE THREAD

**Issue by alfre86** [spotify/docker-client#291]
Do you plan to support new Docker Api 1.21 features (e.g. Networking)?

**Comment by davidxia** [comment]
There are no plans for it yet, but we are open to PRs.

On Mon, Nov 23, 2015 at 10:26 AM, alfre86 <notifications@github.com> wrote:

> Do you plan to support new Docker Api 1.21 features (e.g. Networking)?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/spotify/docker-client/issues/291>.
>



-- 
David Xia
Software Engineer
dxia@spotify.com

**Comment by teetrinkers** [comment]
I implemented some basic support in #306.

**Comment by damianopezzotti** [comment]
We have implemented complete Docker 1.9 network support in #307

**Comment by davidxia** [comment]
#307 has been merged.

**Comment by damianopezzotti** [comment]
Thanks!

2015-12-29 17:35 GMT+01:00 David Xia <notifications@github.com>:

> #307 <https://github.com/spotify/docker-client/pull/307> has been merged.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/spotify/docker-client/issues/291#issuecomment-167826713>
> .
>



-- 
Damiano Pezzotti
...................................... . .
Software Architect | Alambitco
mobile +39 333 2116258
fax +39 02 700432209
email damy@alambitco.com
web www.alambitco.com
flickr www.flickr.com/photos/damianopezzotti
linkedin www.linkedin.com/in/damianopezzotti
pgp id 0x12DFD989

**Comment by johnflavin** [comment]
FYI: I'm working on a PR for the last big API 1.21 feature: [Volumes](https://docs.docker.com/engine/reference/api/docker_remote_api_v1.22/#2-4-volumes). I have it, say, 75% done, but before I finish I need to resolve some questions I have about the Volumes API over at [docker/docker#21605](https://github.com/docker/docker/issues/21605).

**Comment by davidxia** [comment]
At this point the newest docker-client has #307, #306, and #487 which probably cover most of API 1.21. I'm going to close this issue. We can open new ones for specific things that are missing.
