### ISSUE TITLE
docker container not finding the unix socket

### ISSUE THREAD

**Issue by rick-it-2004** [spotify/docker-client#319]
I have a docker container from which I want to spawn a new container. I am using com.spotify:docker-client:3.3.5 for communications.  The code I am running is

    URI uri = URI.create(DefaultDockerClient.DEFAULT_UNIX_ENDPOINT);
              DockerClient docker = DefaultDockerClient.builder().uri(uri).build();

    try {
        return docker.ping();
    } catch (DockerException e) {
        return "(T1) " + e.toString();
    } catch (InterruptedException e){
        return "(T2) " + e.toString();
    }

what I see is a file not found error. It would appear that the problem is around the use of the unix socket, but I don't understand what is wrong. Any help would be gratefully accepted!

    com.spotify.docker.client.DockerException: java.util.concurrent.ExecutionException: javax.ws.rs.ProcessingException: java.io.IOException: No such file or directory

below are the results form version and testing the unix socket

    0 ✓ docker@docker-002  ~/stock_availability $ docker version
    Client:
     Version:      1.9.1
     API version:  1.21...

    Server:
     Version:      1.9.1
     API version:  1.21...

    130 ✗ docker@docker-002  ~/stock_availability $ echo -e "GET /images/docker.mydom.net/stock- availability:v1/json HTTP/1.0\r\n" | nc -U /var/run/docker.sock
    HTTP/1.0 200 OK
    Content-Type: application/json
    Server: Docker/1.9.1 (linux)
    Date: Wed, 30 Dec 2015 16:45:06 GMT
    Content-Length: 1738

    {"Id":"626fb30c8d08..<snip>..400"}}}

**Comment by rgrunber** [comment]
If you're just performing the above code snippet on a host machine running a daemon with unix sockets, it should work, but I think your example is a little more complicated.

When you say : "I have a docker container from which I want to spawn a new container", do you mean you have a container running on your host machine's daemon, and you wish to run a container within that running container ? Is the environment from which you're sending the 'GET' command already within a container ? If any of this is right, then I would guess that your host machine might be running a docker daemon that must communicate over tcp, and that then container's daemon is a unix socket.

To communicate with the container's docker daemon (and not the host's) you'd probably need to do some port forwarding, and I'm not sure if this would work with a unix socket.

**Comment by rick-it-2004** [comment]
Thanks for the reply. 

I have docker running as a service on a centos host. I have a container from which I want to spawn a second container which will also be running on the docker service. The code above is called from the first container.

**Comment by mattnworb** [comment]
I think @rgrunber nailed it. `/var/run/docker.sock` is not visible by default inside a container. You would need to mount it as a volume with `-v /var/run/docker.sock:/var/run/docker.sock` when creating the first container, and [you would probably also need to launch that container as privileged as well](https://docs.docker.com/engine/reference/run/#runtime-privilege-linux-capabilities-and-lxc-configuration) if you really desire to have one container launch another.

As a simple test, run `docker exec first-container-id ls /var/run` to see what is visible inside that container. For example:

```
$ docker run -it ubuntu
root@57ba0f86f8d4:/# ls /var/run
lock  motd.dynamic  network  resolvconf  sendsigs.omit.d  shm  utmp
```
