### ISSUE TITLE
Is there a way to run an image directly from Java?

### ISSUE THREAD

**Issue by Frakcool** [spotify/docker-client#320]
I've been reading the `DockerClient.java` file, unable to find a command which would work as `docker run repo/image`. Probably it is there, but I just haven't found it. With the above code I've been able to pull my image from dockerhub, get docker version, and print a log, I'm trying to execute the Dockerfile, is it possible or am I just losing my time looking for something like this? This is what I have done:
    
    import java.util.ArrayList;
    import java.util.HashMap;
    import java.util.List;
    import java.util.Map;
    
    import com.spotify.docker.client.DefaultDockerClient;
    import com.spotify.docker.client.DockerCertificateException;
    import com.spotify.docker.client.DockerClient;
    import com.spotify.docker.client.DockerException;
    import com.spotify.docker.client.LogStream;
    import com.spotify.docker.client.messages.ContainerConfig;
    import com.spotify.docker.client.messages.ContainerCreation;
    import com.spotify.docker.client.messages.ContainerInfo;
    import com.spotify.docker.client.messages.HostConfig;
    import com.spotify.docker.client.messages.PortBinding;
    
    public class DockerTest {
    	public static void main(String[] args) throws DockerException, InterruptedException, DockerCertificateException {
    		
    		// Create a client based on DOCKER_HOST and DOCKER_CERT_PATH env vars
    		final DockerClient docker = DefaultDockerClient.fromEnv().build();
    
    		// Pull an image
    		docker.pull("frakcool/docker-whale");
    		
    		docker.inspectImage("frakcool/docker-whale:latest");
    		
    		//docker.tag(docker.inspectImage("frakcool/docker-whale:latest").id(), "frakcool/docker-whale:latest");
    		
    		// Bind container ports to host ports
    		final String[] ports = {"80", "22"};
    		final Map<String, List<PortBinding>> portBindings = new HashMap<String, List<PortBinding>>();
    		for (String port : ports) {
    		    List<PortBinding> hostPorts = new ArrayList<PortBinding>();
    		    hostPorts.add(PortBinding.of("0.0.0.0", port));
    		    portBindings.put(port, hostPorts);
    		}
    
    		// Bind container port 443 to an automatically allocated available host port.
    		List<PortBinding> randomPort = new ArrayList<PortBinding>();
    		randomPort.add(PortBinding.randomPort("0.0.0.0"));
    		portBindings.put("443", randomPort);
    
    		final HostConfig hostConfig = HostConfig.builder().portBindings(portBindings).build();
    
    		// Create container with exposed ports
    		final ContainerConfig containerConfig = ContainerConfig.builder()
    		    .hostConfig(hostConfig)
    		    .image("frakcool/docker-whale:latest").exposedPorts(ports)
    		    .cmd("sh", "-c", "while :; do sleep 1; done")
    		    .build();
    
    		final ContainerCreation creation = docker.createContainer(containerConfig);
    		final String id = creation.id();
    		
    		// Inspect container
    		final ContainerInfo info = docker.inspectContainer(id);
    		
    		// Start container
    		docker.startContainer(id);
    
    		// Exec command inside running container with attached STDOUT and STDERR
    		final String[] command = {"bash", "-c", "ls"};
    		final String execId = docker.execCreate(id, command, DockerClient.ExecParameter.STDOUT, DockerClient.ExecParameter.STDERR);
    		final LogStream output = docker.execStart(execId);
    		final String execOutput = output.readFully();
    		
    		System.out.println(execOutput);
    		
    		System.out.println();
    		
    		System.out.println(docker.version());
    		
    		// Kill container
    		docker.killContainer(id);
    	}
    }

**Comment by mattnworb** [comment]
The operations in your code snippet look correct to me - the rough equivalent to `docker run image` would be `pull(..)`, `createContainer(..)`, `startContainer(..)`.

Can you elaborate on what you mean by

> I'm trying to execute the Dockerfile, is it possible

? To build a docker image with the `DockerClient` you would use the `build` methods.

**Comment by Frakcool** [comment]
@mattnworb Hello! With "I'm trying to execute the Dockerfile" I mean, if you do `docker run frakcool/docker-whale` you should see a similar output to the one [here](https://docs.docker.com/linux/step_six/) on the tutorial example (or the one below). What I'm trying to achieve is exactly that, with my Java code and a Dockerfile previously created (like the dockerwhale) and pushed to the dockerhub, then by running this Java file to be able to pull and run the image. The scope for this project is to be able to pull all the tools needed to run a program, but where the customer will have to do nothing but run this java file and get the environment to run the program properly, so this should be like this:

1. Write the Dockerfile (From the tutorial it looks like this one):

        FROM docker/whalesay:latest
        RUN apt-get -y update && apt-get install -y fortunes
        CMD /usr/games/fortune -a | cowsay

2. Push it to the server (Done manually)
3. Write the Java program which will run the command `docker run frakcool/docker-whale` (maybe another but for testing I'm using this one) (The above one)
4. On another PC run the above Java program
5. See a docker whale similar to this one:


      ~~~-~~~-~~~-~~~-~~~~~~~~~~~~~~~~~~~~
    / Everyone is a genius. It's just that  \
    | some people are too stupid to realize |
    \ it.                                   /
     ~~~-~~~-~~~-~~~-~~~~~~~~~~~~~~~~~~~~
        \
         \
          \     
                        ##        .            
                  ## ## ##       ==            
               ## ## ## ##      ===            
           /""""""""""""""""___/ ===        
        ~~~ {~~ ~~~~ ~~~ ~~~~ ~~ ~ /  ===- ~~~   
             \______ o          __/            
              \    \        __/             
                \____\______/   

What I'm actually doing is I'm just able to pull my `frakcool/docker-whale` image but not able to see the whale saying random things, that's exactly what I meant by "Run a Dockerfile"

**Comment by mattnworb** [comment]
Keep in mind that `docker run maryatdocker/docker-whale` when run from a terminal sends the standard output of the process that the image runs (which in this case is `/usr/games/fortune -a | cowsay`) to your terminal's standard out (I think this is `AttachStdout=true` in the HostConfig). 

When you call DockerClient `startContainer(id)` the same isn't true. Docker will capture the stdout of your process and it should be visible if you run `docker logs <containerid>`

**Comment by mattnworb** [comment]
You may have some luck setting `containerConfig.attachStdout(true)` when creating the container.

**Comment by mattnworb** [comment]
`"executing the Dockerfile"` would usually be interpreted as trying to build the image, since that is done from a Dockerfile.

**Comment by Frakcool** [comment]
Didn't know that, I'm sorry about confusion with "executing the Dockerfile" thing, however I'm getting the following error after I added `attachStdout(true)`.

    final ContainerConfig containerConfig = ContainerConfig.builder()
            .hostConfig(hostConfig)
            .image("frakcool/docker-whale").exposedPorts(ports)
            .cmd("sh", "-c", "while :; do sleep 1; done")
            .attachStdout(true)
            .build();

The error I'm getting is: 

    SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
    SLF4J: Defaulting to no-operation (NOP) logger implementation
    SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
    Exception in thread "main" com.spotify.docker.client.DockerRequestException: Request error: POST unix://localhost:80/containers/e0ffb9237af2936345bf8fbd318b9f6a028fe24bd57eb0518b4a3c6a90b06633/start: 500
    	at com.spotify.docker.client.DefaultDockerClient.propagate(DefaultDockerClient.java:1218)
    	at com.spotify.docker.client.DefaultDockerClient.request(DefaultDockerClient.java:1189)
    	at com.spotify.docker.client.DefaultDockerClient.containerAction(DefaultDockerClient.java:449)
    	at com.spotify.docker.client.DefaultDockerClient.startContainer(DefaultDockerClient.java:441)
    	at dockertest.DockerTest.main(DockerTest.java:63)
    Caused by: javax.ws.rs.InternalServerErrorException: HTTP 500 Internal Server Error
    	at org.glassfish.jersey.client.JerseyInvocation.convertToException(JerseyInvocation.java:1002)
    	at org.glassfish.jersey.client.JerseyInvocation.translate(JerseyInvocation.java:799)
    	at org.glassfish.jersey.client.JerseyInvocation.access$500(JerseyInvocation.java:91)
    	at org.glassfish.jersey.client.JerseyInvocation$5.completed(JerseyInvocation.java:760)
    	at org.glassfish.jersey.client.ClientRuntime.processResponse(ClientRuntime.java:197)
    	at org.glassfish.jersey.client.ClientRuntime.access$300(ClientRuntime.java:78)
    	at org.glassfish.jersey.client.ClientRuntime$2.run(ClientRuntime.java:179)
    	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
    	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
    	at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
    	at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
    	at org.glassfish.jersey.internal.Errors.process(Errors.java:267)
    	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:340)
    	at org.glassfish.jersey.client.ClientRuntime$3.run(ClientRuntime.java:209)
    	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
    	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    	at java.lang.Thread.run(Thread.java:745)
    	
Where the line 63 on my program is `docker.startContainer(id);`

**Comment by Frakcool** [comment]
I restarted docker service with `service docker restart`, and now I get the same error but on line 77. Which now it is: `docker.logs(id);`. Which is the last line executed before killing the container docker.killContainer(id);`

So the end of file looks like:

    System.out.println(docker.version());
    docker.logs(id);
    // Kill container
    docker.killContainer(id);

**Comment by Frakcool** [comment]
I got it to work somehow but it shows nothing but:

    Version{apiVersion=1.21, arch=amd64, gitCommit=a34a1d5, goVersion=go1.4.2, kernelVersion=4.2.0-22-generic, os=linux, version=1.9.1}

    com.spotify.docker.client.LogStream@71eed8d

when adding this to the end:

    System.out.println(docker.version());
    System.out.println(docker.logs(id, LogsParam.stdout()).readFully());
    System.out.println(docker.logs(id, LogsParam.stdout()).toString());
