### ISSUE TITLE
Unit tests failing on windows

### ISSUE THREAD

**Issue by sayarg** [spotify/docker-client#327]
pulling the code and running test target on windows as is, fails on a few unit tests. this is in addition to the integration test, which i am out-scoping for the sake of this issue.

specifically:
AuthConfigTest fails on path issues e.g. java.nio.file.InvalidPathException: Illegal char <:> at index 2: /H:/workspace/spotify/docker-client-master/target/test-classes/dockerConfig/fullDockerCfg

DockerHostTest need to be using different defaults for windows
and CompressedDirectoryTest. CompressedDirectory need to use different values when creating the regex matches on windows for the ignore file to work

**Comment by sayarg** [comment]
hello, any thoughts on this? ok to merge the PR?

**Comment by mattnworb** [comment]
@sayarg thanks for the fix and contribution and sorry for the delay in reviewing. I think with #331 merged this closes this issue, right?
