### ISSUE TITLE
Two tests fail to read environment variable DOCKER_CERT_PATH, cannot connect

### ISSUE THREAD

**Issue by johnflavin** [spotify/docker-client#333]
I have a docker host on a local VM set up by the docker toolbox (essentially just created by docker-machine). It is configured to demand TLS verification. Two of the tests in your test suite fail: `testBuildPrivateRepoWithAuth` and `testBuildImageIdWithAuth`. I have the Surefire report up here: https://gist.github.com/johnflavin/c28226e9619dcd30f545.

What seems to be happening is that all the tests in `DefaultDockerClientTest` connect through the `DefaultDockerClient` instance `sut`, which is created in the `setup()` method from a `Builder` made by calling the `DefaultDockerClient.fromEnv()` method. That is, all the tests use `sut` *except* these two, which use their own `sut2` instance created from a bare `DefaultDockerClient.builder()` call. The important difference being that `sut` was made with knowledge of the value of `DOCKER_CERT_PATH`, but `sut2` was not. Therefore, these two tests fail in my environment, as they do not know the proper certificates to use to communicate with the docker server.

I can make a quick pull request that just modifies these two tests to read `DOCKER_CERT_PATH` from the environment and add that to the `Builder`; I've done that on my system and verified that the tests pass. But I wanted to check first if that's a good idea. Really, is there any reason these two tests use `sut2` over `sut`?

**Comment by mattnworb** [comment]
Thanks for the detailed writeup. I think the reason for using `sut2` rather than the `sut` field is to specify a non-null `AuthConfig` in these tests, but it would make more sense for them to create their Builder with `DefaultDockerClient.fromEnv()` rather than `DefaultDockerClient.builder()` (to pick up the env vars).
