### ISSUE TITLE
How to pass parameters to default entrypoint?

### ISSUE THREAD

**Issue by flozano** [spotify/docker-client#344]
When using array format for entrypoint in a Dockerfile, you can pass arguments to the docker run command and they're passed to the entrypoint executable (along with the pre-existing parameters)

However, I cannot find a way to do the same either when creating a ContainerConfig or when creating the container itself in DockerClient.

Am I missing any part of the API ?

**Comment by tedyoung** [comment]
I think you're looking for the cmd() method that ContainerConfig.builder() supplies, which takes a List<String> or a varargs of String...

**Comment by davidxia** [comment]
@flozano Did that answer your question? If so, can I close this?

**Comment by flozano** [comment]
Yes, thank you. I haven't tried yet, however, but the answer makes sense.
