### ISSUE TITLE
add getterMethods for "PortMapping" variables

### ISSUE THREAD

**Issue by fritzrichter** [spotify/docker-client#347]
Currently the variables are hidden as private, but I need to process them in Java. Currently the only solution to actually get them is sth. like this:

`import org.apache.commons.lang3.reflect.FieldUtils;`
`FieldUtils.readField(mapping, "publicPort", true);`

**Comment by davidxia** [comment]
Can't you get them from a `Container` object with `container.ports()`?

**Comment by davidxia** [comment]
@fritzrichter Do you still need this or can I close?
