### ISSUE TITLE
DefaultDockerClient.execCreate() always tries to connect over UNIX socket

### ISSUE THREAD

**Issue by grexe** [spotify/docker-client#352]
This is very slightly related to #283 but I get a different error in a slightly different context.

Using latest stable API 3.5.12 inside a docker-compose group, I try to execute a command on one container inside another running container (for restarting a supervisord service inside the target container):

```
String execId = client.execCreate(container.id(), new String[]{"supervisorctl", "-c", "/etc/supervisord.conf", "restart", "worker"},
                DockerClient.ExecCreateParam.attachStderr(),
DockerClient.ExecCreateParam.attachStdout());
```

My Docker client is connected to : http://dockerhost:2375
(which is resolvable, the same command - I took the POST Url generated by DefaultDockerClient#execCreate() - works just fine over Postman from the host).

However, using the API, the call fails with no concrete error, only in the docker logs, I see it tries to connect over socket instead of TCP/IP as configured:

> level=error msg="attach: stdout: write unix /var/run/docker.sock->@: write: broken pipe"

Is there a way to force TCP/IP connection? When I try to connect from one container to another, sockets won't work...

I'm on Linux 4.4.1-2-MANJARO x64 using Docker 1.9.1 and docker-compose 1.5.2

**Comment by johnflavin** [comment]
> `level=error msg="attach: stdout: write unix /var/run/docker.sock->@: write: broken pipe"`

The error message looks to me less like the client is attempting to connect _to_ the socket, and more like the host is receiving the request correctly over http but having an error trying to write the logs _from_ the socket. Try making the same call but not attaching the `stdout` log and see if it works.

**Comment by davidxia** [comment]
You can use TCP sockets if you set your env vars correctly. See this part in the README:

```java
// Create a client based on DOCKER_HOST and DOCKER_CERT_PATH env vars
final DockerClient docker = DefaultDockerClient.fromEnv().build();
```

**Comment by grexe** [comment]
thanks for the info, tried but did not help.
I can use the API without problems from a standalone app and the same Docker client builder opts (using a valid http:// docker host url).

I seem to run into a similar issue as this one:
http://stackoverflow.com/questions/29938208/docker-client-java-api-the-server-failed-to-respond-with-a-valid-http-response

Because I don't use any other libraries in my standalone test, it works there, but inside my JEE wildfly environment, where we also use RESTeasy, there seems to be a clash with the spotify client lib's Jersey lib. I also tried the shaded JAR, but then my request broke even earlier.

**Comment by davidxia** [comment]
Closing since this issue is pretty old and OP seems to have found a workaround. I can reopen if it's still a problem.
