### ISSUE TITLE
Question - does this work with Rancher?

### ISSUE THREAD

**Issue by juliangamble** [spotify/docker-client#355]
I'm looking to use this with Rancher. Is this feasible?

My question is: **Question - does this work with Rancher?**

**Comment by johnflavin** [comment]
My understanding of [Rancher](http://rancher.com/) is that it provides a GUI front end for managing Docker hosts, images, containers, volumes, etc. It is just a nice way for a person to interact with one or more Docker hosts in a browser. 

This library provides a Java wrapper around the Docker remote API. As such, it is just a nice way for your Java application to interact with a Docker host.

Both things just interact with docker, and that's it. I don't see why you would have a problem using Rancher + this docker-client library any more than you would have a problem using Rancher + the docker command-line client.

**Comment by mattnworb** [comment]
Thanks for answering this @johnflavin. Sounds cleared up to me.
