### ISSUE TITLE
Using container instead of images

### ISSUE THREAD

**Issue by couturierb** [spotify/docker-client#375]
Hello,

With ContainerConfig.builder(), it-is possible to use an already started container instead of creating a new one ?

Thanks !!

**Comment by johnflavin** [comment]
I think that is not possible right now. But it would be easy to modify the `ContainerConfig` to make this possible.

More detail: All of the the model objects in the library use an internal `Builder` object for construction (I think all...). Some of the objects have a `toBuilder` method that initializes a new `Builder` from an existing object. `ContainerConfig` does not have a `toBuilder`. But it's a very simple method, and could be added very quickly.

**Comment by couturierb** [comment]
Thanks for reply :)

I have used another méthod to find and control my container : dockerClient.listContainers(ListContainersParam.create("names", "<container_name>"))

It works well !
