### ISSUE TITLE
improve CI to test against multiple Docker versions

### ISSUE THREAD

**Issue by mattnworb** [spotify/docker-client#387]
We test docker-client in CircleCI against Docker 1.8 (IIRC, that is the oldest version that is available) but for unrelated and uninteresting reasons we use Docker 1.6 internally at Spotify. So after merging PRs from contributors into the project that work fine in 1.8, we find subtle test failures when we try to build the project (in order to release to Maven Central) on our internal Jenkins. 

I'd like to explore soon if it is possible to have a CI solution that can do a matrix build of docker-client against several versions of docker, to try and catch these issues at submission time, rather than release time. I think it would be a lot easier for us as maintainers but also better for contributors also (to be able to tell you that your change breaks on docker 1.7 and 1.8 but works on 1.9, for example).

Alternatively we could run our Jenkins here at Spotify on something > 1.6, but since we are still using that version in production it is important to us to make sure that docker-client is well-tested for 1.6.

**Comment by mattnworb** [comment]
[Travis supports Docker](https://docs.travis-ci.com/user/docker/) now but doesn't appear that you can choose the version.

**Comment by mattnworb** [comment]
One other idea would be to build PRs from contributors on our internal Jenkins, using the Github PR builder plugin (which asks admins to approve testing of each PR to make sure they are not malicious).

**Comment by mattnworb** [comment]
How to install Docker 1.6 or 1.7 on Circle: https://discuss.circleci.com/t/how-use-a-different-docker-version/298/7

1.9: https://discuss.circleci.com/t/docker-1-9-1-is-available/1009

1.10 beta: https://discuss.circleci.com/t/docker-1-10-0-is-available-beta/2100

**Comment by johnflavin** [comment]
Do you want someone (you, me, anyone else) to file issues for all the failures happening over on #389?

**Comment by mattnworb** [comment]
@johnflavin yeah I think that is a fine approach, or a PR that fixes an issue at the same time is fine too. I am going to close this particular issue since we now have a CI solution for Github PRs that tests on > 1 docker version.

**Comment by rgrunber** [comment]
It's good to start addressing this issue. I also wouldn't mind seeing support for, say 2 or 3 previous versions. Generally I don't see checks being contributed when functionality is changed from one version of the docker Remote API to another so that breaks compatibility.

I know that the Remote API has a way to specify what version you expect in response, but it seems versioning isn't really supported for all fields, nor is it clear what fields are versioned (https://github.com/docker/docker/issues/14524) .

**Comment by mattnworb** [comment]
@rgrunber are there specific versions would you like to see support for?

**Comment by rgrunber** [comment]
No specific version. I just mean that at the point of a release for docker-client it should support the same version of docker that is out, and 1 or 2 of the previous ones. At least this way, people who cannot adopt the latest version of docker immediately are still able to use the library against a slightly older version.

It might make contributions a little trickier as people might have a change that works great against the latest docker but don't have much interest in polishing it up and making it behave with older versions.

**Comment by mattnworb** [comment]
I would like to have Travis test against 1.6 through whatever is current. Right now it does 1.6 and 1.8.2 (I think, or another 1.8.x), but just because I haven't had a chance to hunt down why some tests fail on the other versions I introduced in #389
