### ISSUE TITLE
Authentication not working with push to docker hub

### ISSUE THREAD

**Issue by grantlittle** [spotify/docker-client#393]
## Description

When trying to push an existing image from a docker server to docker hub, it appears that authentication is not working correctly. I consistently get the following error

"unauthorized: access to the requested resource is not authorised"

This is exactly the same error I get when I use the docker command line without doing a "docker login" first.

## How to reproduce

I've used the following code to reproduce the problem, replacing the login details and repository details.

I can't find a lot of documentation on the topic, but I've used what documentation I've found to come up with what is below. I hope I've correctly understood the examples.
```
public class SpotifyPushTest {

    public static void main(String... args) throws Exception {


        DefaultDockerClient.Builder builder = DefaultDockerClient.builder()
                .uri(URI.create("https://dockerhost:2376"));

        builder.dockerCertificates(new DockerCertificates(Paths.get("/path/to/certificates")));

        DefaultDockerClient client = builder.build();

        AuthConfig authConfig = AuthConfig.builder()
                .email("me@email.com")
                .username("username")
                .password("password")
                .build();
        int response = client.auth(authConfig);
        assert(response == 200);
        try {
            client.push("login/imagename", new MyProgressHandler());
        } catch (Exception e) {
            e.printStackTrace();
        }
        System.exit(0);


    }

    static class MyProgressHandler implements ProgressHandler {
        @Override
        public void progress(ProgressMessage message) throws DockerException {
            if (null != message.stream()) {
                System.out.println(message.stream());
            }
            if (null != message.error()) {
                System.err.println(message.error());
            }
            if (null != message.progress()) {
                System.out.println(message.progress());
            }
            if (null != message.status()) {
                System.out.println(message.status());
            }

        }
    }
}

```

## What do you expect

I expect the image to be pushed to docker hub.

## What happened instead

I get the error

unauthorized: access to the requested resource is not authorized

## Software:

- docker version: 

Client:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3 
 Git commit:   20f81dd
 Built:        Thu Mar 10 21:49:11 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 21:49:11 2016
 OS/Arch:      linux/amd64

- docker-client version: 3.6.6

**Comment by mattnworb** [comment]
The `auth()` method calls the `/auth` endpoint in the Docker Remote API but does not save the credentials for later use. Instead, pass your `AuthConfig` to the client builder like 

```java
DockerClient client = DefaultDockerClient.builder()
    .authConfig(authConfig)
    ...
    .build();
```

**Comment by grantlittle** [comment]
Awesome, thanks for clarifying the usage. It works fine now. Cheers
