### ISSUE TITLE
How can I get blkio_stats using docker-client?

### ISSUE THREAD

**Issue by kingsmiler** [spotify/docker-client#402]
There is no blkio stats in ContainerStats,  is there some way to get it?

**Comment by johnflavin** [comment]
I see in the [API docs](https://docs.docker.com/engine/reference/api/docker_remote_api_v1.22/#get-container-stats-based-on-resource-usage) that `blkio` is a thing that is returned, and I see that the `ContainerStats` class in `docker-client` does not read it. So short answer is "no, you can't get it". But, like my answer to #403, you could submit a PR (or wait for someone else to do so) to fix this.

**Comment by kingsmiler** [comment]
Thanks :)
