### ISSUE TITLE
Does networks translate to NetworkStats fail?

### ISSUE THREAD

**Issue by kingsmiler** [spotify/docker-client#403]
## Description

I use DEBUG level for logging, and I run docker.stats("id"), then I can see the networks information from console

`"networks":{"eth0":{"rx_bytes":275523,"rx_packets":2364,"rx_errors":0,"rx_dropped":0,"tx_bytes":407693,"tx_packets":6099,"tx_errors":0,"tx_dropped":0}}`

but I cannot find out from containerStats.toString(), it is null "network=null".

Is there something wrong?

**Comment by johnflavin** [comment]
This is a feature that docker added to their API in version 1.9 (API 1.21), but `docker-client` hasn't yet been updated to properly receive that message.

Prior to v1.9, the container stats would only return information about a single network interface—or maybe it was an aggregate of all the network interfaces; I'm not sure—as `"network"`. So you'd get something like this:
```
"network":{"rx_dropped":0,"rx_bytes":648,"rx_errors":0,"tx_packets":8,"tx_dropped":0,"rx_packets":8,"tx_errors":0,"tx_bytes":648}
``` 
See the [v1.20 Remote API docs](https://docs.docker.com/engine/reference/api/docker_remote_api_v1.20/#get-container-stats-based-on-resource-usage). 

In [API v1.21](https://docs.docker.com/engine/reference/api/docker_remote_api_v1.21/#get-container-stats-based-on-resource-usage) (docker v1.9) they changed the container stats to break out the stats for each network separately as `"networks"`. So now you'd get something like this:
```
"networks":{"eth0":{"rx_bytes":5338,"rx_dropped":0,"rx_errors":0,"rx_packets":36,"tx_bytes":648,"tx_dropped":0,"tx_errors":0,"tx_packets":8},"eth5":{"rx_bytes":4641,"rx_dropped":0,"rx_errors":0,"rx_packets":26,"tx_bytes":690,"tx_dropped":0,"tx_errors":0,"tx_packets":9}}
```

`docker-client` needs to be updated to support that. But it hasn't been done yet. If you wanted to submit a PR for this, it wouldn't take that much work but would be greatly appreciated.

**Comment by johnflavin** [comment]
Actually, I'll just do a PR for this myself. It won't be much work, and I think it will fix a test failure we've been seeing when building against versions 1.9 and 1.10.

**Comment by davidxia** [comment]
Thanks for noticing. I just added a commit for it here
https://github.com/spotify/docker-client/pull/400 under "fix testStats()".

On Wed, Mar 30, 2016 at 10:43 AM, Flavin <notifications@github.com> wrote:

> Actually, I'll just do a PR for this myself. It won't be much work, and I
> think it will fix a test failure we've been seeing when building against
> versions 1.9 and 1.10.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/spotify/docker-client/issues/403#issuecomment-203466082>
>



-- 
David Xia
Software Engineer
dxia@spotify.com

**Comment by kingsmiler** [comment]
Thanks for reply.

But I'm sorry that I don't know how to translate "ethx" and it's properties to a concrete object, so...
