### ISSUE TITLE
Codecov numbers are probably incorrect 

### ISSUE THREAD

**Issue by mattnworb** [spotify/docker-client#406]
Each build in Travis submits a report to codecov. It's not clear what codecov does when it receives multiple reports for the same commit, but since some tests behave differently (or are skipped) in different builds, it seems like the numbers in the report would differ. 

If codecov takes the first or the last report as the definitive one, then it's essentially random as to which build generates the coverage number. 

Perhaps we should just run codecov for just one build configuration.

**Comment by mattnworb** [comment]
And perhaps disable it for circleci (or disable circle altogether).

**Comment by davidxia** [comment]
Sound like good ideas.

On Wednesday, March 30, 2016, Matt Brown <notifications@github.com> wrote:

> And perhaps disable it for circleci (or disable circle altogether).
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/spotify/docker-client/issues/406#issuecomment-203698235>
>


-- 
David Xia
Software Engineer
dxia@spotify.com

**Comment by mattnworb** [comment]
I removed the CircleCI webhook so this project doesn't build there anymore.

**Comment by davidxia** [comment]
@mattnworb Can we close this issue?
