### ISSUE TITLE
Code sample for accessing/managing a Docker Swarm cluster

### ISSUE THREAD

**Issue by AdityaGupta1** [spotify/docker-client#411]
I would really love a code sample for how to manage Docker Swarm clusters using this library. This would help me in my project, which is at https://github.com/AdityaGupta1/mobycraft/issues/21. 

This would help me decide whether to migrate to this library from the docker-java library.

**Comment by mattnworb** [comment]
This library doesn't have any support for Docker Swarm. From a quick glance it looks like it might have a similar API as the Docker Remote API that this client talks to, but we've never tried to use it for Swarm.
