### ISSUE TITLE
Migrate to clean JAX-RS 2.0 API and remove proprietary dependencies

### ISSUE THREAD

**Issue by grexe** [spotify/docker-client#413]
(related to #107 and #122)
The DockerClient still has dependencies on Jersey that make it really hard (nearly impossible) to use the docker client library in environments that depend on other REST implementations, e.g. Wildfly that is built on RESTeasy, checked sources for version 3.6.8 (fortunately it's all in one place,-):

> DefaultDockerClient.java:import org.glassfish.jersey.apache.connector.ApacheClientProperties;
> DefaultDockerClient.java:import org.glassfish.jersey.apache.connector.ApacheConnectorProvider;
> DefaultDockerClient.java:import org.glassfish.jersey.client.ClientConfig;
> DefaultDockerClient.java:import org.glassfish.jersey.internal.util.Base64;
> DefaultDockerClient.java:import org.glassfish.jersey.jackson.JacksonFeature;

Maven side dependencies on Jersey:

```
<dependency>
<groupId>org.glassfish.jersey.core</groupId>
<artifactId>jersey-client</artifactId>
<version>2.19</version>
</dependency>
<dependency>
<groupId>org.glassfish.jersey.connectors</groupId>
<artifactId>jersey-apache-connector</artifactId>
<version>2.19</version>
</dependency>
<dependency>
<groupId>org.glassfish.jersey.media</groupId>
<artifactId>jersey-media-json-jackson</artifactId>
<version>2.19</version>
</dependency>
```

Interestingly, the client works for some commands (like looking up, starting or stopping containers), but fails for others (like reading logs or executing commands), I guess only the failing commands use some Jersey specific calls.

Please think about fixing this in the library and only target standard JAX-RS 2 API, as this would be the most straight forward solution and should be really doable (I can support the effort...), as bending widlfly or EAR deployments is really a hassle I want to avoid.

related [Stackoverflow Thread](http://stackoverflow.com/a/28179303/160799)

**Comment by grexe** [comment]
To be more concrete, of course you need a minimal client implementation as Java does not provide a default implementation for JAX-RS 2, sadly.

I am currently evaluating:
* [UniREST](http://unirest.io/java.html) or
* [https://github.com/Netflix/feign](Feign)

My hope would be that this does not clash with server side RESTeasy...

**Comment by grexe** [comment]
Sadly it doesn't quite work like that, as you always need a specific implementation included in the project.
I will therefore create a fork with RESTeasy, but not use any provider specific extensions.
Then I'd only need to modify the POM and provide a variant for RESTeasy using a classifier, much like the shaded variant.

**Comment by mattnworb** [comment]
I have been thinking about attempting to change the library to use a non-Jersey library, since Jersey drags in so so many dependencies and causes headaches for people that use different versions (or at least add an option or alternate `DockerClient`). For example something like Apache HttpClient or OkHttp.

If you have an environment that uses some other Jersey implementation and docker-client used something non-Jersey, would that also alleviate the issue?

**Comment by grexe** [comment]
sorry missed the comment/update - I'm working on updating the [old commit](https://github.com/JWGmeligMeyling/docker-client/commit/a7f15377238fd255b31db73247e1a6c7e42eb8f8#commitcomment-9093093) by @JWGmeligMeyling, strip Jersey special code and replace it with REST-impl-agnostic code from Apache HttpClient.
When I'm done, I'll be happy to provide a pull request, but sadly had no time last week, will revisit this week as it's anyway needed for my work.

**Comment by jskjons** [comment]
I implemented a simple factory that made it easy to exclude the jersey dependencies in this PR: https://github.com/spotify/docker-client/pull/340. The alternate proposal to no longer use jersey would also work.

**Comment by grexe** [comment]
Thanks @jskjons this would also be a promising route to go.
I am actually pretty far with the clean-room JAX-RS 2.0 approach, but hit a snag:
There is no support for custom protocols like unix:// (used for socket connection) in the JAX-RS 2.0 client API, so for that you'd still need Jersey or RESTeasy, below for Jersey:
https://jersey.java.net/documentation/latest/client.html#d0e4844

Also, timeout parameters are not standardized and also implementation dependent.

Maybe we can merge our work @jskjons ?
I'll push my changes to my fork for review.

**Comment by grexe** [comment]
I've finally come back to this issue and was able to update your PR #340 @jskjons - many thanks for the excellent work!

Only had to fix some dependency issues with jersey pulling in an outdated hk2 lib and some conflicting libs in my own project, but the main issue that kept me busy was a conflict between docker-client's *httpclient* library and the one seen on Wildfly's classpath.
In the end, a clean manifest entry in the EAR plugin to define a module dependency to httpclient was all it needed, always easy in hindsight,-)

Last issue is that when pulling an image, it is downloaded completely and verified OK but then I still get an IOException, although I see some RESTeasy related fixes in the code of the PR.
@jskjons you said events are not working, but the ProgressStream should work also for RESTeasy?

```
java.io.IOException: Stream closed
        at java.io.BufferedInputStream.getBufIfOpen(BufferedInputStream.java:170)
        at java.io.BufferedInputStream.read1(BufferedInputStream.java:291)
        at java.io.BufferedInputStream.read(BufferedInputStream.java:345)
        at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._loadMore(UTF8StreamJsonParser.java:204)
        at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._skipWSOrEnd2(UTF8StreamJsonParser.java:2978)
        at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._skipWSOrEnd(UTF8StreamJsonParser.java:2973)
        at com.fasterxml.jackson.core.json.UTF8StreamJsonParser.nextToken(UTF8StreamJsonParser.java:731)
        at com.fasterxml.jackson.databind.MappingIterator.hasNextValue(MappingIterator.java:240)
        at com.spotify.docker.client.ProgressStream.hasNextMessage(ProgressStream.java:53)
```

Another open issue is related to Tests covering Docker swam, all related tests fail with this error using `ResteasyClientFactory`:
```
javax.ws.rs.NotAcceptableException: HTTP 406 Not Acceptable
This node is not a swarm manager. Use \"docker swarm init\" or \"docker swarm join\" to connect this node to swarm and try again.
```

**Comment by grexe** [comment]
created PR #691 based on my work on PR #340 - please have a look (already needs merging again...:-/ )
