### ISSUE TITLE
Volume API

### ISSUE THREAD

**Issue by sayarg** [spotify/docker-client#424]
## Description

Hey guys, do you have any plans to add support for volume API to create and manage docker volumes? i.e. https://docs.docker.com/engine/reference/api/docker_remote_api_v1.23/#2-4-volumes

**Comment by johnflavin** [comment]
I have a PR for `Volumes` almost ready to go. I have them implemented compatible with the API when they were introduced, 1.21, but I want to add the 1.22 and 1.23 changes before I submit.

**Comment by sayarg** [comment]
@johnflavin cool thanks!

**Comment by stephenc** [comment]
Any progress?

**Comment by johnflavin** [comment]
Sorry, I forgot all about this! I'll rebase my branch back up to master and open a PR. 

I'm not entirely sure what state it is in—i.e. whether it's fully compatible with all the latest API changes—but it's probably better to have something than nothing.
