### ISSUE TITLE
Resource exhaustion when using certificates 

### ISSUE THREAD

**Issue by sayarg** [spotify/docker-client#428]
## Description

DockerCertificates keeps creating new file streams and so when used in against a large number of hosts / recreated, causes process to run out of file descriptors

## How to reproduce

Create the docker client with cert setup in a long loop

## What do you expect

File descriptors should be closed

## What happened instead

They where not closed neither released

## Software:

- docker version: any
- docker-client version: 4.0.2

**Comment by mattnworb** [comment]
addressed in #429
