### ISSUE TITLE
Listing images from public docker registry

### ISSUE THREAD

**Issue by sburnwal** [spotify/docker-client#457]
## Description
I want to list all available images (all repositories) under my username on hub.docker.com

## How to reproduce
See the code sample.

## What do you expect
I want to see the list of images/repositories with their tags

## What happened instead
No list retrieved

## Software:
spotify docker-client
- docker version: 1.11
- docker-client version: 1.11

## Full backtrace

```text
I am trying to use the docker client spotify to list all the images
I have on docker public repository (hub.docker.com). This is the code
I am using. Auth status is correctly returned as 200 (not listing
actual user/pwd here) but when I try to list the images, the result
contains 0 (zero) images. Can you tell me what wrong I am doing here ?

AuthConfig authConfig = AuthConfig.builder()
                                    .email("xxx@yyy.com")
                                    .username("xxx")
                                    .password("xxx")

.serverAddress("https://index.docker.io/v1/")
                                    .build();
        // You can also set the AuthConfig for the DockerClient
instead of passing everytime you call pull()
        DockerClient authDocker =
DefaultDockerClient.fromEnv().authConfig(authConfig).build();
        int status = authDocker.auth(authConfig);
        log("Auth status is: " + status);

        final List<Image> images =
authDocker.listImages(ListImagesParam.allImages(true));
        log("Size from listImages() is : " + images.size());
        for(Image img : images) {
            log("Available image id=" + img.id() + " labels=" +
img.labels() + " tags=" + img.repoTags());

        }
```

In addition, can you also tell me how to use v2 APIs for hub.docker.com ?

**Comment by davidxia** [comment]
docker-client is used to interact with the local docker daemon and to push or pull images from docker registries. It doesn't support listing images in registries.

**Comment by mattnworb** [comment]
When you call `DockerClient.listImages()`, it is the equivalent of running `docker images` from the command line. The empty response is the docker daemon telling you that there are no images stored locally.
