### ISSUE TITLE
Search docker registry with tags

### ISSUE THREAD

**Issue by sburnwal** [spotify/docker-client#458]
## Description

I need to search docker registry and get the list of images/repos with tags
## How to reproduce

see the code sample

## What do you expect

Need to see the list of images and their tags
## What happened instead

No way to get the tags

## Software:

- docker version: 1.11.2
- docker-client version: 1.11.2

## Full backtrace

```text
		final List<ImageSearchResult> myImages = authDocker.searchImages("radiatejava");
		for(ImageSearchResult img : myImages) {
			log("Available image name=" + img.getName() + " descr=" + img.getDescription());
		}
```

How do I get the available tags ?

**Comment by johnflavin** [comment]
That is not something reported in the Docker Hub API. See [the documentation for the /images/search endpoint in the Docker Remote API](https://docs.docker.com/engine/reference/api/docker_remote_api_v1.23/#search-images), which is what the `docker-client` library is calling with the `searchImages()` method.

The only fields it returns when you search are `name`, `description`, `is_official`, `is_automated`, and `star_count`. I agree that tags would be useful, but that just isn't something docker gives you when you ask.

**Comment by sburnwal** [comment]
Thanks for the update. Is there any API that is equivalent of docker pull if I need to pull some image from registry server (like hub.docker.com) ?

**Comment by johnflavin** [comment]
Yes. There are a few `pull()` methods in `docker-client`. They call the [/images/create endpoint](https://docs.docker.com/engine/reference/api/docker_remote_api_v1.23/#create-an-image) in the Docker remote API.

**Comment by sburnwal** [comment]
Thank you for the prompt response, closing!
