### ISSUE TITLE
No need to deal with email in AuthConfig

### ISSUE THREAD

**Issue by elifarley** [spotify/docker-client#461]
## Description

No need to expose email property in AuthConfig.
Instead, always use the email `.@...`

At least that's the email I have in my ~/.docker/config.json and it works with the standard Docker client.
## How to reproduce

n/a
## What do you expect

No public mention of "email" in class "AuthConfig"
## What happened instead

You can see "public String email()" in the source code of AuthConfig
## Software:

n/a
## Full backtrace

n/a

``` text
n/a
```

**Comment by davidxia** [comment]
You're right. I've made email nullable in `RegistryAuth` here https://github.com/spotify/docker-client/pull/546. So one can just do 

```java
    // Push an image to a public repo on Docker Hub and check it succeeds
    final String dockerDirectory = Resources.getResource("dockerDirectory").getPath();
    final DockerClient client = DefaultDockerClient
        .fromEnv()
        .registryAuth(RegistryAuth.builder()
                        .username(HUB_AUTH_USERNAME)
                        .password(HUB_AUTH_PASSWORD)
                        .build())
        .build();

    client.build(Paths.get(dockerDirectory), HUB_PUBLIC_IMAGE);
    client.push(HUB_PUBLIC_IMAGE);
 ```
