### ISSUE TITLE
execCreate discards Warnings

### ISSUE THREAD

**Issue by johnflavin** [spotify/docker-client#463]
## Description

The method `DefaultDockerClient.execCreate(...)` calls out to the [/containers/{id}/exec API endpoint](https://docs.docker.com/engine/reference/api/docker_remote_api_v1.18/#exec-create). This endpoint returns an object like the `ContainerCreation` object:

    {
        "Id": "",
        "Warnings": [""]
    }

But instead of creating a `ContainerCreation` (or some bespoke `ExecCreation` object) to handle the whole response, `DefaultDockerClient.execCreate(...)` pulls out the `"Id"` field and returns only that value. This discards any warnings that may have been emitted by docker during the exec creation.

## What do you expect

Either,
Option 1. Change the `DefaultDockerClient.execCreate(...)` method. It should not return a `String` but instead return an `ExecCreation`. Or,
Option 2. Keep `DefaultDockerClient.execCreate(...)`'s return type as `String`, but edit it to call `log.warn(...)` to emit any warnings returned.

#### Option 1: Pro
* Usage is consistent with `createContainer(...)`, in that the two endpoints that return responses with the same structure are treated the same in `docker-client`.
* Warnings aren't just dropped, and can be dealt with explicitly.

#### Option 1: Con
* `ExecCreation` would have identical contents to a `ContainerCreation`. Maybe both aren't necessary? But if `execCreate` retuned a `ContainerCreation`, that would be confusing.
* Breaks the existing `DefaultDockerClient.execCreate(...)` API contract.

#### Option 2: Pro
* Doesn't change the `DefaultDockerClient.execCreate(...)` API.
* Warnings aren't just dropped.

#### Option 2: Con
* Inconsistent usage. `"Warnings"`lists are returned from lots of docker API endpoints. Why only log them here? Why don't we log them everywhere?
* Warnings aren't returned explicitly. Users either log at that level or they don't; they can't inspect the warnings in their code.

**Comment by mattnworb** [comment]
my vote would be for Option 1, so that the `execCreate` caller can examine any warnings programmatically rather than relying on the end user (who is probably different than the developer of the thing calling `execCreate`) to look at the log or even have log output set up to see the warnings. 

While it breaks that API contract of the Java interface, it is a pretty easy migration fix to make for callers.

**Comment by johnflavin** [comment]
I think that's the better option as well.

What about the object type of the response? Should I make an `ExecCreation`, even though it has identical contents to `ContainerCreation`? (I could make an abstract `Creation` class that has all the properties and methods, and `ContainerCreation` and `ExecCreation` would subclass `Creation` but be otherwise empty.) Or should `execCreate` just return a `ContainerCreation`?

**Comment by mattnworb** [comment]
I think it is fine to have an ExecCreation class whose structure happens to be identical to ContainerCreation; reusing the same class for both would seem to create an assumption that the responses from the Docker Remote API will always stay the same.

**Comment by johnflavin** [comment]
Fixed in #427.
