### ISSUE TITLE
Add support for pid namepsace

### ISSUE THREAD

**Issue by sayarg** [spotify/docker-client#474]
The docker http api supports specifying pid namespace for container creation. This was not documented until now, and following this PR merge it is now available in the docker doc.

https://github.com/docker/docker/issues/24517

Any plans to adding the same, or any objections to the idea?

**Comment by johnflavin** [comment]
:+1: on the idea. I could include this in my API 1.18 omnibus PR (#427) or you could do a separate PR if you prefer.

**Comment by sayarg** [comment]
if you don't mind adding to your PR that's be great!

**Comment by johnflavin** [comment]
Ok, I've added it.

**Comment by sayarg** [comment]
thanks vm @johnflavin

**Comment by johnflavin** [comment]
#427 has been merged, which adds `HostConfig.pidMode`. This issue can be closed.
