### ISSUE TITLE
Swarm integration into native docker!

### ISSUE THREAD

**Issue by abdshah94** [spotify/docker-client#480]
As we all know that docker is integrating swarm in the native docker engine in it's latest version. Does that mean Spotify will support swarm specific APIs? cheers!

**Comment by zepouet** [comment]
Hello,

Which specific API do you need ?

Nicolas

**Comment by mattnworb** [comment]
We have no plans to add more API methods ourselves to docker-client for swarm or otherwise, but we are happy to review and accept PRs that add support for new APIs.
