### ISSUE TITLE
Add support oom-kill-disable option suggestion

### ISSUE THREAD

**Issue by jazzhuang** [spotify/docker-client#481]
## Description

$docker -v
Docker version 1.9.1, build 827708e BUILDTIME:2016-04-11 14:17:18
$docker run --help | grep oom
  --oom-kill-disable=false        Disable OOM Killer

I found there is no option for setting it in HostConfig.java.

Does I miss something?

**Comment by jazzhuang** [comment]
This client has support it yet, ref: https://github.com/docker-java/docker-java/blob/ca6a7f307ce85b1b33713ca38eb44ae1754936f2/src/main/java/com/github/dockerjava/api/model/HostConfig.java#L139

**Comment by davidxia** [comment]
Closed by #498
