### ISSUE TITLE
Maven central plugin not correctly updated

### ISSUE THREAD

**Issue by zepouet** [spotify/docker-client#482]
## Description

The mavencentral is not updated to use 5.x release so the LATEST/RELEASE targets not the latest source code. For example, if I use Docker 1.12, I could have serious API bug (archive / copy for example). I don't know if problem is into mavencentral or here about the update list release.

## How to reproduce

Try to use autocompletion in IDEA or ECLIPSE. I add a screenshot as piece.

## What do you expect

To have in pom.xml the autocompletion for Docker Client release

```
 <!-- https://mvnrepository.com/artifact/com.spotify/docker-client -->
<dependency>
    <groupId>com.spotify</groupId>
    <artifactId>docker-client</artifactId>
    <version>5.0.2</version>
</dependency>
```

## What happened instead

See the attached file.

## Software:

- docker version: 1.12
- docker-api version: 1.24

Thanks you very much !
<img width="531" alt="capture d ecran 2016-08-06 a 15 04 03" src="https://cloud.githubusercontent.com/assets/231269/17456909/629549f2-5be7-11e6-99c1-7d64689ff6d1.png">

**Comment by mattnworb** [comment]
Versions 5.0.0, 5.0.1, and 5.0.2 are in Maven central as you can [see here](http://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22com.spotify%22%20AND%20a%3A%22docker-client%22)

I could be wrong but I think that IntelliJ only shows you suggestions based on an index it has downloaded from Maven central, maybe yours is out of date?
