### ISSUE TITLE
Building an image from Dockerfile seems to ignore authConfig

### ISSUE THREAD

**Issue by dobrowolskij** [spotify/docker-client#485]
I try to build an image using a base image from a private repository.
AuthConfig was provided to docker client and it seems to work correctly (requests contain authentication information as expected), for example, for pull operation.
However an attempt to build an image from Dockerfile results in errors since client makes anonymous  requests to repo. 
The Dockerfile itself is correct since all work as expected when executing 'docker build .' from console.
- docker version: 1.11
- docker-client version: 5.0.2

Do I miss something? Is the mentioned scenario possible to accomplish with docker client?
Thanks

**Comment by mattnworb** [comment]
Can you provide an example of the code you are using to build a container that results in the anonymous requests to the registry?

**Comment by mattnworb** [comment]
I am not sure what the original problem was but I believe the authentication revamp since 8.6.0 improves this situation
