### ISSUE TITLE
Unable to start a container properly with docker-client.

### ISSUE THREAD

**Issue by neddogg** [spotify/docker-client#506]
## I'm looking for a mean to do a docker **build tagOfMyImage .** then **docker run tagOfMyImage** with docker-client.

[Add feature/bug description here]

## How to reproduce

    final DockerClient docker = DefaultDockerClient.fromEnv().build();
    //Build image from a Dockerfile
    final AtomicReference<String> imageIdFromMessage = new AtomicReference<>();
    String dockerDirectory = new String("some/path/to/my/dockerfile");
    final String returnedImageId = docker.build(
    Paths.get(dockerDirectory), "new4", new ProgressHandler() {
         @Override
         public void progress(ProgressMessage message) throws DockerException {
	    final String imageId = message.buildImageId();
	         if (imageId != null) {
	              imageIdFromMessage.set(imageId);
	          }
	 }
     });
     // Bind container ports to host ports
     final String[] ports = { "80", "21" };
     final Map<String, List<PortBinding>> portBindings = new HashMap<String, List<PortBinding>>();
     for (String port : ports) {
	List<PortBinding> hostPorts = new ArrayList<PortBinding>();
	hostPorts.add(PortBinding.of("0.0.0.0", port));
	portBindings.put(port, hostPorts);
     }
    // Create container with exposed ports
    // Bind container port 443 to an automatically allocated available host
    // port.
    List<PortBinding> randomPort = new ArrayList<PortBinding>();
    randomPort.add(PortBinding.randomPort("0.0.0.0"));
    portBindings.put("443", randomPort);
    final HostConfig hostConfig = HostConfig.builder().portBindings(portBindings).build();
    final ContainerConfig containerConfig = ContainerConfig.builder().hostConfig(hostConfig)
	.image("streamly/logstash:v1").exposedPorts(ports)
	.cmd("touch", "/latest").build();
    final ContainerCreation creation = docker.createContainer(containerConfig);
    docker.startContainer(creation.id());

## What do you expect

[ docker ps -a
  outputs
  CONTAINER ID        IMAGE                  COMMAND                  CREATED             STATUS                       PORTS                              NAMES
       a651ceb71550        tagOfMyImage   "/docker-entrypoint.s"   17 seconds       Up 17 seconds]

## What happened instead

[ docker ps -a
  outputs
  CONTAINER ID        IMAGE                  COMMAND                  CREATED             STATUS                       PORTS                              NAMES
       a651ceb71550        tagOfMyImage   "/docker-entrypoint.s"   17 seconds       Exited (0) 17 seconds ago]

## Software:

- `docker version`: [Client:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 05:22:43 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 05:22:43 2016
 OS/Arch:      linux/amd64]
- Spotify's docker-client version: [<dependency>
			<groupId>com.spotify</groupId>
			<artifactId>docker-client</artifactId>
			<version>5.0.2</version>
		</dependency>]

## Full backtrace

```text
[Not exception]
```

## Additional information

[When I do
docker build tagOfMyImage .
docker run tagOfMyImage]

## Output

[ docker ps -a
  outputs
  CONTAINER ID        IMAGE                  COMMAND                  CREATED             STATUS                       PORTS                              NAMES
       a651ceb71550        tagOfMyImage   "/docker-entrypoint.s"   17 seconds       Up 17 seconds]

Further this is the contain of my docker file

    FROM logstash
    COPY logstash.conf /etc/logstash/conf.d/
    CMD ["-f", "/etc/logstash/conf.d/logstash.conf"]

and logstash.conf contains

            input {  
               kafka {    
                        topic_id => 'topicName'    
                        zk_connect => 'localhost:2181'    
                        codec => "json"
               }
            }
            output {    
               elasticsearch {        
                         manage_template => false        
                         hosts => ["localhost:9200"]        
               } 
            }

Note this configuration is just for testing purpose. Doesn't mean if I have not install both elasticsearch and kafka in the container.

So I'm wondering if I doing it the right way!!!!
Any clue please?

**Comment by johnflavin** [comment]
You instructed docker to have the container start up and execute the command `touch /latest`. That means the container will execute your command and exit. It won't stay alive any longer than you tell it to.

Indeed, when you did a `docker ps`, it told you that the container started up and exited with status 0, which means there were no errors. It did exactly what you asked.

**Comment by neddogg** [comment]
Thanks @johnflavin for the quick reply.

How can I get my container alive for a long period or even forever?

**Comment by neddogg** [comment]
Oh my bad I could get it working by using **cmd("sh", "-c", "while :; do sleep 1; done")** instead of **cmd("touch", "/latest")**. Thanks @johnflavin It really does what I asked :)
