### ISSUE TITLE
Support nocopy bind option

### ISSUE THREAD

**Issue by dmandalidis** [spotify/docker-client#510]
nocopy options in binds was introduced in 1.24 API version. However, implementation allows to specify it in Bind#to property but I don't know if this was done on purpose....otherwise I could send a PR

**Comment by johnflavin** [comment]
Can you quote from and/or give a link to the docker API documentation for this option?

**Comment by dmandalidis** [comment]
First time it appears on https://docs.docker.com/engine/reference/api/docker_remote_api_v1.24/ (search for 'nocopy') but it was really introduced at 1.23. (https://docs.docker.com/engine/reference/api/docker_remote_api/#/v1-23-api-changes)

> POST /containers/create now allows specifying nocopy for named volumes, which disables automatic copying from the container path to the volume.
>

**Comment by johnflavin** [comment]
Ok, I see that it was listed in the API changes for v1.23. However, I can't find "nocopy" in the [API 1.23](https://github.com/docker/docker/blob/master/docs/reference/api/docker_remote_api_v1.23.md) docs at all, and the only mention in the [1.24 docs](https://github.com/docker/docker/blob/master/docs/reference/api/docker_remote_api_v1.24.md#create-a-service) is in reference to creating a swarm, not creating a container. (Which is not to say that we don't want that swarm option. But it may already be included in #499. Not sure.)

I think this is a very doable PR. But I would feel more comfortable with it if you first opened an issue with docker/docker saying their API docs for 1.23, 1.24, and 1.25 should be updated to list this option. That way we can be sure we're doing the correct thing on our end.

**Comment by dmandalidis** [comment]
You 're right it is only mentionned in the API changelog for 1.23, while in the website it is mentioned as a general mode for volume creating (compared to the respective .md). However, I 've already submitted a PR at docker-java/docker-java with a passing integration tests in 1.23 API (https://github.com/docker-java/docker-java/pull/696) while I 'm also using it in real life (through abusing the Bind#to of yours and through shell :) ). Here's the docker issue I 've just opened : https://github.com/docker/docker/issues/27029

**Comment by johnflavin** [comment]
Cool, thanks for opening the docker ticket. If you’re already familiar enough with the nocopy option in the API, then feel free to get started on a PR for it. I wouldn’t want to do the PR myself yet, because I’m not 100% certain how the option is implemented. Nor would I want to merge it until docker updates the docs (but I can’t merge anything here anyway, so that point is moot). But none of that precludes you from working on it now.

**Comment by dmandalidis** [comment]
Sure, I 'll give it a try, I have one question though. One cannot use this option with a non-named volume, for example you can say :

`docker run -d -v anamedvolume:/htdocs:nocopy foo` but you cannot say :

`docker run -d -v /anamed/volume:/htdocs:nocopy foo`

Do you believe that this is docker-client responsibility or do you let the actual docker implementation to throw an error? (I would vote for the first option as I saw that there is no special check in HostConfig.Bind#to property)

**Comment by johnflavin** [comment]
I would say this is our responsibility to check. We should be able to figure out how to only allow the `nocopy` option to be set if a named volume is the source of the bind. You may be required to re-work the existing `HostConfig.Bind` methods to make this work in a reasonable way, but that should be ok.

Note that in the examples you gave, the named volume would not be provided to `HostConfig.Bind#to` but `HostConfig.Bind#from`. See [the discussion in the comments of #487](https://github.com/spotify/docker-client/pull/487#issuecomment-249205841) for more.

The easiest way to do this would be to allow users to set `nocopy` whether or not they can use it. Then, when the `Bind` object is converted to its string representation in `HostConfig.Bind#toString`, only actually set the `:nocopy` option on the bind string `if (nocopy && from.startsWith("/"))`. Maybe log a waring in the other case, where the user has set `nocopy` and they did not specify a named volume as `from`.

**Comment by dmandalidis** [comment]
Oh sorry, I 've misunderstood the manual page, nocopy is supported in both volume types but defaults to true for named volumed and false on bind mount.

**Comment by davidxia** [comment]
closed by #510
