### ISSUE TITLE
Network attachment for docker service create

### ISSUE THREAD

**Issue by dmandalidis** [spotify/docker-client#520]
This is more a question rather a bug report. I 've just updated my dependencies to use the newly introduced docker swarm support. I 'm struggling to find out how I specify a network name for service create, I think it's impossible with NetworkAttachmentConfig. Moreover, I think NetworkAttachment for TaskSpec is not needed.

Can you please give me some insight?

**Comment by johnflavin** [comment]
(Preface: I’ve never used a docker swarm myself, so I’m not familiar with the commands at all. Someone else may be able to answer you right away, but I certainly cannot. Hopefully that explains why I am definitely not about to address your question directly.)

You could just check in the docker remote API docs how to do this. If they’ve explained things in a way you understand, and if `docker-client` has correctly implemented that part of the API, then you’re ready to go. If either of those things is not true, then there would be an opportunity for improvement.

**Comment by dmandalidis** [comment]
The docker API v1.24 clearly states that for service creation, there is a property called 'Networks' through which one could set the network name to be used by the new service. In `docker-client`, there is indeed a `withNetworks` method in `ServiceSpec`, but the `NetworkAttachmentConfig` does not provide any setting functionality, while it is incorrectly serialized to something which is not a string array. (More details at https://docs.docker.com/engine/reference/api/docker_remote_api_v1.24/#/create-a-service)

Additionally, there is another `withNetworks` method in TaskSpec (with the same setting constraints) while, as far as I understand, there is no such field in TaskSpec in the remote API.

**Comment by dmandalidis** [comment]
Ok I think I got it now...NetworkAttachmentConfig comes from NetworkAttachment used for https://docs.docker.com/engine/reference/api/docker_remote_api_v1.24/#/inspect-a-task.

Provided that I 'm not missing something, I 'll send a PR correcting the service create part.

**Comment by dmandalidis** [comment]
I 've actually missed something, Docker documentation at https://docs.docker.com/engine/reference/api/docker_remote_api_v1.24/#/create-a-service is (at least) not clear for this. Code at master branch is correct apart from the fact that there is no way to construct the NetworkAttachmentConfig object
