### ISSUE TITLE
"--ip" attribuate?

### ISSUE THREAD

**Issue by flexdeviser** [spotify/docker-client#525]
Could you tell me how to set ipAddress for a container?

just like "docker run -d --name **\* --net *\* **--ip 10.28.5.10** nginx"

**Comment by mattnworb** [comment]
The API within this library for creating a container closely mirrors what the [Docker Remote API expects](https://docs.docker.com/engine/reference/api/docker_remote_api_v1.24/#/create-a-container), so if you can find how to specify the networking mode and ip in the `POST /containers/create` call, there should be a match in the Java classes.
