### ISSUE TITLE
LogStream throws EOFException if the stream contains less than 8 bytes

### ISSUE THREAD

**Issue by bayanr** [spotify/docker-client#530]
## Description

When trying to read the output of a command launched through `DockerClient.execStart()`, an `EOFException` is thrown if the output of the command is less than 8 characters using `v6.0.0:shaded`

## How to reproduce
The following unit test demonstrates the problem.

``` java
@Test
public void readStdoutOfCommandWithOutputLessThan8Chars() throws DockerCertificateException, DockerException, InterruptedException, IOException {
  DockerClient client = createDockerClient();
  String simpleEcho = client.execCreate("container_id", new String[] { "echo" ,"Hello" }, DockerClient.ExecCreateParam.attachStdout(true), DockerClient.ExecCreateParam.attachStderr(true)).id();

  LogStream logStream = client.execStart(simpleEcho, DockerClient.ExecStartParameter.TTY);
  ByteArrayOutputStream stdOut = new ByteArrayOutputStream();
  ByteArrayOutputStream stdErr = new ByteArrayOutputStream();

  logStream.attach(stdOut, stdErr);
  System.out.println("======== OUTPUT =======");
  System.out.println(stdOut);
}
```

Produces the following trace:

```
java.lang.RuntimeException: java.io.EOFException
    at com.google.common.base.Throwables.propagate(Throwables.java:160)
    at com.spotify.docker.client.LogStream.computeNext(LogStream.java:61)
    at com.spotify.docker.client.LogStream.computeNext(LogStream.java:35)
    at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:143)
    at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:138)
    at com.spotify.docker.client.LogStream.attach(LogStream.java:142)
    at Test.readStdoutOfCommandWithOutputLessThan8Chars(Test.java:61)
    // JUnit noise omitted
Caused by: java.io.EOFException
    at com.spotify.docker.client.LogReader.nextMessage(LogReader.java:59)
    at com.spotify.docker.client.LogStream.computeNext(LogStream.java:59)
    ... 31 more
```

Whereas the following test

``` java
@Test
public void readStdoutOfCommandWithOutputMoreThan8Chars() throws DockerCertificateException, DockerException, InterruptedException, IOException {
  DockerClient client = createDockerClient();
  String simpleEcho = client.execCreate("container_id", new String[] { "echo" ,"HelloWorld" }, DockerClient.ExecCreateParam.attachStdout(true), DockerClient.ExecCreateParam.attachStderr(true)).id();

  LogStream logStream = client.execStart(simpleEcho, DockerClient.ExecStartParameter.TTY);
  ByteArrayOutputStream stdOut = new ByteArrayOutputStream();
  ByteArrayOutputStream stdErr = new ByteArrayOutputStream();

  logStream.attach(stdOut, stdErr);
  System.out.println("======== OUTPUT =======");
  System.out.println(stdOut);
}
```

Prints out the expected output:

```
//Misc logs
======== OUTPUT =======
HelloWorld
```
## What do you expect

Command output should be read.

## What happened instead

EOFException was thrown

## Software:

- `docker version`:  1.12.2
- Spotify's docker-client version: v6.0.0:shaded

**Comment by bayanr** [comment]
Also reproduced on v6.1.0:shaded.

**Comment by mattnworb** [comment]
thanks for the bug report @bayanr. I was able to reproduce this on master with docker v.1.12.1.

**Comment by mattnworb** [comment]
@bayanr can you add details about how the container that you are exec-ing the `echo` command inside is created? Is the `tty` setting set to true in the `createContainer(..)` call?

**Comment by mattnworb** [comment]
I think that what might be happening is that, when attaching to a container with a tty, the output from [the attach Remote API call](https://docs.docker.com/engine/reference/api/docker_remote_api_v1.24/#/attach-to-a-container) the output `stream is the raw data from the process PTY`.

com.spotify.docker.client.LogReader is always expecting the second type of output from this API call, for non-tty containers:

> When the TTY is disabled, then the stream is multiplexed to separate stdout and stderr.
>
> The format is a Header and a Payload (frame).
>
> ...

**Comment by bayanr** [comment]
Hi @mattnworb sorry for the late response. This is not a setting I am modifying, so whatever the default is I guess. Here is a unit test which is launching a container with a configuration similar to what I have as well as performing the exec.

```Java
@Test
public void readStdoutOfCommandWithOutputLessThan8Chars() throws DockerCertificateException, DockerException, InterruptedException, IOException {
  DockerClient client = createDockerClient();

  ContainerConfig config = ContainerConfig.builder()
    .image("httpd")
    .env("SETTING_1=VALUE_1")
    .build();

  ContainerCreation container = client.createContainer(config);
  client.startContainer(container.id());
  Thread.sleep(2000);
  String simpleEcho = client.execCreate(container.id(), new String[] { "echo" ,"Hello" }, DockerClient.ExecCreateParam.attachStdout(true), DockerClient.ExecCreateParam.attachStderr(true)).id();

  LogStream logStream = client.execStart(simpleEcho, DockerClient.ExecStartParameter.TTY);
  ByteArrayOutputStream stdOut = new ByteArrayOutputStream();
  ByteArrayOutputStream stdErr = new ByteArrayOutputStream();

  logStream.attach(stdOut, stdErr);
  System.out.println("======== OUTPUT =======");
  System.out.println(stdOut);
}
```

I tried explicitly setting TTY to true and the exception still happens.

**Comment by bayanr** [comment]
Apparently the multiplexed stream never happens. Setting TTY to both true and false yields the same exception which is quite weird.

**Comment by johnflavin** [comment]
Can you try just doing either stdout or stderr but not both?

**Comment by bayanr** [comment]
I tried with stdout only, same exception is thrown.

**Comment by mattnworb** [comment]
As far as I can tell the stream returned by `execStart` is multiplexed [when you do not set the `detach` or `tty` parameters](https://docs.docker.com/engine/reference/api/docker_remote_api_v1.24/#/exec-start).

This test passes successfully:

```java
  @Test
  public void readStdoutOfCommandWithOutputLessThan8Chars()
      throws DockerCertificateException, DockerException, InterruptedException, IOException {

    DockerClient client = DefaultDockerClient.fromEnv().build();

    final ContainerConfig containerConfig = ContainerConfig.builder()
        .image("spotify/alpine:latest")
        .cmd("sh", "-c", "while true; do date; sleep 1; done")
        .build();

    final ContainerCreation creation = client.createContainer(containerConfig);

    final String containerId = creation.id();
    client.startContainer(containerId);

    log.info("started container {}", containerId);

    assertTrue("Container " + containerId + " is not running",
        client.inspectContainer(containerId).state().running());

    final ExecCreation execCreation = client.execCreate(
        containerId,
        new String[]{"echo", "Hello"},
        ExecCreateParam.attachStdout(),
        ExecCreateParam.attachStderr());
    log.info("exec created: {}", execCreation);

    // ** I removed the DockerClient.ExecStartParameter.TTY param here ** /
    LogStream logStream = client.execStart(execCreation.id());

    ByteArrayOutputStream stdOut = new ByteArrayOutputStream();
    ByteArrayOutputStream stdErr = new ByteArrayOutputStream();

    logStream.attach(stdOut, stdErr);
    assertThat(stdOut.toString(), is("Hello\n"));
  }
```

It does seem like a bug though that the LogStream instance returned by `execStart` or `attachContainer` is unaware that there are some cases where the stream will not be multiplexed. This could definitely be improved.

**Comment by rgrunber** [comment]
This is definitely a bug at https://github.com/spotify/docker-client/blob/e385b577a617734e4fd87307822924b855a2d46a/src/main/java/com/spotify/docker/client/LogReader.java#L59

As mentioned before, It seems the logic for determining whether the stream is a TTY-enabled or not depends on reading the first 8 bytes, but if there's fewer, then we're clearly in the TTY-enabled case because the stream definitely doesn't have the correct form (it's a raw stream). Instead of throwing the exception (when n != 8), we should go into the code path that handles raw streams (in the else).

This is probably code that I didn't touch when I added support for both types of streams (spotify/docker-client@824af85) and went undetected (likely because most raw streams that truly contain TTY formatting codes end up being larger than 8 bytes)

**Comment by mattnworb** [comment]
thanks to @rgrunber for addressing this in #551
