### ISSUE TITLE
Readme : Please update readme with latest release for maven dependency

### ISSUE THREAD

**Issue by hbutalia** [spotify/docker-client#539]
## Description

Please update readme with latest release for maven dependency.

## How to reproduce

Please refer readme.

## What do you expect

[Describe what do you expect to happen]

## What happened instead

[Describe the actual results]

## Software:

- `docker version`: [Add the output of `docker version` here, both client and server]
- Spotify's docker-client version: [Add docker-client version here]

## Full backtrace

```text
[Paste full backtrace here]
```

**Comment by mattnworb** [comment]
You can always find the latest release at https://github.com/spotify/docker-client/releases
