### ISSUE TITLE
Support swarm nodes infomation

### ISSUE THREAD

**Issue by Castill** [spotify/docker-client#543]
## Description

Support Remote API 1.24 node api or Swarm property in info api

```
/nodes
/info
```

## What do you expect

Get swarm node information so that can get each node status.

## Software:

- `docker version`: 1.12.3
- Spotify's docker-client version: 6.1.0

**Comment by timchenxiaoyu** [comment]
This is very helpful for me。but autovalue in my eclipse error

**Comment by davidxia** [comment]
`/nodes` added in https://github.com/spotify/docker-client/pull/712

`/info` also already exists.
