### ISSUE TITLE
Hostconfig : Memory and Cpu related options like memoryswapiness and cpuPeriod,cpu-percent

### ISSUE THREAD

**Issue by hbutalia** [spotify/docker-client#565]
## Description

[Add feature]

Please add support for cpu related attributes like cpuPeriod,cpu-percent and also memory related attributes memoryswapiness 

## How to reproduce
Please add support in hostconfig for the below mentioned attributes.

      --cpu-percent int             CPU percent (Windows only)
      --cpu-period int              Limit CPU CFS (Completely Fair Scheduler) period
      --cpuset-mems string          MEMs in which to allow execution (0-3, 0,1)

        --memory-swappiness int       Tune container memory swappiness (0 to 100) (default -1)

[Describe what do you expect to happen]

## What happened instead

[Describe the actual results]

## Software:

- `docker version`: [Add the output of `docker version` here, both client and server]
- Spotify's docker-client version: [Add docker-client version here]

## Full backtrace

```text
[Paste full backtrace here]
```

**Comment by davidxia** [comment]
Everything is supported now except for `--cpu-percent`. I don't have a windows machine, and travis only supports linux and mac. I guess we are open to PRs for this remaining option.

**Comment by hbutalia** [comment]
Hi David,

Thank you for considering the request.  You can provide --cpu-percent option using it or not will dependent on the user.

Please let me know in which release will this be available.

Regards,
HB

**Comment by davidxia** [comment]
I'm not sure I understand your comment, but it'll be in the most recent
release.

**Comment by johnflavin** [comment]
If I may, I think the comment was essentially, "Whether or not you can test the `cpu-percent` option, please provide it anyway. _Caveat emptor_."

**Comment by davidxia** [comment]
Hm OK. I'll leave that as a PR for someone else who has a windows machine to develop and test on. :)

**Comment by davidxia** [comment]
I've created a new issue here for it. https://github.com/spotify/docker-client/issues/573
