### ISSUE TITLE
Authenication failure when .docker/config.json has entry using identityToken

### ISSUE THREAD

**Issue by scheerer** [spotify/docker-client#580]
## Description

Authenication failure when .docker/config.json has entry using identityToken.

## How to reproduce

1) docker login to a repository that returns an identityToken (note: the domain/org/project/tag are all fictitious in these examples)

Example of config.json
```
{
  "auths": {
    "docker.customdomain.com": {
      "auth": "ZG9ja2VybWFuOg==",
      "email": "dockerman@hub.com",
      "identityToken": "52ce5fd5-eb60-42bf-931f-5eeec128211a"
    }
  }
}
```

2) Specify a baseImage that is not currently cached on the local machine and needs to be pulled. Eg. `<baseImage>docker.customdomain.com/my_organization/some_project:some_tag</baseImage>`
3) `mvn clean package docker:build`
## FAILURE occurs

**Note**: Manually pulling with docker via: `docker pull docker.customdomain.com/my_organization/some_project:some_tag` will work fine

## What do you expect

I should be able to pull and build FROM an image on private docker repository using the identityToken from config.json

## What happened instead

```
[INFO] --- docker-maven-plugin:0.4.13:build (default-cli) @ user-service ---
[WARNING] Failed to parse auth string for docker.nextgearcapital.com
[INFO] Copying /Users/russell.scheerer/workspaces/user-service/target/user-service.jar -> /Users/russell.scheerer/workspaces/user-service/target/docker/app/user-service.jar
[INFO] Building image docker.customdomain.com/my_organization/user-service
Step 1 : FROM docker.customdomain.com/my_organization/some_project:some_tag
Pulling repository docker.customdomain.com/my_organization/some_project:some_tag
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 14.799 s
[INFO] Finished at: 2017-01-05T15:54:21-05:00
[INFO] Final Memory: 71M/393M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.spotify:docker-maven-plugin:0.4.13:build (default-cli) on project user-service: Exception caught: Error: image my_organization/some_project:some_tag not found -> [Help 1]
```

## Software:

- `docker version`:  
```$ docker version
Client:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:        Wed Oct 26 23:26:11 2016
 OS/Arch:      darwin/amd64

Server:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:        Wed Oct 26 23:26:11 2016
 OS/Arch:      linux/amd64```
- Spotify's docker-maven-plugin version: 0.4.13 (not sure which version of docker-client it uses)

**Comment by davidxia** [comment]
If I'm not mistaken, this project doesn't support tokens yet. PRs are welcome though :)

**Comment by scheerer** [comment]
Thank you. I started working on the codebase, but I myself am struggling to find the appropriate Docker information to know exactly what to send. :( I will continue looking and post if I find anything. Also, Adding the appropriate test to PushPullIT might be a little tricky to get setup someplace.

**Comment by scheerer** [comment]
I was just pointed at this PR for a Python based library... Hopefully I can figure it out with this. https://github.com/docker/docker-py/pull/1210/files

**Comment by mrasband** [comment]
Yeah, it looks like a combo of:

```python
if 'identitytoken' in entry:
    log.debug('Found an IdentityToken entry for registry {0}'.format(
        registry
    ))
    conf[registry] = {
        'IdentityToken': entry['identitytoken']
    }
    continue # Other values are irrelevant if we have a token, skip.
```

and 

```python
def encode_header(auth):
    auth_json = json.dumps(auth).encode('ascii')
    return base64.urlsafe_b64encode(auth_json)
```

[1](https://github.com/docker/docker-py/blob/c02493cf18bbb0b28bce7934b45a042147671be2/docker/auth.py#L182)
[2](https://github.com/docker/docker-py/blob/c02493cf18bbb0b28bce7934b45a042147671be2/docker/auth.py#L145)

**Comment by scheerer** [comment]
I currently have it working with a JUnit test using my personal creds and our private repository... I however need to find a more suitable place to run the integration tests against. :(
