### ISSUE TITLE
DefaultDockerClient.connectToNetwork(...) does not allow to set IP address for container

### ISSUE THREAD

**Issue by llopat** [spotify/docker-client#606]
## Description

The connectToNetwork client method does not support any other parameters apart from containerId and networkId. 
When using the Docker CLI to connect a container to a network it is possible to set few additional properties and according to the Engine API v1.24 documentation at least setting IPv4 and/or IPv6 address should be possible.

## Software:

- `docker version`: 1.12.3
- Spotify's docker-client version: 7.0.2

**Comment by davidxia** [comment]
@llopat You can use [`DockerClient. connectToNetwork(String networkId, NetworkConnection networkConnection)`](https://github.com/spotify/docker-client/blob/master/src/main/java/com/spotify/docker/client/DockerClient.java#L1514)
