### ISSUE TITLE
Allow custom signal when "killing" container

### ISSUE THREAD

**Issue by bentmann** [spotify/docker-client#614]
The `POST /containers/(id or name)/kill` endpoint long supports a `signal` query parameter to control what signal is send to the container. It would be nice if that query parameter was exposed in the `DockerClient.killContainer()` API somehow.

Of particular interest/value is the ability to send SIGQUIT to the container which triggers a thread dump from Java processes.

**Comment by johnflavin** [comment]
You're right that this option has been around for a long time. I found it in the docker docs back to API v1.18. I did a big PR a while ago to ensure 1.18 compatibility, but I must have just missed this parameter. 

This should be easy to add. You could do it yourself, if you want to give it a try.
