### ISSUE TITLE
Update container api

### ISSUE THREAD

**Issue by nesnesrou2810** [spotify/docker-client#621]
Im working on update container Memory and cpu 
any help please

**Comment by johnflavin** [comment]
Can you give any more detail about what you are trying to do, and what you need help with?

**Comment by nesnesrou2810** [comment]
i'm trying to find the imlentaion of update container for the docker API "POST /containers/(id or name)/update", but it sems  its not implmented yrt or just can't find how to do it

**Comment by johnflavin** [comment]
First build a `HostConfig` object with the properties you want, then call `DockerClient.updateContainer(String containerId, HostConfig config)`.
