### ISSUE TITLE
Filters for events containing spaces never match

### ISSUE THREAD

**Issue by XanderXAJ** [spotify/docker-client#626]
## Description

Asking Docker to filter for events that contain a space, such as `health_status: healthy`, will never match.

This works using the Docker CLI or Docker API directly.

## How to reproduce

```java
EventStream eventStream = docker.events(
    EventParam.event("health_status: healthy")
);
eventStream.hasNext(); // Will never fire
```

This minimal Dockerfile will generate 1 `health_status: healthy` message after 3 seconds; re-run it to generate more:

```
FROM busybox:1.26

HEALTHCHECK --interval=1s --timeout=1s --retries=3 CMD true

CMD ["sleep", "10"]
```

## What do you expect

Events with action "health_status: healthy" will match and be returned by `next()`.

## What happened instead

Events are not matched.

## Software:

```
$ docker version
Client:
 Version:      1.13.1
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   092cba3
 Built:        Wed Feb  8 08:47:51 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      1.13.1
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   092cba3
 Built:        Wed Feb  8 08:47:51 2017
 OS/Arch:      linux/amd64
 Experimental: true
```

- Spotify's docker-client version: 7.0.2

---

Briefly stepping through the code, it looks like the filter arguments are being double URL encoded before being sent out:

```
Spotify Docker Client sends:
/events?filters=%7B%22event%22%3A%5B%22health_status%3A%2Bhealthy%22%5D%7D
/events?filters={"event":["health_status:+healthy"]}

This works with the API:
/events?filters=%7B%22event%22%3A%5B%22health_status%3A%20healthy%22%5D%7D
/events?filters={"event":["health_status: healthy"]}

This also works:
/events?filters=%7B%22event%22%3A%5B%22health_status%3A+healthy%22%5D%7D
/events?filters={"event":["health_status: healthy"]}
```

**Comment by johnflavin** [comment]
Yes, that does look like a bug. But it doesn't look to me like *everything* in the filter arguments is getting double encoded, just the space. `" " -> + -> %2B`

If everything were being double encoded, we would see `%25` everywhere, as `character -> %XX -> %25XX`.

**Comment by mattnworb** [comment]
I might be understanding the Jersey code wrong, but I think that when DefaultDockerClient calls [`resource.queryParam(urlEncode(param.name()), urlEncode(param.value()))`](https://github.com/spotify/docker-client/blob/v7.0.2/src/main/java/com/spotify/docker/client/DefaultDockerClient.java#L1427), the queryParam method in WebTarget will already take care of some level of encoding for you.

The chain looks like 

- [`JerseyWebTarget.queryParam(name, value)`](https://github.com/jersey/jersey/blob/2.22/core-client/src/main/java/org/glassfish/jersey/client/JerseyWebTarget.java#L170-L173), which calls 
- [`setQueryParam(UriBuilder uriBuilder, String name, Object[] values)`](https://github.com/jersey/jersey/blob/2.22/core-client/src/main/java/org/glassfish/jersey/client/JerseyWebTarget.java#L175-L182), which then calls 
- [`JerseyUriBuilder.queryParam(String name, Object...values)`](https://github.com/jersey/jersey/blob/2.22/core-common/src/main/java/org/glassfish/jersey/uri/internal/JerseyUriBuilder.java#L550), which calls 
- [`name = encode(name, UriComponent.Type.QUERY_PARAM)`](https://github.com/jersey/jersey/blob/2.22/core-common/src/main/java/org/glassfish/jersey/uri/internal/JerseyUriBuilder.java#L562)

**Comment by XanderXAJ** [comment]
@johnflavin You're right.  I had noticed this, but should have worded my initial comment better! 🙈

@mattnworb I don't think filters go through that code, but are instead added to a list ([`filters.put(param.name(), filterValueList)`](https://github.com/spotify/docker-client/blob/0f7e2196cdea1fdda8ded876ea347f344771105d/src/main/java/com/spotify/docker/client/DefaultDockerClient.java#L1425)) and then encoded separately ([`resource = resource.queryParam("filters", urlEncodeFilters(filters))`](https://github.com/spotify/docker-client/blob/v7.0.2/src/main/java/com/spotify/docker/client/DefaultDockerClient.java#L1435)).

I believe this means both `com.fasterxml.jackson.databind.ObjectMapper` and Jersey perform URL encoding.  Perhaps they do not quite agree on how it should be done?

If Jersey is doing the URL encoding internally, what is the need to do it in advance?

**Comment by davidxia** [comment]
@XanderXAJ How can I repro this? Specifically, how do I generate events with `health_status: healthy`?

**Comment by XanderXAJ** [comment]
@davidxia Here is a minimal Dockerfile that will generate a `health_status: healthy` event after 3 seconds:

```
FROM busybox:1.26

HEALTHCHECK --interval=1s --timeout=1s --retries=3 CMD true

CMD ["sleep", "10"]
```

A container will only output one healthy message (unless it were to become unhealthy and the healthy again), so re-run this image to get more messages as needed.
