### ISSUE TITLE
Help: Changes required in the code while using a remote docker engine

### ISSUE THREAD

**Issue by felixsiju** [spotify/docker-client#630]
## Description

What all the changes to be done  while using a docker engine configured on remote machine.
Please help

## How to reproduce

[Add steps on how to reproduce this issue]

## What do you expect

[Describe what do you expect to happen]

## What happened instead

[Describe the actual results]

## Software:

- `docker version`: [Add the output of `docker version` here, both client and server]
- Spotify's docker-client version: [Add docker-client version here]

## Full backtrace

```text
[Paste full backtrace here]
```

**Comment by johnflavin** [comment]
Please see the [user manual](https://github.com/spotify/docker-client/blob/master/docs/user_manual.md).

Let us know what you have tried to do, what did or didn't work, etc.

**Comment by felixsiju** [comment]
docker version remote machine

docker version
Client:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        
 OS/Arch:      linux/amd64


docker version local

docker version
Client:
 Version:      1.13.0
 API version:  1.25
 Go version:   go1.7.3
 Git commit:   49bf474
 Built:        Tue Jan 17 09:58:26 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.13.0
 API version:  1.25 (minimum version 1.12)
 Go version:   go1.7.3
 Git commit:   49bf474
 Built:        Tue Jan 17 09:58:26 2017
 OS/Arch:      linux/amd64
 Experimental: false

DockerHost.java

  private static final String DEFAULT_ADDRESS = "remote hostname";
  private static final int DEFAULT_PORT = 4243;


Test.java(trying to print the API version of remote host)
            registryAuth = RegistryAuth.builder().username(AUTH_USERNAME).password(AUTH_PASSWORD).build();
            final DefaultDockerClient.Builder builder = DefaultDockerClient.fromEnv();
            // Make it easier to test no read timeout occurs by using a smaller value
            // Such test methods should end in 'NoTimeout'

            dockerEndpoint = builder.uri();

            System.out.printf("dockerEndpoint- %s\n", dockerEndpoint);

            sut = builder.build();

            dockerApiVersion = sut.version().apiVersion();

            System.out.printf("dockerApiVersion- %s\n", dockerApiVersion);


output
-----

dockerApiVersion- 1.25

i was expecting the remote host docker api version as output. What all the changes i missed to pick the remote docker engine.

**Comment by mattnworb** [comment]
@felixsiju you need to tell the DefaultDockerClient the URI/address of the docker instance you want to communicate with. see https://github.com/spotify/docker-client/blob/master/docs/user_manual.md#creating-a-docker-client
