### ISSUE TITLE
Why most of the fields for `docker service create` have been marked as mandatory?

### ISSUE THREAD

**Issue by dmandalidis** [spotify/docker-client#635]
Since docker-client 7.0.x, most of the docker service create options like the properties of Mount, ServiceSpec, ContainerSpec have been marked as mandatory. The clients of these versions have to explicitly enter the default values although docker engine provides them (by default). Last week, I 've opened issues (#617 and #619) to address some of them but it seems that the same situation applies to most of the options (e.g. you cannot create a volume without providing bindOptions). Is this done on purpose or is it a bug?

**Comment by davidxia** [comment]
@dmandalidis Sorry, this is a bug. Do you have a full list of all the optional attributes?

**Comment by dmandalidis** [comment]
@davidxia No I haven't the list at hand and it will take time to compile one. Moreover, I 'm using a couple of methods of docker-client and others may be missing as well. As far as I understood a major refactoring with AutoValue took place which messed up things, could you check back at 6.2.5 version the attributes for docker-service-create were correct at the time.

**Comment by davidxia** [comment]
@dmandalidis Please take a look at PR #645. Hopefully I got all of them.

**Comment by davidxia** [comment]
I'm going to close. We can create new issues for specific bugs.
