### ISSUE TITLE
swarm node list

### ISSUE THREAD

**Issue by timchenxiaoyu** [spotify/docker-client#636]
how to get all swarm nodes

**Comment by johnflavin** [comment]
Currently you can't. The docker REST API added the `GET /nodes` endpoint in version 1.24, and docker-client is not yet completely updated to be compatible with that version of the docker API.

We be happy to review a pull request to add it.

**Comment by davidxia** [comment]
Duplicate of https://github.com/spotify/docker-client/issues/543
