### ISSUE TITLE
autovalue in eclipse error

### ISSUE THREAD

**Issue by timchenxiaoyu** [spotify/docker-client#639]
after  set autovalue to factory path ,the error still exsit! complie error
for example :AutoValue_AttachedNetwork cannot be resolved to a type

**Comment by johnflavin** [comment]
Have you enabled annotation processors for your eclipse project? 

I'm not 100% sure how to do that in eclipse, as I use a different IDE. But I have a hunch that if you can check some box in your settings somewhere this problem will go away.

**Comment by timchenxiaoyu** [comment]
cloud you tell me  which IDE do you use?

**Comment by johnflavin** [comment]
I use IntelliJ: https://www.jetbrains.com/idea/. I have the non-free "ultimate" edition through my job, but I believe the "community" edition is free.

**Comment by davidxia** [comment]
@timchenxiaoyu I also use IntelliJ community edition. Is this still an issue or can I close?
