### ISSUE TITLE
listServices error

### ISSUE THREAD

**Issue by timchenxiaoyu** [spotify/docker-client#642]
docker is 1.13
docker.listServices() error

abstract types either need to be mapped to concrete types, have custom deserializer, or be instantiated with additional type information
 at [Source: org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$UnCloseableInputStream@689a01c0; line: 1, column: 431] (through reference chain: java.util.ArrayList[0]->com.spotify.docker.client.messages.swarm.Service["Spec"]->com.spotify.docker.client.messages.swarm.ServiceSpec["TaskTemplate"]->com.spotify.docker.client.messages.swarm.TaskSpec["ContainerSpec"]->com.spotify.docker.client.messages.swarm.ContainerSpec["Mounts"]->java.util.ArrayList[0])

**Comment by timchenxiaoyu** [comment]
"TaskTemplate": {
                "ContainerSpec": {
                    "DNSConfig": {},
                    "Image": "google/cadvisor:v0.24.1@sha256:902449e23fc2cab1ca9788e2610b0928f27ee91e503f3326c7a463fa17d11dd9",
                    "Labels": {
                        "com.docker.stack.namespace": "monitoring"
                    },
                    "Mounts": [
                        {
                            "Source": "/",
                            "Target": "/rootfs:ro",
                            "Type": "bind"
                        },
                        {
                            "Source": "/var/run",
                            "Target": "/var/run:rw",
                            "Type": "bind"
                        },
                        {
                            "Source": "/sys",
                            "Target": "/sys:ro",
                            "Type": "bind"
                        },
                        {
                            "Source": "/var/lib/docker/",
                            "Target": "/var/lib/docker:ro",
                            "Type": "bind"
                        }
                    ]

**Comment by davidxia** [comment]
Which version of docker-client are you using? I ran `DefaultDockerClientTest.testListServices()` on docker 1.13.1 with the latest master of docker-client and it works.

**Comment by davidxia** [comment]
@timchenxiaoyu Sorry, you're right. I made a PR above.

**Comment by timchenxiaoyu** [comment]
Method listTasks also has this problem

Instantiation of [simple type, class com.spotify.docker.client.messages.swarm.Resources] value failed: Missing required properties: memoryBytes (through reference chain: java.util.ArrayList[0]->com.spotify.docker.client.messages.swarm.Task["Spec"]->com.spotify.docker.client.messages.swarm.TaskSpec["Resources"]->com.spotify.docker.client.messages.swarm.ResourceRequirements["Limits"])

**Comment by davidxia** [comment]
@timchenxiaoyu I made `memoryBytes` nullable but want to write a test for it. Do you have steps to repro? What platform are you on?
