### ISSUE TITLE
identityToken RegistryAuth should look for identitytoken

### ISSUE THREAD

**Issue by scheerer** [spotify/docker-client#648]
## Description

My previous feature add #581 missed the mark slightly. I apparently goofed the actual identitytoken being entirely lowercase in my unit tests and code.

## How to reproduce

`RegistryAuth.fromDockerConfig()` with a real identitytoken based config.json file.

## What do you expect

RegistryAuth should be valid and correctly parsed.

## What happened instead

"Failed to parse auth string for {}"

## Software:

- `docker version`: 
```
$ docker version
Client:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:        Wed Oct 26 23:26:11 2016
 OS/Arch:      darwin/amd64

Server:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:        Wed Oct 26 23:26:11 2016
 OS/Arch:      linux/amd64
```
- Spotify's docker-client version: 8.0.0

**Comment by mattnworb** [comment]
is this still an issue?

**Comment by scheerer** [comment]
Yes it is still an issue

**Comment by davidxia** [comment]
@scheerer Will #816 fix it?
