### ISSUE TITLE
Why there is a restriction for the container name?

### ISSUE THREAD

**Issue by lephix** [spotify/docker-client#658]
In file `docker-client/src/main/java/com/spotify/docker/client/DefaultDockerClient.java` there is a restriction for the container name.

    private static final Pattern CONTAINER_NAME_PATTERN = Pattern.compile("/?[a-zA-Z0-9_-]+");

For example, in docker envrionment, the `.` is allowed for the container name. e.g `a.b.c-123` is a valid container name in docker.

**Comment by johnflavin** [comment]
Do you have a link to documentation? (Not that I'm doubting you are correct, I just want to make sure we get it right if we change something.)

I suspect that maybe a `.` cannot be the first character. So maybe the pattern would be something like `/?[a-zA-Z0-9_-][a-zA-Z_-.]*`.

**Comment by mattnworb** [comment]
My guess would be that docker used to accept a much smaller set of names for the container. 

As best as I can tell from looking at the docker source code (at least in 1.13), [this is the current validation for container name](https://github.com/docker/docker/blob/v1.13.1/utils/names.go#L9)

**Comment by mattnworb** [comment]
here is the source for the master branch of docker (seems like everything is always moving around): https://github.com/docker/docker/blob/dba271a42ab4841dbcf2e953491e9ee728cd8e16/api/names.go#L5-L9

and we would be happy to accept patches to update the regex within docker-client 😄
