### ISSUE TITLE
Potential race condition in tests?

### ISSUE THREAD

**Issue by davidxia** [spotify/docker-client#672]
See

https://travis-ci.org/spotify/docker-client/jobs/208527822
https://travis-ci.org/spotify/docker-client/jobs/208475102
https://travis-ci.org/spotify/docker-client/jobs/208527822
https://travis-ci.org/spotify/docker-client/jobs/209783076
https://travis-ci.org/spotify/docker-client/jobs/208527822
https://travis-ci.org/spotify/docker-client/jobs/209833577
https://travis-ci.org/spotify/docker-client/jobs/210681087
https://travis-ci.org/spotify/docker-client/jobs/211064815
https://travis-ci.org/spotify/docker-client/jobs/211102812
https://travis-ci.org/spotify/docker-client/jobs/211064816

**Comment by johnflavin** [comment]
I'm not sure if this is the race you’re talking about, but here are two jobs that both failed in the same way in `DefaultDockerClientTest#testInspectTask`. I know there have been others like this, but I don't have the links right now.
* [Job #1146.5](https://travis-ci.org/spotify/docker-client/jobs/210681087)
* [Job #1155.5](https://travis-ci.org/spotify/docker-client/jobs/211344040)

They're asserting that two `Task`s are equal. The objects look completely identical except their `Version.index` values are off by one. I don't know how docker sets that version index, or why it would get changed, or what. But this is something we should investigate.

**Comment by johnflavin** [comment]
Note: all the `Task.Version` errors I've collected so far have been on docker version 1.12.1. There could be some known bug in that version. If we can verify that, we could either skip `DefaultDockerClientTest#testInspectTask` for that version or move testing to one of the other 1.12.x minor versions that is not affected.

**Comment by davidxia** [comment]
I vote for latter option.
