### ISSUE TITLE
No builder for Device

### ISSUE THREAD

**Issue by pmcq** [spotify/docker-client#673]
## Description
Currently I am using v6.2.5 but was looking to upgrade to the most recent versions.  However it seems with the change to use AutoValue it's no longer possible to construct a Device? 

I currently use `HostConfig.builder().devices(new Device(...), new Device(...))` to run a container with an attached device.  With the AutoValue'd version Device is abstract so can't be initialized, and the AutoValue_Device isn't accessible.  Looks like a builder needs to be setup as well but I wasn't sure if this was intentional and in new versions should be adding devices some other way. 

https://github.com/spotify/docker-client/blob/master/src/main/java/com/spotify/docker/client/messages/Device.java
https://github.com/google/auto/blob/master/value/userguide/builders.md

**Comment by davidxia** [comment]
@pmcq Thanks for notifying us. Sorry, this is a regression. We'll make a fix.

**Comment by johnflavin** [comment]
You can use the static creator method `Device.create(...)`.

**Comment by davidxia** [comment]
That one's package private :(

**Comment by johnflavin** [comment]
Ah, ok, I did not notice that.

**Comment by davidxia** [comment]
I'll make a PR.

**Comment by pmcq** [comment]
Thanks for the quick turnaround!
