### ISSUE TITLE
Cannot set ipam parameters of container when connecting to a network

### ISSUE THREAD

**Issue by weilai201** [spotify/docker-client#675]
### version
Docker API 1.24
SDK 8.1.2

When I use DefaultDockerClient to connect a container to a network.I cannot find any way to set ipam parameters of NetworkConnection.

I use docker rest api /networks/{id}/connect. I can set ipam paramter ,like 
````
{
  "Container":"f39732ed3ca1",
  "EndpointConfig": {
    "IPAMConfig": {
        "IPv4Address":"172.18.0.3"
    }
  }
}
````

**Comment by johnflavin** [comment]
Currently this isn't possible. We need to fix that. 

What you should be able to do is something like
```java
EndpointConfig.builder()
        .ipamConfig(IpamConfig.builder()
                .ipv4Address("whatever")
                .build())
        .build()
```

There is an `EndpointConfig`, and you can build it, but it does not have any `IpamConfig` yet.
