### ISSUE TITLE
Support for network labels

### ISSUE THREAD

**Issue by albers** [spotify/docker-client#694]
docker-client lacks support for network labels and searching networks based on network labels.
I'd like to contribute this. Would this be appreciated?

**Comment by johnflavin** [comment]
Absolutely!

**Comment by albers** [comment]
OK, then I'll go for it.
This might take a month or so because I can't work on it with high priority.

**Comment by albers** [comment]
- [X] query network labels (#705)
- [X] create networks with labels (#705)
- [ ] add filters to listing networks
