### ISSUE TITLE
extraHosts(): check parameters to shield from docker daemon panic

### ISSUE THREAD

**Issue by grexe** [spotify/docker-client#699]
With docker version `1.12.6, build 78d1802` and docker-client 8.1.3-SNAPSHOT from ~1 week ago, I ran into [docker issue #20997](https://github.com/docker/docker/issues/20997) when supplying wrong parameters to the `hostConfig`'s `extraHosts` parameter.

E.g., when wrongly passing in `extraHosts("host", "alias")` instead of `...("host:alias")`, as I mistakenly did, I'd prefer to get an IllegalArgumentException because the host alias is not properly formatted.

Although it is a docker daemon bug (producing an `out of bounds` error instead of returning the proper cause (illegal argument), it would save devs some time when the library could check the parameters first.

**Comment by grexe** [comment]
see also https://github.com/docker/docker/issues/32136

**Comment by mattnworb** [comment]
so a good fix for this in docker-client would need to check each of these params for something like `\w+:\w+`? Is it enough to just check for the `:`?

**Comment by grexe** [comment]
A simple check for a single ':' should be enough I suppose...
