### ISSUE TITLE
Add more swarm functionality (initialize, join)

### ISSUE THREAD

**Issue by limorgottlieb** [spotify/docker-client#701]
## Description
As I see in the pull requests section, there is already a pull request #516 which was not merged to the master and is related to adding more swarm functionality.
I'm not sure what is the reason for not merging this pull request.
I would be happy to clone the code and fix tests if that is the reason...

In addition, It would be very helpful if swarm join functionality will be added too.

## What do you expect
Swarm initialize and join functionality will be part of the DockerClient

## Software:

- `docker version`: Client:
 Version:      1.12.3
 API version:  1.24

- Spotify's docker-client version: 8.2.1

## Full backtrace

```text
[Paste full backtrace here]
```

**Comment by davidxia** [comment]
@limorgottlieb I never finished that PR. Yes, feel free to help complete it. Any PRs are welcome.

**Comment by limorgottlieb** [comment]
@davidxia I'll take this PR and try to complete it. Can you specify what is still missing in the initialize functionality?
I'll also try to add the join functionality.
The question is if you have time to go over my changes and merge the code?

**Comment by limorgottlieb** [comment]
Hi @davidxia 
I have a new branch with an additional swarm functionality.
I have no permission to push this branch and create a PR.
Could you please help? I really need this additional functionality to be in.
Thanks!

**Comment by johnflavin** [comment]
You'll need to fork the repository. Then you can make a new branch on your repo and push your changes to that branch. (See the docs on [adding a remote](https://help.github.com/articles/adding-a-remote/) to make this easier; I usually call my fork `mine`.) You will make your pull request from that branch on your repo.

**Comment by limorgottlieb** [comment]
Hi,
Did it, I forked the repository and pushed the changes to the new branch.
Thanks.

**Comment by davidxia** [comment]
fixed by https://github.com/spotify/docker-client/pull/729
