### ISSUE TITLE
Classes from `com.google.code.findbugs` missing in shaded jar

### ISSUE THREAD

**Issue by burgerdev** [spotify/docker-client#702]
## Description

The classes from the `com.google.code.findbugs` dependencies belonging to package `javax.annotation` are relocated in the shaded jar, but since the dependency has scope `provided`, they are not really included. This leads to warning messages, at least when using the shaded jar with scala.

## How to reproduce

Build a **scala** project with the shaded `docker-client` jar.

## What do you expect

No warnings about missing classes from `com.spotify.*`.

## What happened instead

A lot of warnings show up.
```text
Warning: scalac: Class com.spotify.docker.client.shaded.javax.annotation.Nullable not found - continuing with a stub.
```

## Software:

- `docker version`: N/A
- Spotify's docker-client version: `8.2.0`

## Full backtrace

N/A

**Comment by davidxia** [comment]
@burgerdev I don't see `com.google.code` relocated in the [pom](https://github.com/spotify/docker-client/blob/fe60e58bcc18d936b62aac54ef620f1be1a69a81/pom.xml#L323). I'm not sure why I made `com.google.code` deps have the provided scope though (see [this PR](https://github.com/spotify/docker-client/pull/582/files#diff-600376dffeb79835ede4a0b285078036R149)). Maybe it shouldn't be?

**Comment by burgerdev** [comment]
The package `com.google.code.findbugs` contains classes with package `javax.annotation` (I arrived at this conclusion by [googling for Nullable](https://stackoverflow.com/a/19031259/6144653)). Those [are relocated](https://github.com/spotify/docker-client/blob/fe60e58bcc18d936b62aac54ef620f1be1a69a81/pom.xml#L318), but the relocated classes are not packaged because of scope `provided`. Does it make more sense now?

**Comment by davidxia** [comment]
Yes, thanks. If you remove the provided scope, install the jar locally, then build your scala project. Do the warnings go away?
