### ISSUE TITLE
Get volume names when inspecting a container

### ISSUE THREAD

**Issue by gortiz** [spotify/docker-client#709]
## Description

I am trying to remove all volumes used by a container, but AFAIK, that cannot be done. ContainerInfo.mount() returns a list of ContainerMount, but DockerClient.removeVolume() accepts either a volume name or a Volume object. As ContainerMount doesn't expose the name attribute and it is not a subclass of Volume, that information cannot be used to remove the volume

## How to reproduce

It is (if I'm not wrong), a defect on the API.

## What do you expect

I would like to have a way to translate from a ContainerMount to a Volume or, at least, to get the name of the mount. Ideally, I would like to be access to other mount attributes like its type.

## What happened instead

ContainerMount does not expose some attributes you can find with docker inspect, and specially the name attribute is needed to call DockerClient.removeVolume

## Software:

- `docker version`: Client: 17.03.0-ce, Server: 17.03.0-ce
- Spotify's docker-client version: 8.2.1

**Comment by johnflavin** [comment]
There is a difference between creating a named volume and mounting a host directory into a container.   

If you create a volume object before you create your container, then you can give it a name and (optionally) a host directory. That volume has its own life cycle independent of any container, which you would need to manage by deleting it yourself when you want to clean up. And you could mount that volume in the container by using its name, rather than using a host directory path.

When you create a container with a host directory mounted, docker does not create any volume object for that. (Ok, maybe docker does create a volume internally, but its life cycle is tied to that of the container and it isn't manageable from the outside.) You don't make a volume, so you won't have a volume name and you won't be able to (or need to) remove any volume object.

**Comment by johnflavin** [comment]
We have some examples of this in the documentation: https://github.com/spotify/docker-client/blob/master/docs/user_manual.md#mounting-directories-in-a-container

**Comment by johnflavin** [comment]
Oh, hmm, wait, I think I see what you mean.

In this snippet of the JSON from `docker container inspect`, here is a `Mount` that I created as a bind:
```json
"Mounts": [
    {
        "Type": "bind",
        "Source": "/Users/flavin/code/docker-client",
        "Destination": "/data",
        "Mode": "",
        "RW": true,
        "Propagation": ""
    }
]
```

And here is a `Mount` that I created from a named volume:
```json
"Mounts": [
    {
        "Type": "volume",
        "Name": "foo",
        "Source": "/var/lib/docker/volumes/foo/_data",
        "Destination": "/data",
        "Driver": "local",
        "Mode": "z",
        "RW": true,
        "Propagation": ""
    }
]
```

You’re absolutely correct that the latter has a `"Name"`, and that we aren't returning that. In addition, we aren't reporting `"Type"`, `"Driver"`, or `"Propagation"`.

Sorry that I made my comments above before I understood the issue you were reporting.

**Comment by gortiz** [comment]
Hi @johnflavin,

I am a docker newbie, but I think it doesn't work as you explain on the first answer. I am trying to run database docker images (mongodb and postgres) and they automatically create (at least) one volume to store the data. That volume is not bound to the container lifecycle and in fact it survives to it.

I was trying to use the _ContainerConfig.Builder.volumes("/path")_ you explain on the documentation (using the same path as the one declared on the image), but the created volume does still survive.

As a temporal path, I found the same solution you explain: explicitly create a volume with a name I can control, so I can remove it once the container is stopped. It is not ideal, but it works.

**Comment by johnflavin** [comment]
Yes, I see. When you create a volume using `ContainerConfig.Builder.volumes("path")`, you are creating a volume object but it is an "anonymous volume". It has a random name assigned by docker, and it can't mount any host directories. 

If you want more control over the volume, it is better to create it yourself by hand, give it a name, etc. But in lieu of all that we should be returning the `"Name"` on the `Mount` object. That would allow you to delete the volume even if you didn't create it yourself and give it a name. (`"Name"` was added to the docker API many versions ago; we just missed that at the time and never added it.)
