### ISSUE TITLE
No changelog?

### ISSUE THREAD

**Issue by ketan** [spotify/docker-client#717]
I don't see the changelog file being maintained which makes it really difficult to when upgrading the library to see what has changed between versions.

Could I ask the maintainers to keep the CHANGELOG up-to-date, preferably when merging PR, if it makes it easy to maintain the file better?

Thanks

**Comment by davidxia** [comment]
Hey, sorry about this. We can definitely keep the changelog up to date going forward.

**Comment by mattnworb** [comment]
We'll make sure that new PRs keep the changelog up to date.
