### ISSUE TITLE
Bachelor Thesis Query

### ISSUE THREAD

**Issue by JeanFrancoisMaes** [spotify/docker-client#724]
Dear Spotify Github members. 

I know the Issue section of a git repo is probably not the place to ask this but since the website didn't really offer me any quality mail address to forward this type of question too, I'm going all in here anyway 

I'm a final year Computer Science student, currently doing his end thesis about Docker in corporate grade production environments. 

It would mean the world to me to ask an engineer of Spotify a few Questions. It won't take up a lot of time I promise. 

Sorry to post this here, did not really have another option as far as I could see... 

Kind Regards and Thanks in advance 

Jean

**Comment by davidxia** [comment]
@JeanFrancoisMaes Sorry for the slow reply. Do you still need help?

**Comment by davidxia** [comment]
DM me on twitter @davidxia_ if so.
