### ISSUE TITLE
Add ManagerStatus into Node

### ISSUE THREAD

**Issue by olegtikhonov** [spotify/docker-client#737]
## Description
Node is not contains ManagerStatus
[Add feature/bug description here]

## How to reproduce
dockerClient.listNodes() or look at Node.java
[Add steps on how to reproduce this issue]

## What do you expect
    @JsonProperty("Leader")
    private Boolean leader;
    @JsonProperty("Reachability")
    private String reachability;
    @JsonProperty("Addr")
    private String addr;
[Describe what do you expect to happen]

## What happened instead
Is not there
[Describe the actual results]

## Software:

- `8.4.0`: [Add the output of `docker version` here, both client and server]
- Spotify's docker-client version: [Add docker-client version here]

## Full backtrace

```text
[Paste full backtrace here]
```

**Comment by davidxia** [comment]
added in https://github.com/spotify/docker-client/pull/774

**Comment by ssullivan** [comment]
The ManagerStatus got added onto a new class called NodeInfo which the inspectNode method returns. I could do a quick PR now that #774 has been merged and add ManagerStatus into the Node class.

**Comment by hatunet** [comment]
It's did.

Why not solve it ?
