### ISSUE TITLE
Enable Proxy support

### ISSUE THREAD

**Issue by shrids** [spotify/docker-client#742]
Currently `com.spotify.docker.client.DefaultDockerClient` does not provide a way to configure http proxy.
We could add something on the following lines so that the internal jaxws.rs client has proxy configured.
```
final ClientConfig config = DEFAULT_CONFIG
        .connectorProvider(new ApacheConnectorProvider())
        .property(ApacheClientProperties.CONNECTION_MANAGER, cm)
        .property(ApacheClientProperties.REQUEST_CONFIG, requestConfig)
        .property(ClientProperties.PROXY_URI, proxy);
        .property(ClientProperties.PROXY_USERNAME,user);
        .property(ClientProperties.PROXY_PASSWORD,pass);
```

**Comment by mattnworb** [comment]
Any idea if the Jersey/ApacheConnectorProvider will respect system properties like `-Dhttp.proxyHost`, like [the `java.net. package does](https://docs.oracle.com/javase/7/docs/api/java/net/doc-files/net-properties.html)? If not that is a bummer.

Would you be willing to create a PR that adds these properties to the DefaultDockerClient.Builder class? that seems like the most natural place to configure this if the system properties aren't read by Jersey.

**Comment by shrids** [comment]
System properties like `http.proxyHost` are not read by Jersey. Added the following snippet inside the package private constructor of `DefaultDockerClient`.

```
    final String proxyHost = System.getProperty("http.proxyHost");
    if (proxyHost != null) {
      config.property(ClientProperties.PROXY_URI, proxyHost + ":"
              + System.getProperty("http.proxyPort", "8080"));
    }
```
This change ensured all the HTTP GET requests to `dockerd `works. But all POST requests to `dockerd `throws an EOF error (error snippet below) . Wondering if it is a setup issue or a proxy issue.
`
docker[21429]: time="2017-05-16T08:31:05.692109391Z" level=error msg="Handler for POST /containers/create returned error: EOF"`

I have a docker daemon which supports 1.24 api version. dockerD version is 1.12.6

**Comment by shrids** [comment]
Found the reason why POST failed while using tinyproxy. (https://github.com/tinyproxy/tinyproxy/issues/58)
To solve this we need to ensure content-length is populated by jersey client. This can be done by setting the following additional property in jersey client
`config.property(ClientProperties.REQUEST_ENTITY_PROCESSING, RequestEntityProcessing.BUFFERED);`
With this change it is working fine...
