### ISSUE TITLE
start requiring Java 8?

### ISSUE THREAD

**Issue by mattnworb** [spotify/docker-client#756]
Java 7 has been [EOL since April 2015](http://www.oracle.com/technetwork/java/eol-135779.html). Do we still need to support it in this library, i.e. compile for target=1.7 source=1.7?

The motivation for this question is that I started to use [our hamcrest-jackson](https://github.com/spotify/java-hamcrest) library in some unit tests in #753 but forgot that this library is built with Java 7 and hamcrest-jackson is built with 8.

Is there anyone using this that is stuck on 7 for some reason, or some other argument to be made against moving to compiling with 8?

**Comment by johnflavin** [comment]
My application is still on java 7. We plan to move to java 8 at some point, but it is never the top priority.

However, I wouldn't want you to hold up progress on my account. My needs are well served by the existing functionality in `docker-client`, so if I had to depend on an older version that supported java 7 it wouldn't bother me.

**Comment by mattnworb** [comment]
We could also explore building for both 7 and 8, using some maven profile magic, and upload both to Maven Central (with a classifier for one of jdk8 or jdk7). 

At this point all I am really after is being able to use some 8-only libraries *in tests*, and not using 8 language features or standard library classes, so perhaps it would be enough to run tests with jdk8 (to allow classes compiled for 8 to load) but build for 7 only (source/target=7 should catch use of 8 language features, but not catch use of 8 classes like Stream etc AFAIK).

**Comment by davidxia** [comment]
I'm fine with using 8 for tests only. It'd be nice to just build new versions for 8 as well, but I'm not sure how many people will complain.

**Comment by mattnworb** [comment]
Another bonus of using Java 8 is I think we could convert all usages of ListenableFuture to CompletableFuture and possibly ditch the Guava dependency altogether.

**Comment by hekonsek** [comment]
Keep in mind that some of your dependencies (like Jersey #915) has already moved to Java8. In practice that would mean that you can't upgrade those dependencies as long as you stick to Java 7. Also some other libraries which happen to use those latest, Java8-based versions of dependencies will be conflicting with docker-client. Please do consider upgrading to Java8. :)

**Comment by mattnworb** [comment]
I happened to notice today that Oracle will end public updates to Java SE 8 in September 2018, so with less than one year left of real "life", I think it is overdue to set this as a minimum version.

**Comment by diemol** [comment]
Can we help with this? I am running often to something similar to #877, and it would be nice to start updating the dependencies.
 What about building with Java 8 first and increment the dependencies one by one? Please let me know how we can contribute.

**Comment by mattnworb** [comment]
@diemol that sounds like exactly the plan I would take myself, so if you want to start any of that in a PR that would be awesome!

**Comment by diemol** [comment]
Sure, I'll give it a try to see how much I can advance. My project relies heavily on this one and giving a hand is the least I could do. 

What is better for you? Opening a PR with a [WIP] status, or I could also setup Travis for my fork.
