### ISSUE TITLE
Auth fails when .docker/config.json base64 decoded password contains a ':' character

### ISSUE THREAD

**Issue by gordz** [spotify/docker-client#764]
## Description
RegistryAuth.forAuthToken() fails to return a correctly populated auth object if the password contains a ':' (colon) character.

## How to reproduce
Use a registry auth file that has a ':' in the password.

## What do you expect
Should be able to authenticate with a registry correctly.

## What happened instead
Authentication fails.

## Software:

- `docker version`: Docker version 17.03.1-ce, build c6d412e
- Spotify's docker-client version: current master 

## Full backtrace
N/A

**Comment by mattnworb** [comment]
Thanks for the report and sorry for the headache. The master branch is a bit unstable at the moment and I would suggest continuing to use the last release version.

Without telling me your actual `auth` value or password, could you describe how the value of that field looks a bit more? Is it actually base64-encoded like [the code in forAuthToken expects](https://github.com/spotify/docker-client/blob/073ad2321c57b752c26ef1f1f743ef6ffcf8b079/src/main/java/com/spotify/docker/client/messages/RegistryAuth.java#L164-L168)? After base64-decoding it, does the value look like `<username>:<password>` - or in other words, how many times does a `:` appear in the decoded string?

**Comment by mattnworb** [comment]
If it is in fact base64 decoded to `<username>:<password>` and the `<password>` has another `:` in it, then the simplest fix is probably that forAuthToken should be splitting the string using the `.split(delimiter, limit)` overload, like `.split(":", 2)`.

**Comment by mattnworb** [comment]
What I describe in the last comment is exactly how [the docker-cli is parsing the field](https://github.com/docker/cli/blob/db5620026dda9b8f5da519e382cf40ed22775e6d/cli/config/configfile/file.go#L184-L189).

**Comment by gordz** [comment]
Nice work, apologies for the delayed response. We ran into the bug on a fork of the 4.0.2 tag, so the bug has been around for a while, however I did notice the same issue on master.
