### ISSUE TITLE
Using volumes_from to compose a volume only docker image into my docker image

### ISSUE THREAD

**Issue by favetelinguis** [spotify/docker-client#769]
The usage guide talk about volumes but there is not example of the case where one would like to use something as volumes_from as is available in docker compose.
 
My question is if there is support for using volumes_from to mount a volumes only docker image into another image using spotify docker client?

**Comment by johnflavin** [comment]
I'm not sure. I looked in docker's API documentation, and I could not find a reference to that. I know it is possible to do through their API, because that's what the CLI uses, but I'm not exactly sure how. Let me do some checking to see if I can figure it out.

**Comment by johnflavin** [comment]
Yes, it is possible. Create a `HostConfig`, and use the `.volumesFrom(String...)` method on its `Builder`. Example:
```java
final String volumeContainer = "some existing container name";
final HostConfig hostConfig = HostConfig.builder()
    .volumesFrom(volumeContainer)
    .build();
final ContainerConfig config = ContainerConfig.builder()
    .image("busybox:latest")
    .hostConfig(hostConfig)
    .cmd("ls", "/foo")
    .build();
client.createContainer(config);
```

**Comment by favetelinguis** [comment]
Ok thanks very much
