### ISSUE TITLE
Proxy problem

### ISSUE THREAD

**Issue by damianopezzotti** [spotify/docker-client#800]
## Description

In my environment, an http proxy is used to access external websites, while docker is inside my network.
My jvm automatically setup proxy system properties and then docker-client try to use proxy to access docker.

## How to reproduce
Setup _http.proxyHost_ system property to a proxy that cannot access docker (or to a wrong address)

## What do you expect

I'd like to decide if proxy has to be used or not, using for example _http.nonProxyHosts_ system property.

**Comment by mattnworb** [comment]
Looks like [Jersey's ClientProperties](https://jersey.github.io/apidocs/latest/jersey/org/glassfish/jersey/client/ClientProperties.html) doesn't have anything corresponding to a "non-proxy hosts" property.

See #771 for how the proxy support was implemented. Perhaps one solution here could be to add a method to the DefaultDockerClient.Builder to disable the proxy behavior that is enabled if `http.proxyHost` is set.

**Comment by davidxia** [comment]
fixed by https://github.com/spotify/docker-client/pull/819
