### ISSUE TITLE
Pushing to private registry fails with 'No basic auth' for older style config.json

### ISSUE THREAD

**Issue by bkielczewski** [spotify/docker-client#804]
## Description

Pushing to private registry fails with 'No basic auth', even if there are credentials for this registry stored in ~/.docker/config.json

Example:

    {
        "auths": {
		"https://some.custom.repository.tld": {
			"auth": "**secret**"
		},
		"https://index.docker.io/v1/": {
			"auth": "**secret**"
		}
        }
    }

Configuration of dockerfile-maven:

    <configuration>
        <repository>some.custom.repository.tld/${project.artifactId}</repository>
    </configuration>

It seems this is because previous versions of docker used to store auth credentials together with repository URL containing transport part (https://some.custom.repository.tld instead of some.custom.repository.tld)

So this currently breaks builds using recent versions of dockerfile-maven, docker-maven plugins ( (>=1.0.0),  i.e. on Shippable, or whenever an older docker was used to issue `docker login`.

In case this is useful to someone, a work-around for Shippable seems to be:

      ci:
       - sed -ie 's/https:\/\///g' ~/.docker/config.json

## What do you expect

Could you just strip transport part out of ~/.docker/config.json, if present?

**Comment by davidxia** [comment]
@bkielczewski What docker versions put the transport in `~/.docker/config.json`? `docker login` on my docker-machine with docker 17.05.0-ce still included the transport

```
{
	"https://index.docker.io/v1/": {
		"auth": "stuff",
		"email": "dxia@spotify.com"
	}
}
```

**Comment by uvwild** [comment]
we are using an **http** registry in an internal network and also have issues with the code trying to read the auths entries in the config.json. This piece of code is not very robust to different variations of the config.json.

**Comment by mattnworb** [comment]
@uvwild can you share what the structure of your config.json looks like?

**Comment by ampedandwired** [comment]
I just encountered this problem using docker 17.06.0-ce.

`docker login https://my.repo.com` results in a `config.json` that looks like this:
```json
{
	"auths": {
		"my.repo.com": {
			"auth": "xxx"
		}
	}
}
```

So the protocol is stripped. However this `config.json` does not work with dockerfile-maven (1.3.4), and results in a `com.spotify.docker.client.exceptions.DockerException: no basic auth credentials` error when pushing.

If I then manually edit `config.json` and add the protocol, like this:
```json
{
	"auths": {
		"https://my.repo.com": {
			"auth": "xxx"
		}
	}
}
```

Then dockerfile-maven is able to push successfully.

**Comment by bkielczewski** [comment]
@davidxia: this is about private registry, and I can confirm this behaviour on docker 1.9.x. This is the one Shippable is using unfortunately. 

I also encountered it locally. Long time ago I've done `docker login` to private registry, it was added with the transport part. I keep updating docker to the newest and didn't have to re-login I can't tell from which version the transport part is no longer being added.

Regardless, it was working ok for docker-maven plugin versions < 1.0, but wasn't ok anymore since 1.0 came out together with dockerfile-maven.

**Comment by hajdukd** [comment]
Is there any possibility to supply the protocol in configuration, to make it at least semi automatic ?
Docker push without protocol works fine.

**Comment by AyeAyePhyuKyaw** [comment]
where can I get "auth" key?

**Comment by amorillotraxens** [comment]
I have the same issue : my .docker/config.json is :
`{
	"auths": {
		"<my_host>:<my_port>": {
			"auth": "YW1vcmlsbG86Q29sb21iZXMxOTcz"
		}
	}
}
`
My maven configuration :
`				<configuration>
					<repository><my_host>:<my_port>/<my_artifact></repository>
					<tag>0.0.1-SNAPSHOT</tag>
					<buildArgs>
						<JAR_FILE>target/<my_artifact>.jar</JAR_FILE>
					</buildArgs>
                                        <useMavenSettingsForAuth>true</useMavenSettingsForAuth>
				</configuration>
`
My settings.xml :
`<servers>
		<server>
			<username><my_user></username>
			<password>{t9H8IPyknrwHWC+/HL78zKtehOijC8+D1cu9Yl8blJE=}</password>
			<id><my_host>:<my_port></id>
		</server>
	</servers>
`
I get this exception when pushing : 
`Caused by: com.spotify.docker.client.exceptions.DockerException: no basic auth credentials`

When I use <username> and <password> in the maven plugin configuration (ie in the pom), it works.
Any help would be appreciated.
Note that I used the maven encryption plugin to generate the password in the settings.xml.
