### ISSUE TITLE
Old Guava used, causes NoSuchMethodError with Guava 22.0

### ISSUE THREAD

**Issue by malejpavouk** [spotify/docker-client#826]
## Description

Currently the project uses Guava version 18.0

from pom:

```
<dependency>
   <groupId>com.google.guava</groupId>
   <artifactId>guava</artifactId>
   <version>18.0</version>
</dependency>
```

## How to reproduce

Set Guava version to 22.0
Try to compile it

or use the project in environment with new guava

## What do you expect
The application is compiled/works.

## What happened instead
java.lang.NoSuchMethodError: com.google.common.net.HostAndPort.getHostText()Ljava/lang/String;

	at com.spotify.docker.client.DefaultDockerClient.fromEnv(DefaultDockerClient.java:1697)

## JavaDoc of Guava 21

@Deprecated
public String getHostText()
Deprecated. Use getHost() instead. This method is scheduled for removal in Guava 22.0.
Old name of getHost().

https://google.github.io/guava/releases/21.0/api/docs/com/google/common/net/HostAndPort.html#getHostText--

---
Please update Guava version in this project. The currently used version 18 is more than 3 years old and it causes problems with recent Guava versions.

Thanks!

**Comment by johnflavin** [comment]
How are you using `docker-client` in your project? Have you tried using the [shaded jar](https://github.com/spotify/docker-client/blob/master/README.md#a-note-on-shading)? That should keep `docker-client`'s guava dependency isolated from the rest of your project.

**Comment by malejpavouk** [comment]
Hi, its a bit more difficult, as the client comes to me as a trasitive dependency through https://github.com/tdomzal/junit-docker-rule. 

Also I do not believe that shading would help me anyway. With shading, the classes are still in their original packages (just all packages are in one jar). And because we still do not have Jigsaw, Java puts all the packages into one bag (regardless from where they came from), so it would just increase number of ClassNotFounds and MethodNotFounds (due to unexpected runtime linking), but would not solve my issue.

**Comment by mattnworb** [comment]
You are correct that guava [is not included in the list of classes](https://github.com/spotify/docker-client/blob/acb18e03d07fafaf9df8944e86e6d133dd196422/pom.xml#L324-L341) that the shade plugin [relocates](https://maven.apache.org/plugins/maven-shade-plugin/examples/class-relocation.html). 

Arguably it should be, as Guava is so widely used that finding a safe version to depend on for as many use cases as possible is tough.

**Comment by davidxia** [comment]
@malejpavouk I think we can't use guava versions greater than 20 because docker-client is built for java 7 and guava versions >= 20 require java 8. See https://github.com/spotify/docker-client/issues/756.

Does locally installing the changes in this PR https://github.com/spotify/docker-client/issues/850 fix your issue?

**Comment by malejpavouk** [comment]
Yes, these changes seems to fix the issue on docker-client side. Thanks!

**Comment by SergiiRedchuk** [comment]
Hello.
I'm trying to use it in my unit test. The dependencies:
    testCompile('com.github.klousiaj:docker-junit-rule:1.3.5') {
        exclude group: 'com.spotify', module: 'docker-client'
    }
    testCompile 'com.spotify:docker-client:8.8.3'
and I still have java.lang.NoSuchMethodError: com.google.common.net.HostAndPort.getHostText()Ljava/lang/String;

Thank you.
