### ISSUE TITLE
I/O exception (java.io.IOException) caught when processing request to {}->unix://localhost:80: No such file or directory

### ISSUE THREAD

**Issue by yangboz** [spotify/docker-client#838]
## Description

I/O exception (java.io.IOException) caught when processing request to {}->unix://localhost:80: No such file or directory

## How to reproduce
 
Java app running well, after Java app dockerization, thrown error. 

## What do you expect

Dockerized version running well.

## What happened instead

final DockerClient dockerClient = DefaultDockerClient.fromEnv().build();

I wonder how can I set the "fromEnv()" method's  external  docker env information as parameter?

## Software:

- `docker version`: Docker version 17.06.0-ce, build 02c1d87
- Spotify's docker-client version: 8.8.0

## Full backtrace

```text
Retrying request to {}->unix://localhost:80
uuid-accredit_1  | 2017-07-23 01:28:14.719 ERROR 1 --- [nio-8095-exec-9] o.a.c.c.C.[.[.[.[dispatcherServlet]      : Servlet.service() for servlet [dispatcherServlet] in context with path [/accredit] threw exception [Request processing failed; nested exception is com.spotify.docker.client.exceptions.DockerException: java.util.concurrent.ExecutionException: javax.ws.rs.ProcessingException: java.io.IOException: No such file or directory] with root cause
uuid-accredit_1  | 
uuid-accredit_1  | java.io.IOException: No such file or directory
uuid-accredit_1  | 	at jnr.unixsocket.UnixSocketChannel.doConnect(UnixSocketChannel.java:94)
uuid-accredit_1  | 	at jnr.unixsocket.UnixSocketChannel.connect(UnixSocketChannel.java:102)
uuid-accredit_1  | 	at com.spotify.docker.client.ApacheUnixSocket.connect(ApacheUnixSocket.java:76)
uuid-accredit_1  | 	at com.spotify.docker.client.UnixConnectionSocketFactory.connectSocket(UnixConnectionSocketFactory.java:78)
uuid-accredit_1  | 	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:134)
uuid-accredit_1  | 	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:353)
uuid-accredit_1  | 	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:380)
uuid-accredit_1  | 	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
uuid-accredit_1  | 	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
uuid-accredit_1  | 	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88)
uuid-accredit_1  | 	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
uuid-accredit_1  | 	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
uuid-accredit_1  | 	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:71)
uuid-accredit_1  | 	at org.glassfish.jersey.apache.connector.ApacheConnector.apply(ApacheConnector.java:435)
uuid-accredit_1  | 	at org.glassfish.jersey.apache.connector.ApacheConnector$1.run(ApacheConnector.java:491)
uuid-accredit_1  | 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
uuid-accredit_1  | 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
uuid-accredit_1  | 	at jersey.repackaged.com.google.common.util.concurrent.MoreExecutors$DirectExecutorService.execute(MoreExecutors.java:299)
uuid-accredit_1  | 	at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:112)
uuid-accredit_1  | 	at jersey.repackaged.com.google.common.util.concurrent.AbstractListeningExecutorService.submit(AbstractListeningExecutorService.java:50)
uuid-accredit_1  | 	at jersey.repackaged.com.google.common.util.concurrent.AbstractListeningExecutorService.submit(AbstractListeningExecutorService.java:37)
uuid-accredit_1  | 	at org.glassfish.jersey.apache.connector.ApacheConnector.apply(ApacheConnector.java:487)
uuid-accredit_1  | 	at org.glassfish.jersey.client.ClientRuntime$2.run(ClientRuntime.java:178)
uuid-accredit_1  | 	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
uuid-accredit_1  | 	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
uuid-accredit_1  | 	at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
uuid-accredit_1  | 	at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
uuid-accredit_1  | 	at org.glassfish.jersey.internal.Errors.process(Errors.java:267)
uuid-accredit_1  | 	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:340)
uuid-accredit_1  | 	at org.glassfish.jersey.client.ClientRuntime$3.run(ClientRuntime.java:210)
uuid-accredit_1  | 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
uuid-accredit_1  | 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
uuid-accredit_1  | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
uuid-accredit_1  | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
uuid-accredit_1  | 	at java.lang.Thread.run(Thread.java:745)
```

**Comment by johnflavin** [comment]
It seems you are asking how you can configure a `DockerClient` instance with the details of your connection. If that is what you are asking, please see the relevant section of the User Manual on [Creating a Docker Client](https://github.com/spotify/docker-client/blob/master/docs/user_manual.md#creating-a-docker-client).

**Comment by yangboz** [comment]
@johnflavin  I try to change the configure to 
final DockerClient docker = new DefaultDockerClient("unix:///var/run/docker.sock");
after that dockerized java app again ,then inside docker-compose running  still the same error, does any ip related configure?

**Comment by johnflavin** [comment]
Let me see if I can figure out what you are trying to do.

You have some java app that uses `docker-client` to do something with docker. You tested it on your machine, and it works fine. Then you put that java app into a docker image and now it doesn't work. Is that correct?

If that is correct, then it seems the problem you are seeing is from your app trying to control docker, but it can't because it is inside a container. Have you tried mounting the docker socket into the container? That would let your app control docker again.

**Comment by yangboz** [comment]
@johnflavin I must to say it is a "docker  in docker-compose" mode, and using "-v /var/run/docker.sock:/var/run/docker.sock " to fix up my problem, and thanks for your help again.

**Comment by pickmonster** [comment]
@yangboz Hi bude. I have been disturbed by same problem, but I don`t understand your way to solve this problem. Is it mean "DockerClient docker = new DefaultDockerClient("-v /var/run/docker.sock:/var/run/docker.sock");"

**Comment by pickmonster** [comment]
@yangboz Hi, buddy. I have been distrubed by same problem, but I can`nt understand your way to solve this question. Is it mean to set DOCKER_HOST value is "-v /var/run/docker.sock:/var/run/docker.sock " ?

DockerClient docker = new DefaultDockerClient("-v /var/run/docker.sock:/var/run/docker.sock");
It like blocked

**Comment by pickmonster** [comment]
@yangboz Hi, buddy. I have been distrubed by same problem, but I can`nt understand your way to solve this question. Is it mean to set DOCKER_HOST value is "-v /var/run/docker.sock:/var/run/docker.sock " ?

DockerClient docker = new DefaultDockerClient("-v /var/run/docker.sock:/var/run/docker.sock");
It can`nt work.

**Comment by yangboz** [comment]
@pickmonster in MacOS,  the  "var/run/docker.sock "  is default value. and I am using Spotify's docker-client API.

**Comment by grimsi** [comment]
Im having the same issue when I deploy my Java app inside of a docker container.
"-v /var/run/docker.sock:/var/run/docker.sock" does not work because I have a windows host system and the container is linux (alpine).
Whats the best way to create a docker client that connects to the docker deamon on the host?
