### ISSUE TITLE
Trouble building Dockerfile

### ISSUE THREAD

**Issue by walteryoung** [spotify/docker-client#854]
## Description

I am having trouble building an image from a Dockerfile using docker-client. I have read through old related issues but can't find what I need. I have a feeling I am setting things up incorrectly.

## How to reproduce

I am following the example from the User Manual here: https://github.com/spotify/docker-client/blob/master/docs/user_manual.md#build-image-from-a-dockerfile

    Path pwd = Paths.get("."); // I have confirmed this is where my Dockerfile is at runtime.
// String imageName is in format: "dockerImage:4.3.2.1"

    final AtomicReference<String> imageIdFromMessage = new AtomicReference<>();
      String returnedImageId = null;
      try {
          returnedImageId = docker.build(pwd.toAbsolutePath(), imageName, new ProgressHandler() {
            @Override
            public void progress(ProgressMessage message) throws DockerException {
              final String imageId = message.buildImageId();
              if (imageId != null) {
                imageIdFromMessage.set(imageId);
            }
            }
        }); // , BuildParam.quiet());
        s_log.info("Docker image {} created. Returned: {}", returnedImageId);
      } catch (DockerException | InterruptedException | IOException e) {
        s_log.error("Exception building the image!", e);
      }

## What do you expect

Some feedback either way, success or failure

## What happened instead

The code hangs. There is no exception caught, and the imageIdFromMessage variable is never modified. When I called this entire method in a try block, it was advancing to the finally() block and attempting to execute that code.

## Software:

- `docker version`: 
$ docker version
Client:
 Version:      17.05.0-ce
 API version:  1.29
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:06:25 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.05.0-ce
 API version:  1.29 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:06:25 2017
 OS/Arch:      linux/amd64
 Experimental: false

- Spotify's docker-client version:         <dockerClientVersion>8.7.3</dockerClientVersion>

## Full backtrace
None.

Thank you in advance for your help.

**Comment by davidxia** [comment]
Can you paste your Dockerfile?

> String imageName is in format: "dockerImage:4.3.2.1"

When I did this docker daemon logs said

```
time="2017-08-10T03:32:44.558053966Z" level=error msg="Handler for POST /build returned error: invalid reference format: repository name must be lowercase"
```

**Comment by walteryoung** [comment]
The imageName I was passing was all lower case, actually. I tried again using only 'testing' as the name and the behavior was the same--no response either way.

I have been building the Dockerfile using a linux command:

    docker build -q -t ${IMAGE_NAME}:${SERVICE_VERSION} .

Which ends up being something like 

    app-service:5.10.0.1

And never had any problems.

Here is my Dockerfile:


    FROM centos
    
    # set java environmental variables
    env JAVA_HOME=/usr/lib/jvm/jre
    env APP_HOME=/opt/APP
    env LD_LIBRARY_PATH="$APP_HOME/library/APPJava/libs":"$APP_HOME/lib/x86_64-unknown-linux-gnu"
    env PATH=$LD_LIBRARY_PATH:$APP_HOME:$JAVA_HOME:/opt/APP:/opt/APP/bin:$PATH
    
    # update with security fixes
    RUN yum -y update && yum install -y java-1.8.0-openjdk && yum clean all && mkdir $APP_HOME && mkdir $APP_HOME/conf && mkdir $APP_HOME/trust && mkdir $APP_HOME/Tools


I turned on docker debug logging and monitored the daemon log using 'journalctl -u docker.service' and there was only one reference to the image I was attempting to build:

    level=debug msg="Calling GET /images/testing/json"

I think that was from this line:

    final ImageInfo info = docker.inspectImage(imageName);

I have seen no other logging, exceptions, or error messages in any way.

**Comment by mattnworb** [comment]
> When I called this entire method in a try block, it was advancing to the finally() block and attempting to execute that code.

This seems to suggest that something was thrown from the try block, causing the finally block to run before the try finished. Are you sure there was no `Throwable` thrown whatsoever?

It's not clear to me from the above message if the `docker.inspectImage(imageName)` succeeded or not. If it did, do any other docker-client API calls also succeed?

If you have a suspicion that things are truly hanging inside of `docker.build(..)` then it would be helpful to generate a thread dump during the hang to see exactly where things are stuck.

**Comment by walteryoung** [comment]
Ah, @mattnworb, great catch. A Throwable was thrown: a dependency on apache commons gzip, which I had previously excluded in my pom.xml for legal/third party software reasons.

I removed that exclude, ran again, and the image built.

Thanks for your help!
