### ISSUE TITLE
Coding conventions

### ISSUE THREAD

**Issue by toelen** [spotify/docker-client#855]
Is their a code style description for this project? I am creating a pull request, and have a pretty hard time configuring my IDE to do automatic formatting.

I tried running java-formatter-plugin on my code, which uses an eclipse settings file, but cannot get it to create the same output as the checkstyle plugin expects.

http://www.jillesvangurp.com/2015/01/29/enforcing-code-conventions-in-java/

**Comment by ssullivan** [comment]
Have you checked the target folder? The checkstyle document should be in there.

**Comment by mattnworb** [comment]
You can find the checkstyle config file that is currently used at https://github.com/spotify/spotify-checkstyle-config/blob/v1.0.2/src/main/resources/spotify_checks.xml

In general you might have more success configuring your IDE to _not_ automatically reformat any lines that you didn't personally edit
