### ISSUE TITLE
Log message behaviour strange when dealing with flushed C stdout

### ISSUE THREAD

**Issue by jjohnstn** [spotify/docker-client#871]
## Description

I work on the Docker Tooling plug-ins that use docker-client.  We have support for running gdbserver in a Container to debug a C/C++ program.  When that C/C++ program has a write to stdout without adding a newline, the output may or may not appear after the program is finished.  During the program, the LogStream is reporting a single LF (line feed) character.  The problem occurs even if I fflush(stdout) in the test program.  Then, after the gdbserver is completed, the stdout message may arrive.  Our code attempts to remove the container when it is done and perhaps the message does not arrive in time.  We are using:

   copyClient.logs(id, LogsParam.follow(), LogsParam.stdout(), LogsParam.stderr());

where copyClient is a copy of the DockerClient which won't cause hanging other operations.

## How to reproduce

This is tricky as it requires using gdb on the client side connected to a gdbserver in a Container that is running a C program that printfs a line without a trailing newline followed by an fflush(stdout).  I would be happy if someone suggested things to try or if the issue is recognizable and fixed in a subsequent release, great, I'll try it.

#include <stdio.h>
#include <stdlib.h>

int main(void) {
	printf("starting\n");
	printf("!!!Hello World!!!"); /* prints !!!Hello World!!! */
	fflush(stdout);
	return EXIT_SUCCESS;
}

## What do you expect

I expect the flushed output to stdout to appear after the fflush(stdout) call is stepped over in the gdb session, but I would accept if the output appeared consistently as the program exits and before the Container exits.

## What happened instead

I always fetch a single Line Feed from the LogStream (one byte) where the output line should have been output.  After gdbserver and the program completes, I sometimes get the expected output line.

## Software:

- `docker version`: 1.10.3
- Spotify's docker-client version: 6.1.1

## Full backtrace

```text
N/A
```

**Comment by johnflavin** [comment]
I have a suspicion that what you are seeing is a symptom of how docker delivers the logs to stdout. When I observe running containers and stream their logs, I can see the should-be-steady stdout inside the container arriving to the external stdout in occasional batches. I don't know if that docker behavior explains what you are seeing, but it sounds similar to me.

Can you try to reproduce what you’re seeing but with `docker-client` taken out of the loop? Execute the same sequence of steps using the docker CLI, or direct to the API using curl with the docker socket. If the problem you’re seeing remains, then there may not be anything you can do from within `docker-client`. If the problem you’re seeing goes away, then maybe there is something we could do, and the difference in behavior between the with-docker-client and without-docker-client replications could help track it down.

**Comment by jjohnstn** [comment]
Ok, I have done some testing.  I should note that I am running gdbserver without TTY or stdin supported.  When I try this with the docker cli command, I see the following:

1. stepping over the printf("starting\n") command results in no output to the terminal
2. stepping over the fflush(stdout) causes the "starting" line plus the "!!!Hello World!!!" to be
    displayed - with the cursor left at the end of  "!!!Hello World!!!"
3. continuing the debugger displays the Child exited message (sent to stderr)

In the end, the output is correct in the right order, but the starting line should have appeared right after the printf statement was stepped over.

[jjohnstn@unused-10-15-17-187 newlib-cygwin]$ docker run -v /home/jjohnstn/runtime-New_configuration-containerbuild/hello:/home/jjohnstn/runtime-New_configuration-containerbuild/hello -p 2345:2345 --security-opt=seccomp:unconfined -w /home/jjohnstn/runtime-New_configuration-containerbuild/hello/Debug fedora26withtools:latest gdbserver :2345 ./hello
Process ./hello created; pid = 11
Listening on port 2345
Remote debugging from host 172.17.0.1
starting
!!!Hello World!!!
Child exited with status 0

When I run the gdbserver with -t, the session runs exactly as expected.  Stepping over the "starting" printf shows the data immediately as does the fflush(stdout).

It is possible that I could restrict the gdbserver to run with -t, however, it does not support the timestamp feature (small price to pay) and shows in a different tab in Eclipse (Terminal instead of Console).

I think you might still be interested in the results (namely that the !!!Hello World!!! shows up before the end of the Child process in gdbserver and no LF as far as I can see).  Is there any further information you would like me to obtain?
