### ISSUE TITLE
Add 'ConfigBind' to 'ContainerSpec'

### ISSUE THREAD

**Issue by wclaeys** [spotify/docker-client#872]
## Description

v1.30 introduced the concept of 'Config' (equivalent of Secret) to the Engine API. Ability to create/read/update/list configs has been introduced in 8.9.0 but no change was done in the ContainerSpec file.

## How to reproduce

Currently there's no possibility to update a Service using this library with a config bind.

## What do you expect

ConfigBind to be available in ContainerSpec.

## What happened instead

No additions were done in ContainerSpec related to Config.

## Software:

- `docker version`: 
```
Client:
 Version:      17.06.0-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:20:36 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.06.0-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:21:56 2017
 OS/Arch:      linux/amd64
 Experimental: false   
```

- Spotify's docker-client version: 8.9.0

**Comment by ssullivan** [comment]
I think PR #869 should take care of this

**Comment by davidxia** [comment]
#869 has been merged and released.
