### ISSUE TITLE
docker image not picked by the client

### ISSUE THREAD

**Issue by safrazhanas** [spotify/docker-client#878]
## Description

I'm trying to build docker image locally and push to private registry.  when i used below code snippet, the image is build locally, however, it's not picked by the client. what am i doing wrong here?

  

## How to reproduce
docker host is set as an environment variable
DOCKER_HOST=tcp://0.0.0.0:2375

used following code snippet

  ```
public static void main( String[] args ) {
        DockerClient docker = null;
        try {
            final RegistryAuth registryAuth = RegistryAuth.builder()
                    .serverAddress("XXXX")
                    .username("XXX")
                    .password("XX")
                    .build();

            docker = new DefaultDockerClient("unix:///var/run/docker.sock");

            final AtomicReference<String> imageIdFromMessage = new AtomicReference<String>();

            final String returnedImageId = docker.build(
                    Paths.get("resource"),
                    "safraz/javabuild", new ProgressHandler() {
                        @Override
                        public void progress(ProgressMessage message) throws DockerException {
                            final String imageId = message.buildImageId();

                            if (imageId != null) {
                                imageIdFromMessage.set(imageId);
                            }
                        }
                    });

            docker.push(returnedImageId, registryAuth);


        } catch (InterruptedException e) {
            System.out.println("......................InterruptedException ......................");
            System.err.println(e.getMessage());

        } catch (IOException e) {
            System.out.println("......................IOException ......................");
            System.err.println(e.getMessage());
        } catch (DockerException e) {
            System.out.println("......................DockerException ......................");
            System.err.println(e.getMessage());
        } finally {
            if(docker != null) {
                docker.close();
            }
        }
    }
```

## What do you expect

docker image should be push to private registry. 

## What happened instead

following is the console output;

Image push failed: ad4c3a9e7cfd: ProgressMessage{id=null, status=null, stream=null, error=An image does not exist locally with the tag: ad4c3a9e7cfd, progress=null, progressDetail=null}
18:23:25.400 [main] INFO com.spotify.docker.client.LoggingPushHandler - push ad4c3a9e7cfd: ProgressMessage{id=null, status=The push refers to a repository [docker.io/library/ad4c3a9e7cfd], stream=null, error=null, progress=null, progressDetail=null}
......................DockerException ......................

however, docker image can be found locally;

[root@sh40246-vm docker]# docker images
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
safraz/javabuild    latest              ad4c3a9e7cfd        22 seconds ago      706MB
java                openjdk-8           d23bdf5b1b1b        7 months ago        643MB

## Software:

- `docker version`: [Add the output of `docker version` here, both client and server]

Client:
 Version:      17.06.1-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   874a737
 Built:        Thu Aug 17 22:53:49 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.06.1-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   874a737
 Built:        Thu Aug 17 23:01:50 2017
 OS/Arch:      linux/amd64
 Experimental: false

- Spotify's docker-client version: [Add docker-client version here]

8.9.0

## Full backtrace

```text
[Paste full backtrace here]
```

**Comment by davidxia** [comment]
I think you need to push with `safraz/javabuild:latest` instead of the hash. Does that work?

**Comment by fraisse** [comment]
It seems that you confuse image id with image name. The `docker images` command returns 
  - `safraz/javabuild` as image name
  - and `ad4c3a9e7cfd` as image id

The `docker pull` command takes `name:[tag]` as parameter.
Then, as @davidxia said, you have to push `safraz/javabuild` and not `ad4c3a9e7cfd`.

**Comment by safrazhanas** [comment]
thanks @davidxia and @fraisse 

i could solve this issue sometime back. couldn't update this thread.
