### ISSUE TITLE
com.spotify.docker.client.messages.HostConfig.Bind.Builder: add support for selinux label

### ISSUE THREAD

**Issue by psefranek** [spotify/docker-client#882]
Can you please consider adding another method to class com.spotify.docker.client.messages.HostConfig.Bind.Builder
allowing us to specify mount option ("z/Z") used in selinux enabled host environment?

As specified at https://docs.docker.com/engine/admin/volumes/bind-mounts/#configure-the-selinux-label
I am proposing builder method selinuxLabel(boolean shared). When shared is true lower case letter "z" is added to List<String> options field. Otherwise, label is considered as unshared and upper case letter "Z" is used instead.

Thanks and keep up the good work!

**Comment by mattnworb** [comment]
Sounds reasonable. If you have the time to create a pull request to add this functionality then that will likely help get it completed faster than someone else could get to it.

**Comment by psefranek** [comment]
Hi @mattnworb, thanks for evaluating my idea. Based on your suggestion I have just created a pull request - https://github.com/spotify/docker-client/pull/883
