### ISSUE TITLE
Need timeout for docker.waitContainer(containerId)

### ISSUE THREAD

**Issue by kqiang** [spotify/docker-client#888]
## Description

We use docker to execute some UI tests. We are trying to find if there is a timeout that we can set so that when the UI test hangs we can terminate it within the timeout.

**Comment by mattnworb** [comment]
Looks like currently there is not; using current versions of docker-client you would need to build this logic yourself in your application code (in a loop: check if the container is running, sleep for some time, check if the timeout has elapsed, repeat)

**Comment by mattnworb** [comment]
It appears that the [Docker Remote API operation for waitContainer](https://docs.docker.com/engine/api/v1.31/#operation/ContainerWait) doesn't support passing a timeout value, so I don't think it is likely that we would add this support in docker-client itself.
