### ISSUE TITLE
could not load FFI provider jnr.ffi.provider.jffi.Provider

### ISSUE THREAD

**Issue by Gmapoub** [spotify/docker-client#894]
## Description

Try to pull a public docker hub registry on local machine

## How to reproduce

- get all jars from https://jar-download.com/?search_box=docker-client
docker-client from group com.spotify (version 8.9.0)
- java code:

```
        try {
            final DockerClient docker = DefaultDockerClient.fromEnv().build();
            docker.pull("nginx");
            Util.dm("docker done");
        } catch (DockerCertificateException ex) {
            System.out.println("Get Image1 "+s+" Failed!");
            System.out.println(ex);
        } catch (DockerException ex) {
            System.out.println("Get Image2 "+s+" Failed!");
            System.out.println(ex);
        } catch (InterruptedException ex) {
            System.out.println("Get Image3 "+s+" Failed!");
            System.out.println(ex);
        }
```
or 

```
        try {
            final DockerClient docker = DefaultDockerClient.fromEnv().build();
            final RegistryAuth registryAuth = RegistryAuth.builder()
                .email("test@test.com")
                .username("test")
                .password("")
                .build();
            docker.pull("nginx", registryAuth);
            Util.dm("docker done");
            return true;
        } catch (DockerCertificateException ex) {
            System.out.println("Get Ressource "+s+" Failed!");
            System.out.println(ex);
        } catch (DockerException ex) {
            System.out.println("Get Ressource "+s+" Failed!");
            System.out.println(ex);
        } catch (InterruptedException ex) {
            System.out.println("Get Ressource "+s+" Failed!");
            System.out.println(ex);
        }
```
From https://github.com/spotify/docker-client/blob/master/docs/user_manual.md#create-an-image

## What do you expect

image pulled without creating a .dockercfg

## What happened instead

image not here

## Software:

- `docker version`: 
```
Client:
 Version:      17.05.0-ce
 API version:  1.29
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:10:54 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.05.0-ce
 API version:  1.29 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:10:54 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

- Spotify's docker-client version:  8.9.0

## Full backtrace

```text
20:55:13.228 [Thread-2] DEBUG com.spotify.docker.client.DockerCertificates - /home/poub/.docker/ca.pem, /home/poub/.docker/key.pem or /home/poub/.docker/cert.pem does not exist, not using SSL
20:55:13.392 [Thread-2] DEBUG com.spotify.docker.client.DockerConfigReader - Using configfile: /home/poub/.dockercfg 
Get Image2 nginx Failed!
com.spotify.docker.client.exceptions.DockerException: java.util.concurrent.ExecutionException: javax.ws.rs.ProcessingException: java.lang.UnsatisfiedLinkError: could not load FFI provider jnr.ffi.provider.jffi.Provider

$ ls /home/poub/.dockercfg
No file or directory
```
I miss something but where....

**Comment by johnflavin** [comment]
Are you using the shaded jar? See https://github.com/spotify/docker-client#a-note-on-shading

**Comment by Gmapoub** [comment]
@johnflavin Thank you for your answer.
Hum, no. I don't think so. I took the jar docker client jar file from here https://mvnrepository.com/artifact/com.spotify/docker-client/8.9.0

**Comment by johnflavin** [comment]
I am not sure what is in those jars, as I'm not familiar with those repositories. I would try getting the shaded jar from maven central. Here is a search that returns all the docker-client jars: http://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22com.spotify%22%20AND%20a%3A%22docker-client%22; and here is a link to the latest shaded jar: http://repo1.maven.org/maven2/com/spotify/docker-client/8.9.0/docker-client-8.9.0-shaded.jar.

**Comment by Gmapoub** [comment]
Oh this way. Ok I'll try. Thanks for your time.

**Comment by Gmapoub** [comment]
Same trouble with shaded.

**Comment by Gmapoub** [comment]
OK i think i've found an issue there is a problem between this jar httpcore-4.0.1.jar and this one httpcore-4.4.5.jar

**Comment by Gmapoub** [comment]
It looks it came from docker.pull("nginx");

**Comment by davidxia** [comment]
@Gmapoub Not sure I understand the problem here. Are you able to run any DockerClient methods like `ping()` or `version()`?

**Comment by Gmapoub** [comment]
Hi @davidxia
Sorry, I finally used Docker-Java and I've found a conflict between two dependencies on the program I was working for. Maybe it was the problem, here.
Thank you for your time, and so sorry that i didn't close that issue before :(

**Comment by davidxia** [comment]
It’s OK. I’ve seen this problem before as well. It’s very misleading.
-- 
David Xia
Software Engineer
dxia@spotify.com
