### ISSUE TITLE
Release 8.9.1 ?

### ISSUE THREAD

**Issue by sanjaypujare** [spotify/docker-client#896]
## Description

This is more of a question than an issue: the readme file says "Commits to the master branch will trigger our continuous integration agent to build the jar and release by uploading to Sonatype." but that doesn't seem right (unless I misunderstood). In any case the latest release I see on search.maven.org is 8.9.0. When will I see 8.9.1? And what is in general the process to get a new release?

Also is there a different forum to ask such questions?

**Comment by mattnworb** [comment]
This is the right place for such questions :) We no longer automatically do a release after each commit to master, so I'll remove that misleading statement from the readme.

**Comment by sanjaypujare** [comment]
Thanks @mattnworb . When is 8.9.1 scheduled to come out?

**Comment by johnflavin** [comment]
I would also like to see a 8.9.1 release soon. I plan to put out a release of my project soon which relies on some of the PRs I've put in recently. I could always push my own custom `8.9.1-some-specific-identifier` version to our repository that's just for me to use, but it would be nice to avoid that if I can.

**Comment by mattnworb** [comment]
I'll cut a release now.

**Comment by mattnworb** [comment]
8.9.1 should be on its way to maven central now 🚀

**Comment by sanjaypujare** [comment]
Thanks
