### ISSUE TITLE
Question:  is there a way to pass environment variables to a Docker Container?

### ISSUE THREAD

**Issue by rwmajor2** [spotify/docker-client#897]
..such as using the command line docker -e flag?

**Comment by mattnworb** [comment]
Yep, through the `ContainerConfig.env` list IIRC https://github.com/spotify/docker-client/blob/7b69b289db9a6b4f5ca7cabf4a78bbdadedc81c4/src/main/java/com/spotify/docker/client/messages/ContainerConfig.java#L91-L93

**Comment by Tommassino** [comment]
Maybe this could be better documented, since there is no way to know how this string is supposed to be formatted (its not on the wiki or documented in code). Ofc I can infer from the way the cmdline params are being used, but i have to actually test it to verify that it is the case.

**Comment by johnflavin** [comment]
Like so many things in this library, you really should be checking with docker's API documentation for how to format these. We aren't trying for `docker-client` to emulate the `docker` CLI, but to be a client for docker's remote API. When in doubt about how something works, check if docker has API documentation on it.

(...but that doesn't completely avoid your point, in that the advice I just gave 👆 up there should be documented somewhere here.)

**Comment by gentunian** [comment]
Is `env()` supported with `docker stack deploy`? I'm getting an empty list:

```java
if (eventStream.hasNext()) {
  event = eventStream.next();

  // Action enum type: START("start")
  if (event.action().equals(Action.START)) {
    final ContainerInfo info = docker.inspectContainer(event.actor().id());

    for (String e: info.config().env()) {
       System.out.println("\Env: " + e);
    }
  }
}
```

**Comment by jclinto-siegefx** [comment]
What is the syntax for -e? Having an issue with this.

**Comment by algakzru** [comment]
According to the [docker API documentation](https://docs.docker.com/engine/api/v1.39/#operation/ContainerExec) it supports passing environment variables in  /containers/{id}/exec endpoint.

I tried to do it in docker-client :
```
ExecCreation execCreation = docker.execCreate(
                containerId,
                new String[]{"sh", "-c", "env | grep VIDEO_FILE_NAME"},
                new DockerClient.ExecCreateParam("Env", Arrays.toString(new String[]{"VIDEO_FILE_NAME=test"})));
```

but it throws a DockerRequestException:
```
com.spotify.docker.client.exceptions.DockerRequestException: Request error: POST http://172.16.2.50:2376/containers/94db27b500ab27a91ea2345ccc43647e7402cf496f2bea07594b6783ca0eceac/exec: 400, body: {"message":"json: cannot unmarshal string into Go struct field ExecConfig.Env of type []string"}
```

Is it possible to pass environment variables in ExecCreation ?
If yes, how to do it ?
