### ISSUE TITLE
API changes report for Docker Client

### ISSUE THREAD

**Issue by lvc** [spotify/docker-client#899]
The review of API changes for the Docker Client library since 3.0.0 version: https://abi-laboratory.pro/java/tracker/timeline/docker-client/

Hope it will be helpful for users and maintainers of the library.

The report is generated for jars found at http://central.maven.org/maven2/com/spotify/docker-client/ according to https://wiki.eclipse.org/Evolving_Java-based_APIs_2.

Thank you.

![docker-client-2](https://user-images.githubusercontent.com/1517837/31113359-a0c7a314-a821-11e7-84ef-742d423422e7.png)
![docker-client-1](https://user-images.githubusercontent.com/1517837/31113358-a0c5947a-a821-11e7-9653-91ce0de64b4f.png)

**Comment by johnflavin** [comment]
This is certainly interesting. But I'm not sure how to interpret this information, or how to make it actionable. Is this good? Is this bad?

**Comment by lvc** [comment]
> how to interpret this information

1. Check detected breaking changes by following "red" links in the compatibility table
2. If such changes are really breaking changes (not part of the private API) then try to avoid such changes in future releases of the library in order to improve backward compatibility.

> Is this good? Is this bad?

The backward compatibility rate of the library is good relative to other Java projects analyzed (several hundreds).

For detailed info on binary compatibility in Java see https://wiki.eclipse.org/Evolving_Java-based_APIs_2.

Thank you.
