### ISSUE TITLE
Physical host went to panic mode when running docker for 8 hours

### ISSUE THREAD

**Issue by kqiang** [spotify/docker-client#901]
We are using spotify maven version 8.8.2 to execute the docker container. There are 4 thread executes the container, each execute it every 5 minutes on a single host.

Here is the host environment:
CentOS release 6.5 (Final),  Kernel 2.6.32-431.el6.x86_64, physical host., Docker version 1.7.1, build 786b29d/1.7.1

We found that after it running for 8 hours, the physical hosts went to the panic mode. This behavior can be reproduced. But we didn't see this issue when use the VM with the same environment.

Could you let me know if this is a known issue with the older docker version? 
We are planning to upgrade to CentOS7 so that we can install the latest docker version on it. But still don't know if this issue will happen again in the latest Docker version.

**Comment by mattnworb** [comment]
Sounds to me like you should report this in the docker project’s issue tracker, as docker-client is just a java-based way to communicate with the API that the docker daemon exposes.

**Comment by kqiang** [comment]
Since I am using the spotify API to access docker, I just want to check if there is such issue in the latest docker version when use with the spotify API.

**Comment by mattnworb** [comment]
No, I don't think we have ever seen any issues caused by using `docker-client` as the API client that would result in a panic. I strongly suggest bringing up the panic with the main docker project and trying to troubleshoot the cause of that further.
