### ISSUE TITLE
Attach to container should not require container to be running

### ISSUE THREAD

**Issue by mustafaakin** [spotify/docker-client#905]
## Description

Current implementation, attach function checks whether the container is working and throws an exception. While the API does not specify that behavior, the docker cli also behaves the same way unfortunately. 

However, when you create and start a container, you might not attach fast enough, so that you lose some of the output, or you might not catch it all, because it closes. Instead, you create the container, attach to it, and start it in another thread so that you do not miss anything. 

## How to reproduce

```
$ docker create --name m1 alpine ps aux
$ nc -U /var/run/docker.sock
POST /containers/m1/attach?stream=1&stdout=1 HTTP/1.1
Upgrade: tcp
Connection: Upgrade
Host: localhost
```

```
# another shell
$ docker start m1
```

```
# previous shell
$ nc ...
...
HTTP/1.1 101 Switching Protocols
Connection: Upgrade
Content-Type: application/vnd.docker.raw-stream
Upgrade: tcp
Date: Thu, 19 Oct 2017 11:49:11 GMT

PID   USER     TIME   COMMAND
    1 root       0:00 ps aux

```

## What do you expect

Not throw an exception because container is not running

## What happened instead

This happened:

https://github.com/spotify/docker-client/blob/master/src/main/java/com/spotify/docker/client/DefaultDockerClient.java#L1513-L1516

## Software:

Docker:  17.09.0-ce
Spotify Docker Client: 8.9.1

I am happy to send a pull request if you wish. This affects my use case, and it is how it is implemented in the golang library as well.

**Comment by johnflavin** [comment]
This is pretty interesting. I had assumed that, because the CLI client did not allow this behavior, that the API also did not allow it. But, you’re right, the API absolutely allows you to attach to a created container that has not yet been started.

I reproduced this API behavior using `curl`.
```bash
[Terminal 1]$ docker create --name m1 alpine ps aux

[Terminal 2]$ curl --unix-socket /var/run/docker.sock -X POST http://localhost/containers/m1/attach\?stream=1\&stdout=1
...

[Terminal 1]$ docker start m1

[Terminal 2]
...
PID   USER     TIME   COMMAND
    1 root       0:00 ps aux
```

I don't have any problem with `docker-client` supporting this API behavior, rather than reproducing the behavior of the `docker` CLI. Thoughts, @mattnworb @davidxia ?

**Comment by mattnworb** [comment]
Sounds good to me. I am surprised [the API documentation for attaching](https://docs.docker.com/engine/api/v1.32/#operation/ContainerAttach) doesn't mention anything related to this.

**Comment by davidxia** [comment]
SGTM too. PRs welcome
