### ISSUE TITLE
Need an option to suppress progress messages

### ISSUE THREAD

**Issue by testphreak** [spotify/docker-client#909]
## Description

When I pull an image for example, I would like a set a boolean flag on the pull method, to turn off progress messages. As a client, I am only concerned with knowing if the image was pulled down to the host successfully.

## How to reproduce

Pull any image with the DockerClient `pull` method.

## What do you expect

I would like to be able to set a flag on the pull method, for example `enableProgressMessage`, which can be true by default if majority of the folks like the progress messages. If set to false, it will pull the image silently and return a `String` with a 200/success message.

## What happened instead

When the pull method is called, it prints out the status of every progress message on the console.

## Software:

- docker version: 
```
Version{apiVersion=1.29, arch=amd64, buildTime=2017-05-04T22:10:54.638119411+00:00, gitCommit=89658be, goVersion=go1.7.5, kernelVersion=4.4.0-77-generic, os=linux, version=17.05.0-ce}
```
- Spotify's docker-client version: `8.9.1`

**Comment by mattnworb** [comment]
You can use this method in DockerClient that takes a ProgressHandler, and just pass it a no-op implementation: https://github.com/spotify/docker-client/blob/fe60e58bcc18d936b62aac54ef620f1be1a69a81/src/main/java/com/spotify/docker/client/DockerClient.java#L426

for example:

```java
final ProgressHandler silentHandler = message -> { };
dockerClient.pull("foobar", silentHandler);
```

**Comment by testphreak** [comment]
That worked! Thank you @mattnworb!

**Comment by mslinn** [comment]
Here is the incantation for the Scala folks:
```
dockerClient.pull("foobar", (_: ProgressMessage) => ())
```
