### ISSUE TITLE
What's the difference between DockerClient.createContainer() and execCreate()?

### ISSUE THREAD

**Issue by cowwoc** [spotify/docker-client#912]
## Description

Please update the documentation to explain the difference between the `createContainer()` and `execCreate()` methods.

## API version: 8.9.1

**Comment by mattnworb** [comment]
Do the javadocs in the interface help explain this at all?

https://github.com/spotify/docker-client/blob/fe60e58bcc18d936b62aac54ef620f1be1a69a81/src/main/java/com/spotify/docker/client/DockerClient.java#L813-L825

https://github.com/spotify/docker-client/blob/fe60e58bcc18d936b62aac54ef620f1be1a69a81/src/main/java/com/spotify/docker/client/DockerClient.java#L1405-L1416

These map one-to-one to the [ContainerCreate](https://docs.docker.com/engine/api/v1.33/#operation/ContainerCreate) and [ContainerExec](https://docs.docker.com/engine/api/v1.33/#operation/ContainerExec) methods in the Docker Remote API.

**Comment by cowwoc** [comment]
@mattnworb The name `ContainerExec` and the description they provide (Run a command inside a running container) makes perfect sense to me.

I don't understand why this API's method name has "create" in it. It let me to believe that the command was somehow creating a new container. I also feel that "Run a command inside a running container" is a lot more descriptive than "sets up an exec instance [...]". I don't even know what an "exec instance" means in this context. This description requires me to be aware of some terminology that isn't immediately referenced by the Javadoc.

Consider adopting the Docker Remote API naming convention and documentation if possible, and referencing their documentation from your own using `@see` tags.

**Comment by cowwoc** [comment]
Maybe by `exec instance` you meant that you are running the equivalent of `docker exec`. If so, using the latter terminology would be clearer to end-users.

**Comment by davidxia** [comment]
@cowwoc, thanks for the issue report.

> Consider adopting the Docker Remote API naming convention and documentation if possible

I think we are using language verbatim from the [remote Docker API docs](https://docs.docker.com/engine/api/v1.30/#operation/ContainerExec). 

> referencing their documentation from your own using @see tags

This would be a good idea but their API docs require specific version numbers. I haven't thought of a good place to link.

I'm going to close this issue as your original question has been answered.
