### ISSUE TITLE
authForSwarm warning when createService method called without supplying auth

### ISSUE THREAD

**Issue by testphreak** [spotify/docker-client#913]
## Description

According to the JavaDoc, I should be able to call `createService` with just the ServiceSpec object. But it appears that if I don't supply the AuthSupplier object, it prints a warning in the console `[WARNING] authForSwarm not implemented in this class`. Is it possible to not have `createService(serviceSpec)` print this warning?

## How to reproduce

Call the `createService` method with a valid ServiceSpec object.

## What do you expect

No warning should be printed.

## What happened instead

It prints the following log line when creating a service.
`[WARNING] authForSwarm not implemented in this class`

## Software:

- `docker version`: 
```
Version{apiVersion=1.29, arch=amd64, buildTime=2017-05-04T22:10:54.638119411+00:00, gitCommit=89658be, goVersion=go1.7.5, kernelVersion=4.4.0-77-generic, os=linux, version=17.05.0-ce}
```
- Spotify's docker-client version: `8.9.1`

**Comment by mattnworb** [comment]
I think it would be fair to simply remove this log line, it probably doesn't add any value. I think the intent may have been to just be proactive about letting someone know that no authentication info would be set up with swarm, *in case* that caused problems down the line.

https://github.com/spotify/docker-client/blob/12d428fe329c9aa6ee89741d27b80abffd512717/src/main/java/com/spotify/docker/client/auth/ConfigFileRegistryAuthSupplier.java#L94-L98

**Comment by testphreak** [comment]
Thanks @mattnworb! Would be nice if this log line is removed with the next release.

**Comment by davidxia** [comment]
Remove log msg altogether or demote to debug level?

**Comment by testphreak** [comment]
Remove it all together since I am only passing in the `ServiceSpec`object.

```java
ServiceCreateResponse createResponse = dockerClient.createService(serviceSpec);
```

If I was passing in `RegistryAuth` as well to the `createService` method, then the warning message makes sense I guess.
