### ISSUE TITLE
Add example of starting containers in detached mode

### ISSUE THREAD

**Issue by cowwoc** [spotify/docker-client#914]
## Description

Please add an example to the Wiki of how to run the equivalent of `docker run -d` using this API. It took me a while to figure this out. I eventually stumbled upon https://stackoverflow.com/a/29548606/14731

**Comment by ahab94** [comment]
Hey @cowwoc, 
```Java
ContainerConfig.builder()
        .hostConfig(hostConfig)
        .portSpecs(containerInfo.config().portSpecs())
        .exposedPorts(containerInfo.config().exposedPorts())
        .entrypoint(containerInfo.config().entrypoint())
        .env(containerInfo.config().env())
        .image(containerInfo.image())
        .cmd(containerInfo.config().cmd())
        .tty(true)
        .build()
```
add 
```Java 
.tty(true)
```
in your container config and this will run your containers detached.

**Comment by ahab94** [comment]
I agree it took me a while as well to figure out that ``.tty(true)`` == `-d`.
