### ISSUE TITLE
Start container inside an application running in a container

### ISSUE THREAD

**Issue by CSGrimey** [spotify/docker-client#917]
Hi,

I have a couple of lines of code that creates a DefaultDockerClient using the default unix socket ("unix:///var/run/docker.sock").
It then calls listImages, which returns at the moment, 39 images.
Then it calls startContainer using a known container id.
I then call waitContainer with that same container id, and returns the status code once that container has finished.

The test container just runs a bash command that sleeps for 10 seconds, then exits.
My goal is to find out whether the container being started in the code is inside the docker container calling it, or whether it is alongside the docker container calling it.

This all works when running the application via a terminal.
But once I put this application inside a docker container, all calls to the spotify library fail with  "java.util.concurrent.ExecutionException: javax.ws.rs.ProcessingException: java.io.IOException: No such file or directory"

My docker run command looks like so:
docker run -it --name dockerservice -v /opt:/opt -v /data/logs:/log docker-service

This tells me that the container calling the startContainer cannot see the containers on the host.

My questions are:
. When code inside a docker container calls startContainer, where is the resulting container located? Is it inside the docker container that calls startContainer? Or does startContainer call the host and that host creates the container alongside the callee container?
. How could I get the container started to live outside the calling docker container? Do I need to map the unix socket of the container to the unix socket of the host somehow in order to achieve this?

I'm new to docker, so excuse my lack of understanding in it.

**Comment by mattnworb** [comment]
Hey, it would be helpful if you could post the full stacktrace of the exception.

My guess would be that inside your container, `/var/run/docker.sock` does not exist. Your code is trying to use this file/path/unix socket to communciate with docker. So essentially, the code inside your container has no way to communicate with the docker daemon.

A common pattern you'll see for when containers need to spawn other containers or communicate with the docker daemon in general is to just mount `/var/run/docker.sock` as another volume in the `docker run` command. This way your container can talk to the docker daemon on the host, and if it needs to launch another container it can do so (on the docker daemon _on the host_).

Another option is to use https://hub.docker.com/_/docker/ but I think that most of the time when someone wants a container to interact with docker, but it doesn't sound to me like you want a second / completely separate docker installation here.

**Comment by CSGrimey** [comment]
Hi Matt, thank you for your fast reply.

So I'd just need to add "-v /var/run/docker.sock:/var/run/docker.sock" to the end of my docker run command? 
Though thinking about it, I don't know if you can map files, just directories.
I suppose I would also need to create the /var/run/docker.sock file in the container via my entrypoint, right?

**Comment by CSGrimey** [comment]
I've added the volume to the socket as you mentioned and created the directory and socket file in my entrypoint and it seems to work now. So thank you very much for that.
Now I just need to find out whether it created the container alongside the callee container in the host. I'll report back my findings.

**Comment by mattnworb** [comment]
If you mount `/var/run/docker.sock` from the host inside a container and then inside that container you communicate with `/var/run/docker.sock` to create containers, then those containers are "alongside" each other as you put it.

```
docker on host 
\
 - container1
 - container2 (created from code running in container1)
```
