### ISSUE TITLE
How to associate a container to a node?

### ISSUE THREAD

**Issue by ViniciusDeAndrade** [spotify/docker-client#926]
Hi.
I set up on my _dockercompose.yaml_ file some services, and there are some in one node, and 
some in another.

I have searched of how, in this java client, we can get the information of...: in which node a specified container is running. Or, which containers are running in that node...

Can someone help me? 
PS.: I already tryed almost everything in this class to get what I want

```
package main;

import java.util.List;

import com.spotify.docker.client.DockerClient;
import com.spotify.docker.client.exceptions.DockerException;
import com.spotify.docker.client.messages.Container;
import com.spotify.docker.client.messages.Image;
import com.spotify.docker.client.messages.swarm.Node;

public class Cluster {

	public void containers(DockerClient docker) throws DockerException, InterruptedException {
		List<Container> list = docker.listContainers();
		for(int i = 0; i< list.size(); i++)
			System.out.println(list.get(i).toString());
	}

	public void nodes(DockerClient docker) throws DockerException, InterruptedException {
		List<Node> list = docker.listNodes();
		for(int i = 0; i< list.size(); i++)
			System.out.println(list.get(i).description().toString());
	}

	public void images(DockerClient docker) throws DockerException, InterruptedException {
		List<Image> list = docker.listImages();
		for(int i = 0; i< list.size(); i++)
			System.out.println(list.get(i).toString());
	}
}

```

**Comment by davidxia** [comment]
I'm not that familiar with Docker compose or swarm but here goes. I assume you're using docker compose to deploy multiple containers to a swarm cluster made of multiple docker instances/nodes?

> in which node a specified container is running

DockerClient only talks to one remote Docker API at a time. It can't tell you on which swarm node a container is running.

> Or, which containers are running in that node.

DockerClient.listContainers() will tell you which containers are running on a node.

Does this answer your question?

**Comment by ViniciusDeAndrade** [comment]
I already got (I think) the answer. DockerClient.listContainers() give me all the containers, but the data inside which one has no reference about the node. As well as if I catch all the nodes, they also do not have any reference to the containers running on them.

So, without going into details, the solution is inside the dockerInspect method from DockerClient class passing the id of the container.

Thanks
