### ISSUE TITLE
Simpler 'oneliner' example for the README please

### ISSUE THREAD

**Issue by paul-hammant** [spotify/docker-client#936]
Here's the Python one-liner for docker:

```
docker.from_env().containers.run("org/repo", name="aNameForIt", detach=True, ports={'80/tcp': 8080}, auto_remove=True)
```

It'd be great to have a oneliner in the README  to make it easy for people to get going quickly.

**Comment by mattnworb** [comment]
The [user manual doc](https://github.com/spotify/docker-client/blob/master/docs/user_manual.md) has a bunch of examples of how to use the library - do any of those work for you?
