### ISSUE TITLE
How to achieve --network-alias functionality 

### ISSUE THREAD

**Issue by sathipal** [spotify/docker-client#938]
## Description

This is more of a query rather than a bug. 

I would like to understand how to achieve --network-alias functionality using this docker-client project? 

for example,

`docker run -d --net-alias=alias1 --network=custome-bridge <image>`

This options allows the embedded DNS server to maintain the mapping between all of the container aliases and its IP address on a specific user-defined network.

**Comment by vovapolu** [comment]
Any progress on this issue?

**Comment by emcas88** [comment]
This would be nice to have
