### ISSUE TITLE
Why does "tcp://..." not work but "http://..." works

### ISSUE THREAD

**Issue by sanjaypujare** [spotify/docker-client#946]
## Description

While using the docker-client API we have to specify the docker-host as "http://..." and NOT "tcp://..." although the dockerd start command used -H "tcp://..." . 

## How to reproduce

Any code try to use

```
DefaultDockerClient("tcp://localhost:2376");
```

## What do you expect

If the connection between the docker-client and dockerd is indeed tcp and not http it should accept "tcp://.." as the protocol specifier.

## What happened instead

We got "UnsupportedSchemeException:

![image](https://user-images.githubusercontent.com/14166415/33866272-6ac14454-deaa-11e7-9188-5f89007e49ad.png)

## Software:

- `docker version`: 
```
Client:
 Version:      17.06.1-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   874a737
 Built:        Thu Aug 17 22:53:38 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      17.06.1-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   874a737
 Built:        Thu Aug 17 22:54:55 2017
 OS/Arch:      linux/amd64
 Experimental: true

```
- Spotify's docker-client version: 8.9.1

## Full backtrace

![image](https://user-images.githubusercontent.com/14166415/33866272-6ac14454-deaa-11e7-9188-5f89007e49ad.png)

**Comment by stefiane** [comment]
Check source ,you will know. Source code is as follows:
**```
public DefaultDockerClient(final String uri) { 
     this(URI.create(uri.replaceAll("^unix:///", "unix://localhost/"))); 
  }
```** 

REST API doesn't support tcp protocol, so you only use http protocol.

**Comment by anmarpei** [comment]
So, sanjaypujare , how you solve that issue? How you finally config your docker-client?
If you could paste here an example, it would be great, ;)

Thanks

**Comment by sanjaypujare** [comment]
Didn't fix anything. Just got the end users to use "http://" instead of "tcp://" which was sent to the API. BTW, my impression is that for dockerd the "tcp" protocol is basically http i.e. it accepts http protocol commands etc. So there is no basic "tcp" protocol that accepts some binary or non-http payload. Somebody can correct me if I am wrong.

**Comment by anmarpei** [comment]
Thanks for the response,
I was trying in both ways and finally i choose other library. In my case Java Docker API Client (https://github.com/docker-java/docker-java) goes OK defining the conecction with TCP protocol.

Thanks,
