### ISSUE TITLE
Exposed ports not work for containers

### ISSUE THREAD

**Issue by man4j** [spotify/docker-client#956]
ContainerCreation creation = swarmService.getDocker().createContainer(ContainerConfig.builder().hostConfig(HostConfig.builder().autoRemove(false).portBindings(Collections.singletonMap(port + "/tcp", Collections.singletonList(PortBinding.of("", port + "")))).build())
                                                                 .exposedPorts(port + "/tcp")
                                                                 .image("alpine")
                                                                 .build());

swarmService.getDocker().startContainer(creation.id());

## What do you expect
docker inspect 2a867de7940d | grep Exposed
empty

[Describe what do you expect to happen]
docker inspect 2a867de7940d | grep Exposed
"ExposedPorts": {

## Software:
17.09.0-ce
8.9.1

**Comment by man4j** [comment]
from docker API:

ExposedPorts
An object mapping ports to an empty object in the form:

{"<port>/<tcp|udp>": {}}

**Comment by man4j** [comment]
from client implementation:

ImmutableSet<String> exposedPorts

**Comment by jjohnstn** [comment]
I am running into this issue as well using docker-client API.  We are setting the exposedPorts via the API and expect to be able to get back host ports once the container is created.  We are seeing no ports in the Container info network settings and looking at the ContainerConfig post-creation, it has no exposedPorts specified (i.e. has thrown away our request).
