### ISSUE TITLE
Question (Maybe bug?) about NetworkConfig and NetworkingConfig

### ISSUE THREAD

**Issue by shpendk** [spotify/docker-client#964]
## What i am trying to do
I am trying to tell my container that i'm creating programmatically, to use the "bridge" driver. The plan was to use code like this:
```
final NetworkConfig networkConfig = NetworkConfig.builder().driver("bridge").build();

final ContainerConfig containerConfig = ContainerConfig.builder()
                .networkConfig(networkConfig)
```
However there is no `.networkConfig` method, instead its called network**ing**Config . It also expects an object of type Network**ing**Config, is this expected?

## How to reproduce

Simply try the code above and you'll see a compilation error

## What do you expect

Not sure. I was hoping there is an easy way to pass a network config, just like you can do `.hostConfig()` to pass a host configuration object. Any ideas on how to do that i'd appreciate. 

## Software:

- `docker version`: `Docker version 17.09.0-ce, build afdb6d4`
- Spotify's docker-client version: 8.10.1

**Comment by johnflavin** [comment]
The names we have for the classes, while confusing, does follow the naming conventions for docker's remote API. 

The `NetworkConfig` object is only used to create a new network in the `dockerClient.createNetwork(networkConfig)` method.

When you are creating a container that uses a network, you have to make a `NetworkingConfig` object—which is nothing but a thin wrapper around an `EndpointConfig` object—and pass that into the `ContainerConfig`.

**Comment by shpendk** [comment]
Oh i see, thanks a lot for the quick answer @johnflavin. Just wanted to be sure i didn't stumble upon a naming issue. 

I'll close the issue since it is effectively resolved.
