### ISSUE TITLE
Assigning a maximum amount of memory to a container.

### ISSUE THREAD

**Issue by TheMasteredPanda** [spotify/docker-client#965]
Forgive me if I haven't looked hard enough, but I cannot see an instant messaging platform that Spotify uses to discuss such queries. 

My query is the title. How an earth to do you it using this client?

**Comment by TheMasteredPanda** [comment]
Found my resolution.

**Comment by mattnworb** [comment]
@TheMasteredPanda could you post what you ended up using to help anyone searching for this in the future?

**Comment by TheMasteredPanda** [comment]
Of course. I simply neglected to recognize that you can assign the maximum amount of ram the container by creating a HostConfig then passing it through the necessary method when creating a ContainerConfig instance.

```java
        containerConfig = ContainerConfig.builder()
                .hostConfig(HostConfig.builder()
                        .memory(maximumMemory)
                        .build())
                .image(name + ":" + verison)
                .env(String.format("MINIMUM_ACCEPTABLE_PLAYERS_PER_GAME=%s", String.valueOf(minimumPlayers))
                , String.format("MAXIMUM_ACCEPT_PLAYERS_PER_GAME=%s", String.valueOf(maximumMemory)))
                .addVolume(mapVolumeName);
```
