### ISSUE TITLE
Specifying the name of the container when creating it?

### ISSUE THREAD

**Issue by TheMasteredPanda** [spotify/docker-client#968]
Hello, 

As stupid as it may sound I cannot see were you can specify the name of a container when creating a `ContainerConfig` instance. 

The use case for such a basic feature is for readability purposes, as you'll understand I wouldn't remember what container `tender_ptolemy` does. 

Where can I do this with this client?

Thanks,
TheMasteredPanda.

**Comment by mattnworb** [comment]
DockerClient.createContainer(ContainerConfig config, String name)
