### ISSUE TITLE
Support .dockerignore multi-directory ** wildcard

### ISSUE THREAD

**Issue by steven-sheehy** [spotify/docker-client#973]
## Description

While using the dockerfile-maven-plugin, I attempted to ignore a build artifact that could be found in any arbitrary depth of directories using the ** wildcard. It seems like docker-client does not support this wildcard operator. This particular file comes from the spring-boot-thin-launcher plugin and would be regenerated every build and cause my docker image layer to not cache between builds.

From Docker's [.dockerignore documentation](https://docs.docker.com/engine/reference/builder/#dockerignore-file):
> Beyond Go’s filepath.Match rules, Docker also supports a special wildcard string ** that matches any number of directories (including zero). For example, **/*.go will exclude all files that end with .go that are found in all directories, including the root of the build context.

This feature was added to Moby in a 2015 [pull request](https://github.com/moby/moby/pull/17090/files).

## How to reproduce

`$ cat .dockerignore`
```bash
.git
**/resolver-status.properties
```
`$ ./mvnw install`

I also tried to do multiple single star wildcards hoping I could workaround the issue and that did not seem to work either.

```bash
.git
**/resolver-status.properties
target/thin/root/repository/com/company/*/*/resolver-status.properties
```

I ran `docker build . -t test` and it ignored as expected.

## What do you expect

I expected the resolver-status.properties to be ignored and my layer to be cached since nothing had changed.

## What happened instead

It did not cache the target/thin/root/repository layer:
```bash
[INFO] Pulling from library/openjdk
[INFO] Digest: sha256:c5c705b462abab858066d412b3f871865684d8f837571c98b68e78c505dc7549
[INFO] Status: Image is up to date for openjdk:8-alpine
[INFO]  ---> 224765a6bdbe
[INFO] Step 2/6 : ADD target/thin/root/repository m2/repository
[INFO]  ---> 482ab18c95f0
```

Workaround is to specify multiple .dockerignore entries with only a single * wildcard.

## Software:

- `docker version`: 17.09.1-ce
- Spotify's docker-client version: 8.11.0

**Comment by stephenc** [comment]
Any update? This is really annoying for anyone using `docker-machine` to run an instance on EC2 as the context becomes ridiculously large copying lots of junk from everywhere... while same is not the case when using `docker build`

**Comment by yuelipku** [comment]
+1

**Comment by johnflavin** [comment]
A note in case anyone wants to do a PR to make this happen. It is in the scope of the project, in that the handling of local files is a `docker` client feature that we have re-implimented here.

The `csdc.DockerClient.build(...)` methods create a `csdc.CompressedDirectory` to store all the directory's files. That `CompressedDirectory` code does read and take into account the `.dockerignore` file, using each line in the `.dockerignore` to create a `DockerIgnorePathMatcher`. See [CompressedDirectory L384](https://github.com/spotify/docker-client/blob/master/src/main/java/com/spotify/docker/client/CompressedDirectory.java#L384). If one did want to implement this feature request, that latter inner class is where the modification would have to be made.
