### ISSUE TITLE
Creating image from docker file.

### ISSUE THREAD

**Issue by jahidshohel** [spotify/docker-client#975]
## Description
I am trying to create a an image from Dockerfile using the method -

`build(final Path directory, final String name, final String dockerfile, final ProgressHandler handler, final BuildParam... params)`

But keep getting the message `"Cannot locate specified Dockerfile:....`. In my case, lets say my Dockerfile is on location `c:\\Users\\abc\\Dockerfile.test`. And I am invoking that method like -

```
Path dockerFile=Paths.get("c:\\Users\\abc\\Dockerfile.test");
docker.build(dockerFile.getParent(), "myimage:latest", dockerFile.getFileName(), null);
```

That doesn't work. Then on 3rd param all possible values I have tried is  `Dockerfile.test`, `./Dockerfile.test`. But still the same.

I am on a Windows 7 machine with Docker toolbox (Docker version `Docker version 17.10.0-ce, build f4ffd25`.)

Any idea what wrong I am doing?

**Comment by mattnworb** [comment]
You mention that it doesn’t work, but can you describe what happens instead? Do you get an exception, an error message, etc?

**Comment by johnflavin** [comment]
If your Dockerfile name is just `Dockerfile` you can omit it. Try using the two-argument-plus-varargs form of the method (`build(Path directory, String name, final BuildParam... params)`). With your values, this would be
```java
docker.build(dockerFile.getParent(), "myimage:latest");
```

**Comment by jahidshohel** [comment]
@johnflavin I have a test docker file which is named as `Dockerfile.test`, that we use to create a test container.
