### ISSUE TITLE
Support for Docker Service Scale option

### ISSUE THREAD

**Issue by hardik2408** [spotify/docker-client#990]
## Description

I am trying to dynamically increase the number of running containers of an already running service. When I try to achieve this through shell commands (docker service scale SERVICE=REPLICAS), I am able to scale and downscale but there is no such provision in the docker-client API. 

## How to reproduce

To achieve scaling from terminal follow steps written below:
- Create a docker swarm with n machines (n >=1)

- Create a docker service with some image
>docker service create --replicas n $image_name

- Now to scale use
>docker service scale $service_name=n*2

The above steps will increase the total number of started containers by n

## What do you expect

I want something similar to happen through the API

## What happened instead

I was not able to find support for scaling in the docs

## Software:

- Docker version 17.12.1-ce, build 7390fc6
- Spotify's docker-client version: 8.11.1

**Comment by simonbernard** [comment]
I would also like to scale a service using the API. It would be great if it could be implemented!
