### ISSUE TITLE
How to define a container Name?

### ISSUE THREAD

**Issue by rwmajor2** [spotify/docker-client#991]
Question.  How do I define a Container name during creation instead of getting a default name?

  HostConfig hostConfig = HostConfig.builder()
            .portBindings(portBindings)
            .memory(nbr.getRAM() * 1024 * 1024)
            .cpuShares(nbr.getCPU())
            .build();

    ContainerConfig containerConfig = ContainerConfig.builder()
            .hostConfig(hostConfig)
            .image(dockerimage)
            .entrypoint(Stream.of("start-notebook.sh"))
            .exposedPorts(ports)
            .build();

**Comment by mattnworb** [comment]
use the `DockerClient.createContainer(ContainerConfig, String)` method:

https://github.com/spotify/docker-client/blob/a89e5bc1bb49900e87c176a04d72416be3c6f52e/src/main/java/com/spotify/docker/client/DockerClient.java#L827-L840
