### ISSUE TITLE
document how to get info on mapped ports

### ISSUE THREAD

**Issue by christophsturm** [spotify/docker-client#992]
sorry for posting this as an issue, but i could not find a mailing list.

looking at the code thats in the readme it maps a container port to a random local port:

```
// Bind container port 443 to an automatically allocated available host port.
List<PortBinding> randomPort = new ArrayList<>();
randomPort.add(PortBinding.randomPort("0.0.0.0"));
portBindings.put("443", randomPort);

final HostConfig hostConfig = HostConfig.builder().portBindings(portBindings).build();
```

later it does not seem to use that port and i have also not found any docs in the user manual on how to get port mappings. So it would be really useful if this was added to the docs or to the code in the readme.

**Comment by qfdk** [comment]
I used those code but it seems not work :( I'm looking for a solution.
I got this reponse
```
Up 3 minutes        51348/tcp                jovial_villani
```
but not which i want
```
Up 3 minutes        0.0.0.0:3000->51348/tcp                jovial_villani
```
