### ISSUE TITLE
Supporting the --volume-driver option for NFS mount plugin

### ISSUE THREAD

**Issue by jsierles** [spotify/docker-client#994]
Is there a way to use this option already? If not, could I be pointed in the right place to add it? Thanks!

**Comment by zhangxy1035** [comment]
can you solve this problem ，I don't know how to set api to achieve nfs   
is there have some example


my docker cmd is
`docker volume  create --driver local --opt type=nfs --opt o=addr=192.168.10.8,rw --opt device=:/nfsdir --name volume-nfs`
