### ISSUE TITLE
Is the "--add-host" flag supported in any way with the client?

### ISSUE THREAD

**Issue by Shabirmean** [spotify/docker-client#995]
## Description

I am trying to start a container with updates to the **/etc/hosts** file using the **"--add-host"** feature available in docker. I want to know whether this is supported by the spotify client and if so can I get some direction as to where can I find an example as to how to use it?

PS: I looked up previous issues and I couldn't find any. If this was already addressed please excuse me and link me to that thread.

Thank you

**Comment by speza** [comment]
I believe this property is called `ExtraHosts` when using the REST API and is part of the `HostConfig` class. 

Docker docs:

> ExtraHosts - A list of hostnames/IP mappings to add to the container’s /etc/hosts file. Specified in the form ["hostname:IP"]

You need to specify this when you create your container, passing in a `ContainerConfig` that includes the `HostConfig` `ExtraHosts` value set.

```
HostConfig hostConfig = HostConfig.builder()
        .extraHosts("hostname:IP")
        .build();

ContainerConfig containerConfig = ContainerConfig.builder()
        .hostConfig(hostConfig)
        .build();

client.createContainer(containerConfig);
```

**Comment by Shabirmean** [comment]
@speza - have you experimented this? I tried doing this. However, when I do this my **/etc/hosts** has no content at all and is empty? Is there something I am missing. When I start the container with the usual **--add-hosts** flag manually it's all fine.

**Comment by mattnworb** [comment]
@Shabirmean can you post an example of the code you are using that is not working for you?

**Comment by Shabirmean** [comment]
Yes sure.

```java
final HostConfig hostConfig = HostConfig.builder()
                        .extraHosts(contHostname + ":" + newIpAdd)
                        .binds(container.getMounts())
                        .build();

final ContainerConfig containerConfig = ContainerConfig.builder()
                        .image(container.getImage())
                        .hostConfig(hostConfig)
                        .hostname(contHostname)
                        .networkDisabled(true)
                        .tty(true)
```

After the container is spawned, the **/etc/hosts** file is empty.

Also, *(if it matters)* my ***Dockerfile*** creates a user inside the container and it is not as root user that the container is spawned.

```html
Client:
 Version:      17.05.0-ce
 API version:  1.29
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:10:54 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.05.0-ce
 API version:  1.29 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:10:54 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Comment by mattnworb** [comment]
Just to rule it out, have you tried using the same code with a version of your image that doesn’t use the non-root user?

**Comment by Shabirmean** [comment]
@mattnworb - No I haven't tried it. Do you want me to try that?
Also, note that I start the container with *network=disabled*

**Comment by mattnworb** [comment]
Whether or not `networkDisabled` also disables the extra hosts config would seem to be more of a question of how Docker and it's API works - I'm not too sure of the answer - but I'd suggest playing with different combinations of the options to see if either of those two are influencing the behavior you are seeing.

**Comment by Shabirmean** [comment]
As a workaround to this I am doing an **exec** with **_"echo {etc_hosts_entry} > /etc/host"_** with **-u root** (as root user)
